<div id="headline">
    <h2><?php echo $this->lang->L_HEADER_EXPORT;?></h2>
</div>
<h4><?php echo $this->lang->L_EXPORT_COMMIT_FILES_VCS;?></h4>
<?php if (isset($this->commitResult['stdout']) && strlen($this->commitResult['stdout']) > 0) { ?>
<table class="bdr more-padding" summary="Export result">
    <tr class="thead">
        <th><?php echo $this->lang->L_EXPORT_VCS_OUTPUT;?></th>
    </tr>
    <tr class="row-odd">
        <td><pre><?php echo $this->out($this->commitResult['stdout']); ?></pre></td>
    </tr>
</table><br/>
<?php } ?>
<?php
if (isset($this->commitResult['stderr']) && strlen($this->commitResult['stderr']) > 0) {
    $this->popUpMessage()->addMessage(
        'vcsError',
        $this->lang->L_EXPORT_VCSERROR,
        $this->commitResult['stderr'],
        array(
            'modal' => true,
            'autoOpen' => true,
            'dialogClass' => 'error',
        )
    );
}
?>
<a href="<?php echo $this->baseUrl();?>/export/index/" class="Formbutton"><?php echo $this->getIcon('ArrowLeft','');?> <?php echo $this->lang->L_BACK_TO_OVERVIEW;?> </a>
