<?php
$i = 1;
$export = $this->export;
?>
<h2><?php echo $this->lang->L_HEADER_EXPORT;?></h2>
<h4><?php echo $this->lang->L_EXPORT_FILE_STATUS_DOWNLOAD_PACKAGE;?></h4>

<table class="bdr small" summary="List of languages and their change status">
    <tr class="thead">
        <th>#</th>
        <th colspan="3"><?php echo $this->lang->L_LANGUAGE;?></th>
        <th><?php echo $this->lang->L_EXPORT_LATEST_CHANGE_DATABASE;?></th>
        <th><?php echo $this->lang->L_EXPORT_LATEST_CHANGE_IN_DOWNLOAD_PACKAGE;?></th>
    </tr>
<?php
$languagesToUpdate = 0;
$exportNeeded = false;
foreach ($this->status as $key => $s)
{
    if ($this->languages[$key]['active'] == 0) {
        continue;
    }
    $tsDownloadPackage = $export->convertUnixDate($export->getLatestDownloadPackageTimestamp());
    $tsDatabase        = $this->historyModel->getLatestChange($key);
?>
    <tr class="<?php echo$this->cycle(array('row-even', 'row-odd'))->next();?>">
        <td class="right"><?php echo $i;?>.</td>
        <td>
            <?php echo $this->printFlag($key);?>
        </td>
        <td><?php echo $this->languages[$key]['locale'];?></td>
        <td><?php echo $this->languages[$key]['name'];?></td>
        <td class="right"><?php echo $tsDatabase;?></td>
        <td>
            <?php
                if ($tsDownloadPackage < $tsDatabase) {
                    $exportNeeded = true;
                    echo $this->getIcon('NotOk', 'Not up to date', 16);
                } else {
                    echo $this->getIcon('Ok', 'Up to date', 16);
                }
            ?>
        </td>
    </tr>
<?php
    $i++;
}
?>
</table>
<br />
<?php
if ($exportNeeded) {
?>
    <p class="error"><?php echo $this->lang->L_EXPORT_UPDATE_NEEDED;?></p>
<?php } else { ?>
<p class="ok"><?php echo $this->lang->L_EXPORT_DOWNLOAD_PACKAGE_UPTODATE;?></p>
<?php } ?>
<a href="<?php echo $this->baseUrl();?>/export/update.all" class="Formbutton">
    <?php echo $this->getIcon('save', '').''.$this->lang->L_EXPORT_BUILD_DOWNLOAD_PACKAGE;?>
</a><br/>
