<?php
$i = 1;
$export = $this->export;
?>
<h2>Export</h2>
<h4>File status of download package:</h4>

<table class="bdr small" summary="List of languages and their change status">
    <tr class="thead">
        <th>#</th>
        <th colspan="3">Language</th>
        <th>Latest change in database</th>
        <th>Latest change in download package?</th>
    </tr>
<?php
$languagesToUpdate = 0;
$exportNeeded = false;
foreach ($this->status as $key => $s)
{
    if ($this->languages[$key]['active'] == 0) {
        continue;
    }
    $tsDownloadPackage = $export->convertUnixDate($export->getLatestDownloadPackageTimestamp());
    $tsDatabase        = $this->historyModel->getLatestChange($key);
?>
    <tr class="<?php echo$this->cycle(array('row-even', 'row-odd'))->next();?>">
        <td class="right"><?php echo $i;?>.</td>
        <td>
            <?php echo $this->printFlag($key);?>
        </td>
        <td><?php echo $this->languages[$key]['locale'];?></td>
        <td><?php echo $this->languages[$key]['name'];?></td>
        <td class="right"><?php echo $tsDatabase;?></td>
        <td>
            <?php
                if ($tsDownloadPackage < $tsDatabase) {
                    $exportNeeded = true;
                    echo $this->getIcon('Attention', 'Not up to date', 16);
                } else {
                    echo $this->getIcon('Ok', 'Up to date', 16);
                }
            ?>
        </td>
    </tr>
<?php
    $i++;
}
?>
</table>
<br />
<?php
if ($exportNeeded) {
?>
    <p class="error">Download package needs to be updated.</p>
    <a href="<?php echo $this->baseUrl();?>/export/update.all" class="Formbutton">
        <?php echo $this->getIcon('save', '');?> Build download package
    </a><br/>
<?php } else { ?>
<p class="ok">Download package is up to date.</p>
<?php }