<h2>Export</h2>
<h4>Exporting all languages</h4>
<p>
<table class="bdr">
<?php
    $exportError = false;
    $cycle = $this->cycle(array('row-even', 'row-odd'));
    foreach ($this->languages as $lang) {
    ?>
    <tr class="<?php echo $cycle->next();?>">
        <td>Exporting language <b><?php echo $lang['meta']['name'];?> (<?php echo $lang['meta']['locale'];?>)</b> from database their language files</td>
        <td>
    <?php
        if ($lang['filesize'] !== false) {
            echo $this->getIcon('Ok', '', 16). ' Filesize: '.$this->byteOutput($lang['filesize']);
        } else {
            $exportError = true;
            echo $this->getIcon('Attention', '', 16) . ' ERROR! The file couldn\'t be saved!';
        }
    ?>
        </td>
        </tr>
    <?php
    }
    ?>
</table>
</p>
<h4>Committing changes to Subversion Repository</h4>
<p>
    <?php if ($this->svnExportResult['output'] > '') { ?><pre><span class="success">SVN output:</span> <?php echo $this->svnExportResult['output']; ?></pre><?php } ?>
    <?php if ($this->svnExportResult['error'] > '') { ?><pre><span class="error">SVN error:</span> <?php echo $this->svnExportResult['error']; ?></pre><?php } ?>
</p>
<br />
<a href="<?php echo $this->baseUrl();?>/export/index/" class="Formbutton"><?php echo $this->getIcon('ArrowLeft','');?> Back to overview </a>
