<h2>Export</h2>
<h4>Exporting language '<?php echo $this->language['name'];?> (<?php echo $this->language['locale'];?>)':</h4>
<table class="bdr more-pading">
    <tr class="thead">
        <th colspan="2">Filename</th>
        <th>Filesize</th>
    </tr>
<?php
foreach ($this->exportedFiles as $exportedFile) {
    $cycle = $this->cycle(array('row-even', 'row-odd'));
?>
   <tr class="<?php echo $cycle->next();?>">
        <td><?php echo $exportedFile['filename']; ?></td>
        <td><?php echo ($exportedFile['size'] !== false) ? $this->getIcon('Ok', '', 16) : $this->getIcon('Attention', '', 16); ?></td>
        <td><?php echo $this->byteOutput($exportedFile['size']); ?></td>
    </tr>
<?php } ?>
<?php if ($this->exportOk) { ?>
    <tr class="<?php echo $cycle->next();?>">
        <td colspan="3">
            <a href="<?php echo $this->baseUrl();?>/export/commit/" class="Formbutton"><?php echo $this->getIcon('Sync', '', 16);?> Commit to VCS </a>
        </td>
    </tr>
<?php } ?>
</table><br/>
<a href="<?php echo $this->baseUrl();?>/export/index/" class="Formbutton"><?php echo $this->getIcon('ArrowLeft','');?> Back to overview </a>
