<?php
$cycleHelper = $this->cycle(array('row-even', 'row-odd'));
$entry = $this->entry;
?>
<form action="<?php echo $this->baseUrl();?>/entries/edit" method="post" id="editForm">
    <table class="bdr more-padding" summary="List of edit boxes">
        <tr class="thead"><th colspan="2"><?php echo $this->lang->L_EDIT;?>:</th></tr>
        <tr class="<?php echo $cycleHelper->next();?>">
            <td class="top"><?php echo $this->lang->L_KEY;?>:</td>
            <td>
                <?php echo $this->key['key'];?>
            </td>
        </tr>

        <tr class="<?php echo $cycleHelper->next()?>">
            <td><?php echo $this->lang->L_FILE; ?>:</td>
            <td><?php
                if ($this->user->hasRight('addVar')) {
                    echo $this->printFileTemplateHtml($this->assignedFileTemplate['id']);
                } else {
                    if (!empty($this->assignedFileTemplate['name']) && !empty($this->assignedFileTemplate['filename'])) {
                        echo $this->assignedFileTemplate['name'] . ' (' . $this->assignedFileTemplate['filename'] . ')';
                    }
                } ?>
            </td>
        </tr>
        <?php
        foreach ($this->languagesEdit as $languageId) {
            $rowclass = $cycleHelper->next();
            if (!isset($this->skipKeysOffsets[$languageId])) {
                $this->skipKeysOffsets[$languageId] = 0;
            } ?>
            <tr class="<?php echo $rowclass;?>">
                <td><?php echo $this->printFlag($languageId);?></td>
                <td><?php
                    if ($this->langStatus[$languageId]['notTranslated'] > 0) { ?>
                        <span class="floatRight">
                            <?php
                            if ($this->skipKeysOffsets[$languageId] >= 0) { ?>
                                <a href="<?php echo $this->baseUrl() . '/entries/get-previous-untranslated-key/languageId/' . $languageId;?>" class="Formbutton">
                                    <?php echo $this->getIcon('Back', $this->lang->L_GET_PREVIOUS_UNTRANSLATED_KEY, 16);?>
                                </a><?php
                            } else { ?>
                                <button class="Formbutton" disabled="disabled">
                                    <?php echo $this->getIcon('BackDisabled', $this->lang->L_GET_PREVIOUS_UNTRANSLATED_KEY, 16);?>
                                </button><?php
                            }

                            if ($this->skipKeysOffsets[$languageId] +1 < $this->langStatus[$languageId]['notTranslated']) { ?>
                                <a href="<?php echo $this->baseUrl() . '/entries/get-next-untranslated-key/languageId/' . $languageId
                                    . '/entryId/' . $this->key['id'];?>" class="Formbutton">
                                    <?php echo $this->getIcon('Forward', $this->lang->L_GET_NEXT_UNTRANSLATED_KEY, 16);?>
                                </a><?php
                            } else { ?>
                                <button class="Formbutton" disabled="disabled">
                                    <?php echo $this->getIcon('ForwardDisabled', $this->lang->L_GET_NEXT_UNTRANSLATED_KEY, 16);?>
                                </button><?php
                            } ?>
                        </span><?php
                    } ?>

                    <span class="small floatLeft">
                        <b><?php echo $this->languages[$languageId]['name'];?>:</b>
                        <br />
                        <?php echo $this->lang->L_PROGRESS . ' ' . $this->langStatus[$languageId]['done'];?>%
                        <?php
                            if ($this->langStatus[$languageId]['notTranslated'] > 0) {
                                echo $this->lang->L_UNTRANSLATED. ': ' . $this->langStatus[$languageId]['notTranslated'];
                            }
                          ?>
                    </span>
                </td>
            </tr>
            <tr class="<?php echo $rowclass;?>">
                <td>&nbsp;</td>
                <td>
                    <textarea id="edit-<?php echo $this->languages[$languageId]['id'];?>" name="edit-<?php echo $this->languages[$languageId]['id'];?>"
                              class="textarea-edit" rows="2" cols="55"><?php
                                if (isset($entry[$languageId])) {
                                    echo trim(htmlentities($entry[$languageId], ENT_COMPAT, 'utf-8'));
                                };?></textarea>
                    <br /><br />
                </td>
            </tr><?php
        } ?>

        <tr class="<?php echo $cycleHelper->next();?>">
            <td>&nbsp;</td>
            <td>
                <input type="hidden" name="id" value="<?php echo $this->key['id'];?>" />
                <?php
                if (count($this->languagesEdit) > 0) { ?>
                    <a href="#" class="Formbutton" id="save-button" onclick="$('#editForm').submit()">
                        <?php echo $this->getIcon('save', $this->lang->L_SAVE) . ' ' . $this->lang->L_SAVE;?>
                    </a><?php
                } ?>
            </td>
        </tr>
    </table>
</form>

<?php
if (isset($this->entrySaved)) {
    $this->showNotification(
        $this->entrySaved == 1 || $this->entrySaved === true,
        $this->lang->L_SAVED_SUCCESSFULLY . '.',
        $this->lang->L_SAVED_UNSUCCESSFULLY . '!'
    );
}
if (isset($this->keyExistsError)) {
    $this->showNotification(false, '', $this->keyExistsError);
}

