<?php
$cycleHelper = $this->cycle(array('row-even', 'row-odd'));
$entry = $this->entry;
?>
<form action="<?php echo $this->baseUrl();?>/entries/edit/ref/<?php echo $this->referrer;?>" method="post" id="editForm">
    <table class="bdr more-padding" summary="List of edit boxes">
        <tr class="thead"><th colspan="2"><?php echo $this->lang->L_EDIT;?>:</th></tr>
        <tr class="<?php echo $cycleHelper->next();?>">
            <td class="top"><?php echo $this->escape($this->lang->L_KEY);?>:</td>
            <td>
                <?php echo $this->escape($this->key['key']);?>
            </td>
        </tr>

        <tr class="<?php echo $cycleHelper->next()?>">
            <td><?php echo $this->escape($this->lang->L_FILE); ?>:</td>
            <td><?php
                if ($this->user->hasRight('addVar')) {
                    echo $this->printFileTemplateHtml($this->assignedFileTemplate['id']);
                } else {
                    if (!empty($this->assignedFileTemplate['name']) && !empty($this->assignedFileTemplate['filename'])) {
                        echo $this->assignedFileTemplate['name'] . ' (' . $this->assignedFileTemplate['filename'] . ')';
                    }
                } ?>
            </td>
        </tr>
        <?php
        foreach ($this->languagesEdit as $languageId) {
            $rowclass = $cycleHelper->next();
            if (!isset($this->skipKeysOffsets[$languageId])) {
                $this->skipKeysOffsets[$languageId] = 0;
            } ?>
            <tr class="<?php echo $rowclass;?>">
                <td><?php echo $this->printFlag($languageId);?></td>
                <td><?php
                    if ($this->langStatus[$languageId]['notTranslated'] > 0) { ?>
                        <span class="floatRight">
                            <?php
                            if ($this->skipKeysOffsets[$languageId] >= 0) { ?>
                                <a href="<?php echo $this->baseUrl() . '/entries/get-previous-untranslated-key/languageId/' . $languageId;?>" class="Formbutton ui-corner-all">
                                    <?php echo $this->getIcon('Back', $this->lang->L_GET_PREVIOUS_UNTRANSLATED_KEY, 16);?>
                                </a><?php
                            } else { ?>
                                <a href="#" class="Formbutton ui-corner-all disabled" disabled="disabled">
                                    <?php echo $this->getIcon('BackDisabled', '', 16);?>
                                </a><?php
                            }

                            if ($this->skipKeysOffsets[$languageId] +1 < $this->langStatus[$languageId]['notTranslated']) { ?>
                                <a href="<?php echo $this->baseUrl() . '/entries/get-next-untranslated-key/languageId/' . $languageId
                                    . '/entryId/' . $this->key['id'];?>" class="Formbutton ui-corner-all">
                                    <?php echo $this->getIcon('Forward', $this->lang->L_GET_NEXT_UNTRANSLATED_KEY, 16);?>
                                </a><?php
                            } else { ?>
                                <a href="#" class="Formbutton ui-corner-all disabled" disabled="disabled">
                                    <?php echo $this->getIcon('ForwardDisabled', '', 16);?>
                                </a><?php
                            } ?>
                        </span><?php
                    } ?>

                    <span class="small floatLeft">
                        <b><?php echo $this->languages[$languageId]['name'];?>:</b>
                            <?php
                            if (array_key_exists($languageId, $this->needsUpdate) && $this->needsUpdate[$languageId]) { ?>
                                <img src="<?php echo $this->getIconSrc('Attention', '16'); ?>"
                                    title="<?php echo $this->lang->L_NEEDS_UPDATE_INFO ?>"
                                    for="<?php echo $this->key['id'] . '-' . $languageId;?>"
                                    id="removeNeedsUpdate-<?php echo $this->key['id'] . '-' . $languageId;?>"
                                    class="removeNeedsUpdateTrigger" />
                            <?php } ?>
                        <br />
                        <?php echo $this->lang->L_PROGRESS . ' ' . $this->langStatus[$languageId]['done'];?>%
                        <?php
                            if ($this->langStatus[$languageId]['notTranslated'] > 0) {
                                echo $this->lang->L_UNTRANSLATED. ': ';
                                if (!isset($entry[$languageId]) || $entry[$languageId] == '') {
                                    echo ($this->skipKeysOffsets[$languageId] + 1) .'/';
                                }
                                echo $this->langStatus[$languageId]['notTranslated'];
                            }
                          ?>
                    </span>
                </td>
            </tr>
            <tr class="<?php echo $rowclass;?>">
                <td>&nbsp;</td>
                <td>
                    <textarea id="edit-<?php echo $this->languages[$languageId]['id'];?>" name="edit-<?php echo $this->languages[$languageId]['id'];?>"
                              class="textarea-edit" rows="2" cols="55"><?php
                                if (isset($entry[$languageId])) {
                                    echo trim(htmlentities($entry[$languageId], ENT_COMPAT, 'utf-8'));
                                };?></textarea>
                    <br /><br />
                    <input type="checkbox" id="optional-<?php echo $this->languages[$languageId]['id'];?>"
                           name="optional-<?php echo $this->languages[$languageId]['id'];?>"
                           value="<?php echo $this->languages[$languageId]['id'];?>"
                        <?php echo ((isset($this->optionalTranslations[$this->key['id']][$languageId])) ? ' checked' : null) ?>>
                    <label for="optional-<?php echo $this->key['id'];?>-<?php echo $this->languages[$languageId]['id'];?>"><?php echo $this->lang->L_OPTIONAL_TRANSLATION; ?></label>
                    <br />
                    <?php if ($languageId == $this->fallbackLanguageId) { ?>
                        <input type="checkbox" name="only-small-change" id="only-small-change" />
                        <label for="only-small-change"><?php echo $this->lang->L_ONLY_SMALL_CHANGE_INFO; ?></label>
                        <br />
                    <?php } ?>
                </td>
            </tr><?php
        } ?>

        <tr class="<?php echo $cycleHelper->next();?>">
            <td>&nbsp;</td>
            <td>
                <input type="hidden" name="id" value="<?php echo $this->key['id'];?>" />
                <?php
                if (count($this->languagesEdit) > 0) { ?>
                    <a href="#" class="Formbutton ui-corner-all" id="save-button" onclick="$('#editForm').submit()">
                        <?php echo $this->getIcon('save', $this->lang->L_SAVE) . ' ' . $this->lang->L_SAVE;?>
                    </a>
                    <button type="submit" class="Formbutton ui-corner-all" id="saveGetUntranslated" name="saveGetUntranslated">
                        <?php echo $this->getIcon('save', $this->lang->L_SAVE) . ' ' . $this->lang->L_GET_NEXT_UNTRANSLATED_KEY;?>
                    </button><?php
                }
                ?>
            </td>
        </tr>
    </table>
</form>

<?php
if (isset($this->entrySaved)) {
    $this->showNotification(
        $this->entrySaved == 1 || $this->entrySaved === true,
        $this->lang->L_SAVED_SUCCESSFULLY . '.',
        $this->lang->L_SAVED_UNSUCCESSFULLY . '!'
    );
}
if (isset($this->keyExistsError)) {
    $this->showNotification(false, '', $this->keyExistsError);
}

if (count($this->languagesEdit) > 0) {
    if ($this->setFocusToLanguage === false) {
        $this->setFocusToLanguage = $this->languagesEdit[0]['id'];
    }
    $this->jQuery()->onLoadCaptureStart();?>
    $('#edit-<?php echo $this->setFocusToLanguage;?>').focus();<?php
    $this->jQuery()->onLoadCaptureEnd();
}

$this->jQuery()->onLoadCaptureStart();
echo $this->partial('helper/js-remove-needs-update.phtml');
$this->jQuery()->onLoadCaptureEnd();
?>
