<?php
$cycleHelper = $this->cycle(array('row-even', 'row-odd'));
$translateConfig = $this->config->getParam('google');
$apiKey = $translateConfig['apikey'];
$entry = $this->entry;
if (!empty($this->referenceLanguages)) {
?>
<table class="bdr small" style="margin-bottom: 20px;" summary="Output of reference languages">
    <tr class="thead"><th colspan="5"><?php echo $this->lang->L_REFERENCE_LANGUAGES;?>:</th></tr>
    <?php
    $rowclass = $cycleHelper->next();
    foreach ($this->referenceLanguages as $lang) {
        $rowclass = $cycleHelper->next();
        ?>
        <tr class="<?php echo $rowclass;?>">
            <td>
                <?php echo $this->printFlag($lang, 20);?>
            </td>
            <td colspan="4">
                <span class="small"><?php echo $this->languages[$lang]['name'];?>:</span>
                <?php
                    if (!isset($entry[$lang]) || trim($entry[$lang]) == '') { ?>
                        <i><?php echo $this->lang->L_UNTRANSLATED;?></i></td></tr><?php
                        continue;
                    }
                ?>
                <br />
            </td>
        </tr>
        <tr class="<?php echo $rowclass;?>">
            <td>&nbsp;</td>
            <td colspan="4">
                <textarea readonly="readonly" id="textarea-<?php echo $this->languages[$lang]['id'];?>" class="textarea-edit" rows="2" cols="55"><?php echo trim(htmlentities($entry[$lang], ENT_COMPAT, 'utf-8'));?></textarea>
            </td>
        </tr>
        <tr class="<?php echo $rowclass;?>">
            <td>&nbsp;</td>
            <td colspan="2">
                <?php echo $this->lang->L_COPY_TO;?>:&nbsp;<?php
                foreach ($this->languagesEdit as $langEdit) { ?>
                    <a href="#" class="copy">
                        <?php echo $this->printFlag($langEdit, 16, 'copy-' . $this->languages[$lang]['id'] . '-' . $this->languages[$langEdit]['id']);?>
                    </a><?php
                } ?>
            </td>
            <?php
            if ($apiKey > '') { ?>
                <td colspan="2"><?php echo $this->lang->L_TRANSLATE_TO;?>: &nbsp;<?php
                    foreach ($this->languagesEdit as $langEdit) {
                        if (in_array($this->languages[$lang]['locale'], $this->translatable)) {
                            if ($lang == $langEdit) {
                                continue;
                            } ?>
                            <a href="#" class="translate">
                                <?php echo $this->printFlag($langEdit, 16, 'translate-' . $this->languages[$lang]['id'] . '-' . $this->languages[$langEdit]['id']);?>
                            </a><?php
                        }
                    }
            } else { ?>
                <td colspan="3">&nbsp;<?php
            } ?>
            </td>
        </tr>
        <tr class="<?php echo $cycleHelper->current();?>" style="line-height:4px;"><td colspan="5"></td></tr><?php
    }
    ?>
</table>
<script type="text/javascript">
<?php
}
$this->jQuery()->onLoadCaptureStart();?>
$('.copy').click(function (e) {
    copyLang(e);
});
$('.translate').click(function (e) {
    translate(e);
});

function copyLang(event) {
    var lang = event.target.id;
    lang = lang.substr(5);
    lang = lang.split('-');
    $('#edit-'+lang[1]).val($('#textarea-'+lang[0]).val());
    $('#edit-'+lang[1]).focus();
}

function translate(event) {
    var lang = event.target.id;
    lang = lang.substr(10);
    lang = lang.split('-');
    var sourceLang = lang[0];
    var targetLang = lang[1];
    setPageInactive();
    $.ajax({
        url: '<?php echo $this->baseUrl();?>/ajax/translate/key/<?php echo $this->key['id'];?>/source/'+sourceLang+'/target/'+targetLang,
        dataType : 'html',
        success: function(response) {
            $('#edit-'+lang[1]).val(response.trim());
            $('#edit-'+lang[1]).focus();
            setPageActive();
        },
        error: function() {
            $('#edit-'+lang[1]).val('Error: ' + response);
            $('#edit-'+lang[1]).focus();
            setPageActive();
        }
    });
}
<?php $this->jQuery()->onLoadCaptureEnd();?>
</script>
