<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
    <meta content="text/html; charset=utf-8"/>
    <title>oTranCe - Online Translation Center</title>
    <link type="text/css" rel="stylesheet" href="css/style.css"/>
    <link type="text/css" rel="stylesheet" href="css/login.css"/>
    <style type="text/css">
        #login .bdr td {
            border:none;
        }
    </style>
    <script type="text/javascript" src="js/jquery.min.js"></script>
    <script type="text/javascript" src="js/jquery.tmpl.min.js"></script>
    <script type="text/javascript">
        var icons = {
            "0":"images/16x16/Apply.png",
            "1":"images/16x16/Exception.png",
            "2":"images/16x16/NotOk.png"
        };
        var currentStep = 0;

        var steps = {
            "1":function() {
                function runCheck() {
                    var $form = $('#requireCheck');
                    $.ajax({
                        url:$form.prop('action'),
                        type:$form.prop('method'),
                        success:function(result) {
                            var v;
                            var passed = true;
                            for (var k in result) {
                                v = result[k];
                                passed = passed && v.passed;
                                $('#si' + k).prop('src', icons[v.status]);
                                $('#r' + k).html(v.value);
                            }
                            if (passed) {
                                $('#steps .step1 .status').removeClass('active error done pending').addClass('done');
                                $('#nextStepButton').css('display', 'inline-block').focus();
                            } else {
                                $('#steps .step1 .status').removeClass('active error done pending').addClass('error');
                                $('#nextStepButton').hide();
                            }
                        }
                    });
                }

                var toggleVar = 1;
                var rowClasses = ['row-even', 'row-odd'];
                $.ajax({
                    "url":"index.php?controller=requirements&action=fetchInfo",
                    "type":"POST",
                    "success":function(result) {
                        $('#requireRow').tmpl(result, {
                            "getRowClass":function() {
                                toggleVar++;
                                return rowClasses[toggleVar % rowClasses.length];
                            }
                        }).appendTo('#requireCheck table');
                        runCheck();
                    }
                });
            },
            "2":function() {
                function downloadExtract()
                {
                    $.ajax({
                        "url":"index.php?controller=download&action=download",
                        "type":"POST",
                        "success":function(result) {
                            $('#downStatus').prop('src', icons[result.download ? 0 : 1]);
                            $('#extractStatus').prop('src', icons[result.extract ? 0 : 1]);
                            if (result.download && result.extract) {
                                $('#steps .step2 .status').removeClass('active error done pending').addClass('done');
                                $('#nextStepButton').insertBefore('#step2 h2').css('display', 'inline-block').focus();
                            } else {
                                $('#steps .step2 .status').removeClass('active error done pending').addClass('error');
                                $('#nextStepButton').hide();
                            }
                        }
                    });
                }
                $.ajax({
                    "url":"index.php?controller=download&action=package",
                    "type":"POST",
                    "success":function(result) {
                        $('#package').html(result.download);
                        $('#extractDir').html(result.extract);
                        downloadExtract();
                    }
                });
            },
            "3":function() {
                $('#dbHost').focus();
                $('#mysqlSettings').bind('submit', function() {
                    $.ajax({
                        "url":$(this).prop('action'),
                        "type":$(this).prop('method'),
                        "data":$(this).serializeArray(),
                        "success":function(result) {
                            if (result.connect) {
                                $('#steps .step3 .status').removeClass('active error done pending').addClass('done');
                                $('#mysqlNotify').removeClass('ok error').addClass('ok').html('MySQL connection successfully established.').fadeIn(500).delay(2500).fadeOut(500);
                                $('#nextStepButton').insertBefore('#step3 h2').css('display', 'inline-block').focus();
                            } else {
                                $('#steps .step3 .status').removeClass('active error done pending').addClass('error');
                                $('#mysqlNotify').removeClass('ok error').addClass('error').html('MySQL connection error!<br/>' + result.number + ': ' + result.message).fadeIn(500).delay(5000).fadeOut(500);
                                $('#nextStepButton').hide();
                            }
                        }
                    });
                });
            },
            "4":function() {
                $.ajax({
                    "url":"index.php?controller=mysql&action=createTables",
                    "type":"POST",
                    "success":function(result) {
                        if (result.success) {
                            $('#steps .step4 .status').removeClass('active error done pending').addClass('done');
                            $('#mysqlNotify').removeClass('ok error').addClass('ok').html('MySQL database tables sucessfully created.').fadeIn(500).delay(2500).fadeOut(500);
                            $('#nextStepButton').insertBefore('#step4 h2').css('display', 'inline-block').focus();
                        } else {
                            $('#steps .step4 .status').removeClass('active error done pending').addClass('error');
                            var message = 'Error while creating tables.<br/>' + result.number + ': ' + result.message;
                            message += '<br/>Line ' + result.line + ': ' + result.query;
                            $('#mysqlNotify').removeClass('ok error').addClass('error').html(message).fadeIn(500).delay(5000).fadeOut(500);
                            $('#nextStepButton').hide();
                        }
                    }
                });
            },
            "5":function() {
                $('#projectName').focus();
                $('#projectSettings').bind('submit', function() {
                    if ($('#adminPass').val() == $('#adminPass2').val()) {
                        $.ajax({
                            "url":$(this).prop('action'),
                            "type":$(this).prop('method'),
                            "data":$(this).serializeArray(),
                            "success":function(result) {
                                if (result.createAdmin && result.saveConfig) {
                                    $('#steps .step5 .status').removeClass('active error done pending').addClass('done');
                                    $('#setupFinished').show();
                                    $('#setupFinished a.Formbutton').focus();
                                    $('#step' + currentStep).hide();
                                }
                            }
                        });
                    } else {
                        var message = "Admin password must be equal with it's confirmation.";
                        $('#mysqlNotify').removeClass('ok error').addClass('error').html(message).fadeIn(500).delay(5000).fadeOut(500);
                    }
                    return false;
                });
            }
        };

        function nextStep()
        {
            $('#step' + currentStep).hide();
            currentStep++;
            $('#step' + currentStep).show();
            $('#steps .step' + currentStep + ' .status').removeClass('pending').addClass('active');
            $('#nextStepButton').hide();
            steps[currentStep]();
        }

        $(document).ready(function(){
            $('#nextStepButton').bind('click', function() {
                nextStep();
                return false;
            });
            nextStep();
        });
    </script>
    <script type="text/x-jquery-tmpl" id="requireRow">
        <tr class="${$item.getRowClass()}">
            <td class="vmiddle">${title} {{if required}}*{{/if}}</td>
            <td class="vmiddle">${expected}</td>
            <td class="vmiddle">=&gt;</td>
            <td class="vmiddle" id="r${reqKey}" style="width:110px;"></td>
            <td class="vmiddle"><img src="images/16x16/Info.png" alt="" id="si${reqKey}"/></td>
        </tr>
    </script>
</head>
<body>
    <div id="header"></div>
    <div id="container">
        <div id="login">
            <h1>oTranCe - Setup</h1>
            <ul id="steps">
                <li class="step step1"><span class="status active"></span> Requirements check</li>
                <li class="step step2"><span class="status pending"></span> Download &amp; extract</li>
                <li class="step step3"><span class="status pending"></span> MySQL connection</li>
                <li class="step step4"><span class="status pending"></span> Database tables</li>
                <li class="step step5"><span class="status pending"></span> Project settings</li>
                <li class="clear"></li>
            </ul>
            <div class="clear"></div>
            <div id="step1">
                <a href="#" id="nextStepButton" class="Formbutton">Next step <img src="images/16x16/Forward.png" alt=""/></a>
                <form id="requireCheck" action="index.php?controller=requirements&amp;action=check" method="post" onsubmit="return false;">
                    <h2>Requirements check</h2>
                    <table class="bdr small">
                        <tr class="thead">
                            <th>Requirement</th>
                            <th>Expected</th>
                            <th></th>
                            <th colspan="2">Status</th>
                        </tr>
                    </table>
                    * These requirements must be met.
                </form>
            </div>
            <div id="step2">
                <h2>Download &amp; extract</h2>
                <table class="bdr small">
                    <tr class="thead">
                        <th>Action</th>
                        <th>Status</th>
                    </tr>
                    <tr>
                        <td class="vmiddle">Downloading <span id="package"></span></td>
                        <td class="vmiddle"><img src="images/16x16/Info.png" alt="" id="downStatus"/></td>
                    </tr>
                    <tr>
                        <td class="vmiddle">Extracting to <span id="extractDir"></span></td>
                        <td class="vmiddle"><img src="images/16x16/Info.png" alt="" id="extractStatus"/></td>
                    </tr>
                </table>
            </div>
            <div id="step3">
                <h2>MySQL settings</h2>
                <form id="mysqlSettings" action="index.php?controller=mysql&action=check" method="post" onsubmit="return false;">
                    <table class="bdr small">
                        <tr>
                            <th><label for="dbHost">Server host:</label></th>
                            <td><input type="text" class="text" name="mysql[host]" id="dbHost" value="localhost"/></td>
                        </tr>
                        <tr>
                            <th><label for="dbPort">Server port:</label></th>
                            <td><input type="text" class="text" name="mysql[port]" id="dbPort" maxlength="5" size="5" value="3306"/></td>
                        </tr>
                        <tr>
                            <th><label for="dbSocket">Server socket:</label></th>
                            <td><input type="text" class="text" name="mysql[socket]" id="dbSocket"/></td>
                        </tr>
                        <tr>
                            <th><label for="dbUser">Server user:</label></th>
                            <td><input type="text" class="text" name="mysql[user]" id="dbUser"/></td>
                        </tr>
                        <tr>
                            <th><label for="dbPass">Server password:</label></th>
                            <td><input type="password" class="text" name="mysql[pass]" id="dbPass"/></td>
                        </tr>
                        <tr>
                            <th><label for="dbName">Server database:</label></th>
                            <td><input type="text" class="text" name="mysql[db]" id="dbName" value="otrance"/></td>
                        </tr>
                        <tr>
                            <th></th>
                            <td><button type="submit" class="Formbutton"><img src="images/16x16/save.png" alt=""/> Save</button></td>
                        </tr>
                    </table>
                </form>
            </div>
            <div id="step4">
                <h2>Creating database tables</h2>
            </div>
            <div id="step5">
                <h2>Project settings</h2>
                <form id="projectSettings" action="index.php?controller=project&action=save" method="post" onsubmit="return false;">
                    <table class="bdr small">
                        <tr>
                            <th><label for="projectName">Project name:</label></th>
                            <td><input type="text" class="text" name="project[name]" id="projectName"/></td>
                        </tr>
                        <tr>
                            <th><label for="projectUrl">Project URL:</label></th>
                            <td><input type="text" class="text" name="project[url]" id="projectUrl"/></td>
                        </tr>
                        <tr>
                            <th><label for="adminLogin">Admin login:</label></th>
                            <td><input type="text" class="text" name="admin[login]" id="adminLogin"/></td>
                        </tr>
                        <tr>
                            <th><label for="adminPass">Admin password:</label></th>
                            <td><input type="password" class="text" name="admin[pass]" id="adminPass"/></td>
                        </tr>
                        <tr>
                            <th><label for="adminPass2">... confirm:</label></th>
                            <td><input type="password" class="text" name="admin[pass2]" id="adminPass2"/></td>
                        </tr>
                        <tr>
                            <th></th>
                            <td><button type="submit" class="Formbutton"><img src="images/16x16/save.png" alt=""/> Save</button></td>
                        </tr>
                    </table>
                </form>
            </div>
            <div id="setupFinished">
                <h2>Setup finished</h2>
                <h3>Setup successfully completed. Now you can use your oTranCe installation.</h3>
                <a href="../" class="Formbutton">Goto your oTranCe installation <img src="images/16x16/Forward.png" alt=""/></a>
            </div>
            <div id="mysqlNotify" class="notification-bar"></div>
        </div>
    </div>
    <div class="spacer"></div>
    <div class="spacer"></div>
    <div id="footer">
        <p>
            oTranCe is a free online translation plattform &middot;
            <a href="http://oTranCe.de/en/">oTranCe Homepage</a> &middot;
            <a href="http://oTranCe.de/en/team/">The developer team</a> &middot;
            <a href="http://oTranCe.de/en/project/donate/">Donate</a>&nbsp;
        </p>
    </div>
</body>
</html>
