<div id="headline">
    <h2><?php echo $this->lang->L_ADMIN . ' - ' . $this->lang->L_EDIT_LANGUAGE;?></h2>
</div>
<?php
echo $this->partial('admin/head-navi.phtml', array('lang' => $this->lang));
if ($this->languageId == 0) {
    $subTitle = $this->lang->L_ADD_NEW_LANGUAGE;
} else {
    $subTitle = $this->lang->L_EDIT_LANGUAGE . " \"{$this->langName} ({$this->langLocale})\"";
}
?>
<div>
<?php if ($this->user->hasRight('addLanguage')) {?>
    <button type="button" class="Formbutton ui-corner-all" onclick="window.location.href='<?php echo $this->baseUrl();?>/admin_languages/edit/id/0'">
        <?php echo $this->getIcon('plus', '') . ' ' . $this->lang->L_ADD_NEW_LANGUAGE;?>
    </button>
    <br /><br />
<?php } ?>
</div>
<h4><?php echo $subTitle; ?>:</h4>
<form action="<?php echo $this->baseUrl(); ?>/admin_languages/edit/id/<?php echo $this->languageId; ?>/" method="post" enctype="multipart/form-data" id="myForm">
    <table class="bdr more-padding" summary="List of language settings">
        <tr class="thead">
           <th colspan="2"><?php echo $this->lang->L_LANGUAGE_SETTINGS;?></th>
        </tr>
        <tr class="row-odd">
            <td class="vmiddle"><?php echo $this->lang->L_IS_ACTIVE;?>:</td>
            <td class="vmiddle">
                <input type="radio" name="langActive" id="langActiveYes" value="1"<?php echo (!isset($this->langActive) || $this->langActive) ? ' checked="checked"' : ''; ?>/>
                <label for="langActiveYes"> <?php echo $this->lang->L_YES;?></label>
                &nbsp;&nbsp;
                <input type="radio" name="langActive" id="langActiveNo" value="0"<?php echo (isset($this->langActive) && !$this->langActive) ? ' checked="checked"' : ''; ?>
                    <?php
                    if ($this->fallbackLanguageId == $this->languageId) {
                        echo ' disabled="disabled"';
                    }
                    ?>
                />
                <label for="langActiveNo"> <?php echo $this->lang->L_NO;?></label>
            </td>
        </tr>
        <tr class="row-even">
            <td class="vmiddle"><label for="langLocale"><?php echo $this->lang->L_LOCALE;?>:</label></td>
            <td class="vmiddle"><input type="text" class="text" name="langLocale" id="langLocale" value="<?php echo $this->escape($this->langLocale); ?>" maxlength="5"/><?php
                if (!empty($this->inputErrors['langLocale'])) { ?>
                    <span class="error"><br/><?php echo implode("<br/>", $this->inputErrors['langLocale']); ?></span>
                <?php }?>
            </td>
        </tr>
        <tr class="row-odd">
            <td class="vmiddle"><label for="langName"><?php echo $this->lang->L_NAME_OF_LANGUAGE;?>:</label></td>
            <td><input type="text" class="text" name="langName" id="langName" value="<?php echo $this->escape($this->langName); ?>" maxlength="50" /><?php
                if (!empty($this->inputErrors['langName'])) { ?>
                    <span class="error"><br/><?php echo implode("<br/>", $this->inputErrors['langName']); ?></span>
                <?php } ?>
            </td>
        </tr>
        <tr class="row-even">
            <td>
                    <label for="langFlag"><?php echo $this->lang->L_FLAG;?>:</label><br /><br />
            </td>
            <td>
                <?php if ($this->flagExtension > '') {
                    echo $this->printFlag($this->languageId);
                } else { ?>
                    <input type="file" class="text" name="langFlag" id="langFlag" /><?php
                }

                if ($this->flagExtension > '') { ?>
                    <button type="button" class="Formbutton ui-corner-all" onclick="window.location.href = '<?php echo $this->baseUrl(); ?>/admin_languages/delete.flag/id/<?php echo $this->languageId; ?>/';"><?php echo $this->getIcon('delete', '');?> <?php echo $this->lang->L_DELETE_FLAG;?></button><?php
                    if (!empty($this->inputErrors['langFlag'])) {?>
                        <span class="error"><br/><?php echo implode("<br/>", $this->inputErrors['langFlag']); ?></span><?php
                    }
                } ?>
            </td>
        </tr>
        <tr class="row-odd">
            <td>
                <input type="hidden" name="flagExt" value="<?php echo $this->flagExtension; ?>"/>
                <input type="hidden" name="id" value="<?php echo $this->languageId; ?>"/>
            </td>
            <td class="vmiddle">
                <button type="submit" class="Formbutton ui-corner-all"><?php echo $this->getIcon('save', '');?> <?php echo $this->lang->L_SAVE;?></button>
            </td>
        </tr>
    </table>
    <?php
    if ($this->languageId > 0 && $this->user->hasRight('editUsers')) {
        echo $this->partial(
        'admin/languages/language-edit-rights.phtml',
            array(
                'user'              => $this->user,
                'users'             => $this->users,
                'hits'              => $this->userHits,
                'filterUser'        => $this->filterUser,
                'translators'       => $this->translators,
                'languageId'        => $this->languageId,
                'lang'              => $this->lang,
                'offset'            => $this->offset,
                'recordsPerPage'    => $this->recordsPerPage,
                'selRecordsPerPage' => $this->selRecordsPerPage
            )
        );
    }
    ?>
</form>
<?php
if (in_array($this->flag, array('deleted', 'notDeleted'))) {
    $result = $this->flag == 'deleted';
    $this->showNotification(
        $result,
        $this->lang->L_FLAG_DELETED_SUCCESSFULLY . '.',
        $this->lang->L_ERROR_DELETING_FLAG . '!'
    );
}

if (isset($this->creationResult)) {
    $this->showNotification(
        $this->creationResult,
        $this->lang->L_SAVED_SUCCESSFULLY . '.',
        $this->lang->L_SAVED_UNSUCCESSFULLY . '!'
    );
}

