<?php
$inputFieldMap = array(
    'langName' => 'Language name',
    'langLocale' => 'Language locale',
    'langFlag' => 'Language flag',
);
?>
<h2>Admin - Languages</h2>
<?php echo $this->partial('admin/head-navi.phtml'); ?>
<?php if ($this->langId == 0) {
    $subTitle = "Create new language";
} else {
    $subTitle = "Edit language \"{$this->langName} ({$this->langLocale})\"";
} ?>
<h4><?php echo $subTitle; ?></h4>
<form action="<?php echo $this->baseUrl(); ?>/admin_languages/edit/id/<?php echo $this->langId; ?>/" method="post" enctype="multipart/form-data">
    <table class="bdr more-padding">
        <tr class="thead">
           <th colspan="2">Language settings</th>
        </tr>
        <tr class="row-odd">
            <td>Language is active:</td>
            <td>
                <input type="radio" name="langActive" id="langActiveYes" value="1"<?php echo (!isset($this->langActive) || $this->langActive) ? ' checked="checked"' : ''; ?>/>
                <label for="langActiveYes"> Yes</label>
                &nbsp;&nbsp;
                <input type="radio" name="langActive" id="langActiveNo" value="0"<?php echo (isset($this->langActive) && !$this->langActive) ? ' checked="checked"' : ''; ?>/>
                <label for="langActiveNo"> No</label>
            </td>
        </tr>
        <tr class="row-even">
            <td><label for="langLocale">Language locale (e.g. en, de):</label></td>
            <td><input type="text" class="text" name="langLocale" id="langLocale" value="<?php echo $this->escape($this->langLocale); ?>" maxlength="5"/><?php
    if (array_key_exists('langLocale', $this->inputErrors)) {
?><span class="error"><br/><?php echo implode("<br/>", $this->inputErrors['langLocale']); ?></span><?php
            }
?></td>
        </tr>
        <tr class="row-odd">
            <td><label for="langName">Language name (e.g. English, Deutsch):</label></td>
            <td><input type="text" class="text" name="langName" id="langName" value="<?php echo $this->escape($this->langName); ?>" maxlength="50" /><?php
    if (array_key_exists('langName', $this->inputErrors)) {
?><span class="error"><br/><?php echo implode("<br/>", $this->inputErrors['langName']); ?></span><?php
            }
?></td>
        </tr>
        <tr class="row-even">
            <td>
                <label for="langFlag">Language flag:</label><br /><br />
                <?php echo $this->printFlag($this->langId);?>

            </td>
            <td>
                <input type="file" class="text" name="langFlag" id="langFlag" /><br/>
                <?php if ($this->flagExtension > '') { ?>
                    <button type="button" class="Formbutton" onclick="window.location.href = '<?php echo $this->baseUrl(); ?>/admin_languages/delete.flag/id/<?php echo $this->langId; ?>/';"><?php echo $this->getIcon('delete', '');?> Delete flag</button>
                    <?php if (array_key_exists('langFlag', $this->inputErrors)) {?>
                        <span class="error"><br/><?php echo implode("<br/>", $this->inputErrors['langFlag']); ?></span>
                    <?php }
                    }?>
            </td>
        </tr>
        <tr class="row-odd">
            <td><input type="hidden" name="flagExt" value="<?php echo $this->flagExtension; ?>"/></td>
            <td>
                <button type="submit" class="Formbutton"><?php echo $this->getIcon('save', '');?> Save</button>
            </td>
        </tr>
    </table>
</form>
<?php
if (!empty($this->inputErrors)) {
    $fieldErrors = '<table>';
    foreach ($this->inputErrors as $inputName => $inputError) {
        if (array_key_exists($inputName, $inputFieldMap)) {
            $inputName = $inputFieldMap[$inputName];
        }
        $fieldErrors .= "<tr><td class=\"error\">$inputName:</td><td class=\"error\">";
        $fieldErrors .= implode('<br/>', $inputError);
        $fieldErrors .= "</td></tr>";
    }
    $fieldErrors .= '</table>';
    $this->popUpMessage()->addMessage(
        'settingsNotSaved',
        'Error',
        'Error validating your inputs:<br /><br />' . $fieldErrors
            . '<br /><br />Please correct your input.',
        array(
            'modal' => true,
            'width' => 400,
            'dialogClass' => 'info',
        )
    );
}

if ($this->flag == 'deleted') {
    $this->popUpMessage()->addMessage(
        'settingsSaved',
        'Ok',
        'The image of the flag has been deleted successfully.',
        array(
             'modal' => true,
             'height' => 130,
             'width' => 400,
             'dialogClass' => 'info',
        )
    );
}

if ($this->flag == 'notDeleted') {
    $this->popUpMessage()->addMessage(
        'settingsSaved',
        'Ok',
        'Can\'t delete the image file of the flag.',
        array(
             'modal' => true,
             'height' => 130,
             'width' => 400,
             'dialogClass' => 'info',
        )
    );
}

if (isset($this->creationResult)) {
    if ($this->creationResult === true) {
        $this->popUpMessage()->addMessage(
            'settingsSaved',
            'Ok',
            'Your changes have been saved successfully.',
            array(
                 'modal' => true,
                 'height' => 130,
                 'width' => 400,
                 'dialogClass' => 'info',
            )
        );
    } else {
        $this->popUpMessage()->addMessage(
            'settingsSaved',
            'Error',
            'The following error occurred while saving your changes.<br /><br/><span class="error">'
                . $this->creationResult . '</span><br /><br/>Please try again.<br/><br/>',
            array(
                'modal' => true,
                'width' => 400,
                'dialogClass' => 'info',
            )
        );
    }
}

?>
