<h2>Admin - Languages</h2>
<?php echo $this->partial('admin/head-navi.phtml'); ?>
<form action="<?php echo $this->baseUrl();?>/admin_languages/" method="post" id="myForm">
    <p style="margin:0;padding:0;">
        <input type="hidden" id="offset" name="offset" value="<?php echo $this->offset;?>" />
        Filter / Search:
        <input type="text" class="text" id="filterUser" name="filterUser" value="<?php echo $this->escape($this->filterUser);?>" />
        <button type="submit" class="Formbutton" value="Search" onclick="resetOffset();">
            <?php echo $this->getIcon('search', '', 16);?> Search
        </button>
        <button type="submit" class="Formbutton" onclick="$('#filterUser').val('');resetOffset();">
            <?php echo $this->getIcon('delete', '');?> Reset
        </button>
        <?php if ($this->user->hasRight('addLanguage')) {?>
            <button type="button" class="Formbutton" onclick="window.location.href='<?php echo $this->baseUrl();?>/admin_languages/edit/id/0'">
            <?php echo $this->getIcon('plus', '');?> Add language
            </button>
        <?php } ?>
        <br /><br />

        <a href="#" <?php if($this->offset > 0): ?> title="Shortcut ALT+C"
            onclick="mySubmit('offset', '<?php echo $this->offset-$this->recordsPerPage;?>');"
            accesskey="c" class="Formbutton"><?php echo $this->getIcon('Back', '', 16);?>
            <?php else: ?>
            class="Formbutton"><?php echo $this->getIcon('BackDisabled', '', 16);?>
            <?php endif; ?>
        </a>

        <a href="#" <?php if($this->offset + $this->recordsPerPage < $this->hits): ?> title="Shortcut ALT+V"
            onclick="mySubmit('offset', '<?php echo $this->offset+$this->recordsPerPage;?>');"
            accesskey="v" class="Formbutton"><?php echo $this->getIcon('Forward', '', 16);?>
            <?php else: ?>
            class="Formbutton"><?php echo $this->getIcon('ForwardDisabled', '', 16);?>
            <?php endif; ?>
        </a>
        Entries per page:
        <select name="recordsPerPage" onchange="setPageInactive();;resetOffset();$('#myForm').submit();">
            <?php echo $this->selRecordsPerPage;?>
        </select>
        Hits: <?php echo $this->numberFormat($this->hits);?>
        <input type="hidden" name="deleteLanguage" id="deleteLanguage" value="0">
    </p>
</form>

<table class="bdr more-padding small" summary="Languages">
    <tr class="thead">
        <th>&nbsp;</th>
        <th>#</th>
        <th>Locale</th>
        <th>Name</th>
        <th>Active</th>
        <th>Has flag</th>
    </tr>
<?php
if ($this->hits == 0) { ?>
    <tr class="row-odd">
        <td colspan="6" class="error">Sorry, no hits.</td>
    </tr>

<?php
}
$i = 1;
$i += $this->offset;
foreach ($this->languages as $language) {
    $cycleHelper = $this->cycle(array('row-even', 'row-odd'));
    $editUrl = $this->baseUrl() . '/admin_languages/edit/id/' . $language['id'] . '/';
?>
    <tr class="<?php echo $cycleHelper->next(); ?>">
        <td>
            <a href="<?php echo $editUrl; ?>" title="Edit language"><?php echo $this->getIcon('Edit', ''); ?></a>
            <?php if ($this->user->hasRight('deleteLanguage')) { ?>
                <a href="#" title="Delete language" id="deleteLanguage-<?php echo $language['id'];?>" class="deleteLanguage">
                    <?php echo $this->getIcon('delete', ''); ?>
                </a>
            <?php } ?>
        </td>
        <td class="right"><?php echo $i++; ?>.</td>
        <td><a href="<?php echo $editUrl; ?>" title="Edit language"><?php echo $language['locale']; ?></a></td>
        <td><a href="<?php echo $editUrl; ?>" title="Edit language"><?php echo $language['name']; ?></a></td>
        <td><?php echo $language['active'] ? $this->getIcon('Ok', 'Yes', 16) : $this->getIcon('Attention', 'No', 16); ?></td>
        <td><?php echo $language['hasFlag'] ? $this->printFlag($language['id']) : $this->getIcon('Attention', 'No flag uploaded', 16); ?></td>
    </tr>
<?php
}
?>
</table>
<div id="confirmDeleteLanguage" style="display:none">
    Are you really sure you want to delete this language?<br />
    This will also remove all translations and all edit rights of users for this language.
</div>
<?php $this->jQuery()->onLoadCaptureStart(); ?>
$('.deleteLanguage').click(function() {
    var a=this;
    $('#confirmDeleteLanguage').dialog({
        autoOpen: true,
        modal: true,
        title: 'Really delete?',
        width: 380,
        height: 160,
        buttons : {
                    "Yes, delete language": function() {
                        var id = a.id.replace(/deleteLanguage-/, '');
                        $('#deleteLanguage').attr('value', id);
                        $('#myForm').submit();
                    },
                    "Cancel": function() {
                        $(this).dialog("close");
                    }
                  }
    })
});
<?php
if (isset($this->languageDeleted)) {
    if ($this->userDeleted == true) {
        $this->popUpMessage()->addMessage(
            'userDeleted',
            'Success',
            'The user has been deleted successfully.<br />All log entries, settings and rights have been removed too.',
            array(
                'modal' => true,
                'height' => 160,
                'width' => 340,
                'dialogClass' => 'info',
            )
        );
    } else {
        $this->popUpMessage()->addMessage(
            'userDeleted',
            'Error',
            'There was an error deleting this user.<br />Please try again.',
            array(
                'modal' => true,
                'height' => 140,
                'width' => 340,
                'dialogClass' => 'info',
            )
        );

    }
}
$this->jQuery()->onLoadCaptureEnd();
