<div id="headline">
    <h2><?php echo $this->lang->L_ADMIN;?> - <?php echo $this->lang->L_LANGUAGES;?></h2>
</div>
<?php echo $this->partial('admin/head-navi.phtml', array('lang' => $this->lang)); ?>
<form action="<?php echo $this->baseUrl();?>/admin_languages/" method="post" id="myForm">
    <p style="margin:0;padding:0;">
        <input type="hidden" id="offset" name="offset" value="<?php echo $this->offset;?>" />
            <?php echo $this->lang->L_FILTER_SEARCH;?>:
        <input type="text" class="text" id="filterLanguage" name="filterLanguage" value="<?php echo $this->escape($this->filterLanguage);?>" />
        <button type="submit" class="Formbutton" value="Search" onclick="resetOffset();">
            <?php echo $this->getIcon('search', $this->lang->L_SEARCH, 16);?> <?php echo $this->lang->L_SEARCH;?>
        </button>
        <button type="submit" class="Formbutton" onclick="$('#filterLanguage').val('');resetOffset();">
            <?php echo $this->getIcon('delete', $this->lang->L_RESET);?> <?php echo $this->lang->L_RESET;?>
        </button>
        <?php if ($this->user->hasRight('addLanguage')) {?>
            <button type="button" class="Formbutton" onclick="window.location.href='<?php echo $this->baseUrl();?>/admin_languages/edit/id/0'">
                <?php echo $this->getIcon('plus', $this->lang->L_ADD_NEW_LANGUAGE) . ' ' . $this->lang->L_ADD_NEW_LANGUAGE;?>
            </button>
        <?php } ?>
        <br /><br />

        <a href="#" <?php if($this->offset > 0): ?> title="Shortcut ALT+C"
            onclick="mySubmit('offset', '<?php echo $this->offset-$this->recordsPerPage;?>');"
            accesskey="c" class="Formbutton"><?php echo $this->getIcon('Back', '', 16);?>
            <?php else: ?>
            class="Formbutton"><?php echo $this->getIcon('BackDisabled', '', 16);?>
            <?php endif; ?>
        </a>

        <a href="#" <?php if($this->offset + $this->recordsPerPage < $this->hits): ?> title="Shortcut ALT+V"
            onclick="mySubmit('offset', '<?php echo $this->offset+$this->recordsPerPage;?>');"
            accesskey="v" class="Formbutton"><?php echo $this->getIcon('Forward', '', 16);?>
            <?php else: ?>
            class="Formbutton"><?php echo $this->getIcon('ForwardDisabled', '', 16);?>
            <?php endif; ?>
        </a>
        <?php echo $this->lang->L_ENTRIES_PER_PAGE;?>:
        <select name="recordsPerPage" onchange="setPageInactive();;resetOffset();$('#myForm').submit();">
            <?php echo $this->selRecordsPerPage;?>
        </select>
        <?php echo $this->lang->L_HITS;?>: <?php echo $this->numberFormat($this->hits);?>
        <input type="hidden" name="deleteLanguage" id="deleteLanguage" value="0" />
    </p>
</form>

<table class="bdr more-padding small" summary="Languages">
    <tr class="thead">
        <th>&nbsp;</th>
        <th>#</th>
        <th><?php echo $this->lang->L_LOCALE;?></th>
        <th><?php echo $this->lang->L_NAME;?></th>
        <th><?php echo $this->lang->L_STATUS;?></th>
        <th><?php echo $this->lang->L_FLAG;?></th>
    </tr>
<?php
if ($this->hits == 0) { ?>
    <tr class="row-odd">
        <td colspan="6" class="error">Sorry, no hits.</td>
    </tr>

<?php
}
$i = 1;
$i += $this->offset;
foreach ($this->languages as $language) {
    $cycleHelper = $this->cycle(array('row-even', 'row-odd'));
    $editUrl = $this->baseUrl() . '/admin_languages/edit/id/' . $language['id'] . '/';
?>
    <tr class="<?php echo $cycleHelper->next(); ?>">
        <td>
            <a href="<?php echo $editUrl; ?>" title="<?php echo $this->lang->L_EDIT_LANGUAGE;?>">
                <?php echo $this->getIcon('Edit', ''); ?>
            </a>
            <?php if ($this->user->hasRight('deleteLanguage')) { ?>
                <a href="#" title="<?php echo $this->lang->L_DELETE_LANGUAGE;?>" id="deleteLanguage-<?php echo $language['id'];?>" class="deleteLanguage">
                    <?php echo $this->getIcon('delete', ''); ?>
                </a>
            <?php } ?>
        </td>
        <td class="right">
            <a href="<?php echo $editUrl; ?>" title="<?php echo $this->lang->L_EDIT_LANGUAGE;?>">
                <?php echo $i++; ?>.
            </a>
        </td>
        <td>
            <a href="<?php echo $editUrl; ?>" title="<?php echo $this->lang->L_EDIT_LANGUAGE;?>">
                <?php echo $language['locale']; ?>
            </a>
        </td>
        <td>
            <a href="<?php echo $editUrl; ?>" title="<?php echo $this->lang->L_EDIT_LANGUAGE;?>">
                <?php echo $language['name']; ?>
            </a>
        </td>
        <td>
            <div id="lang-<?php echo $language['id'];?>"
                <?php if ($this->fallbackLanguageId != $language['id']) { ?>
                    class="switchLanguageStatus"
                <?php } ?>
                >
                <?php echo $language['active'] ? $this->getIcon('Ok', $this->lang->L_CHANGE_STATUS, 16) : $this->getIcon('NotOk', $this->lang->L_CHANGE_STATUS, 16); ?>
            </div>
        </td>
        <td>
            <a href="<?php echo $editUrl; ?>" title="<?php echo $this->lang->L_EDIT_LANGUAGE;?>">
                <?php echo $language['hasFlag'] ? $this->printFlag($language['id']) : $this->getIcon('NotOk', $this->L_NO_FLAG, 16); ?>
            </a>
        </td>
    </tr>
<?php
}
?>
</table>
<div id="confirmDeleteLanguage" style="display:none">
    <?php echo $this->lang->L_CONFIRM_DELETE_LANGUAGE;?>
</div>
<?php $this->jQuery()->onLoadCaptureStart(); ?>
$('.deleteLanguage').click(function() {
    var a=this;
    $('#confirmDeleteLanguage').dialog({
        autoOpen: true,
        modal: true,
        title: '<?php echo $this->escape($this->lang->L_CONFIRM_DELETE_TITLE);?>',
        width: 380,
        height: 160,
        buttons : {
                    "<?php echo $this->escape($this->lang->L_CONFIRM_DELETE_LANGUAGE_BUTTON);?>": function() {
                        var id = a.id.replace(/deleteLanguage-/, '');
                        $('#deleteLanguage').attr('value', id);
                        $('#myForm').submit();
                    },
                    "<?php echo $this->lang->L_CANCEL;?>": function() {
                        $(this).dialog("close");
                    }
                  }
    })
});
$('.switchLanguageStatus').click(function() {
    var id = this.id.replace(/lang-/, '');
    $(this).html(imgAjax);
    $.ajax({
        type: 'POST',
        url: '<?php echo $this->serverUrl() . $this->baseUrl();?>/ajax/switch-language-status' ,
        dataType: 'json',
        async : true,
        cache: false,
        data:{
            'languageId' : id
        },
        success:function(data) {
            $('#lang-' + id).html(data.icon);
        },
        error:function(error) {
            $('#lang-' + id).html(imgError);
        }
    });
});
<?php
$this->jQuery()->onLoadCaptureEnd();
if (isset($this->languageDeleted)) {
    $this->showNotification(
        $this->languageDeleted,
        $this->lang->L_LANGUAGE_DELETED_SUCCESSFULLY,
        $this->lang->L_ERROR_DELETING_LANGUAGE,
        4000
    );
}
