<?php
$cycleHelper = $this->cycle(array('row-even', 'row-odd'));
$i = $this->offset +1;
?>
<div>&nbsp;</div>
<h4>Edit rights:</h4>
<?php
echo $this->partial('/helper/search-users.phtml', array(
        'user'              => $this->user,
        'hits'              => $this->hits,
        'offset'            => $this->offset,
        'recordsPerPage'    => $this->recordsPerPage,
        'selRecordsPerPage' => $this->selRecordsPerPage,
        'filterUser'        => $this->filterUser,
        'offset'            => $this->offset,
    )
);
?>
<table class="bdr more-padding" summary="List of language settings">
    <tr class="thead">
        <th>#</th>
        <th><?php echo $this->lang->L_USER;?></th>
        <th><?php echo $this->lang->L_STATUS;?></th>
    </tr>
    <?php
    if (!empty($this->users)) {
        foreach ($this->users as $user) {
        ?>
        <tr class="<?php echo $cycleHelper->next();?>">
            <td class="right">
                <label title="<?php echo $this->lang->L_CHANGE_STATUS;?>" for="img-<?php echo $user['id'];?>" class="switchUserEditRightLabel">
                    <?php echo $i;?>.
                </label>
            </td>
            <td>
                <label title="<?php echo $this->lang->L_CHANGE_STATUS;?>" for="img-<?php echo $user['id'];?>" class="switchUserEditRightLabel">
                    <?php echo $this->escape($user['username']);?>
                </label>
            </td>
            <td>
                <div id="img-<?php echo $user['id'];?>" class="switchUserEditRight">
                    <?php
                        if (isset($this->translators[$user['id']])) {
                            echo $this->getIcon('Ok', $this->lang->L_CHANGE_STATUS, 16);
                        } else {
                            echo $this->getIcon('NotOk', $this->lang->L_CHANGE_STATUS, 16);
                        }
                    ;?>
                </div>
            </td>
        </tr>
        <?php
            $i++;
        }
    }
    ?>
</table>
<p>
    <br /><br />
</p>
<?php
$this->jQuery()->onLoadCaptureStart(); ?>
var imgAjax  = '<?php echo $this->getIcon('ajax-loader');?>';
var imgError = '<?php echo $this->getIcon('NotOk', '', 16);?>';

$('.switchUserEditRight').click(function() {
    var userId = this.id.replace(/img-/, '');
    $('#img-' + userId).html(imgAjax);
    $.ajax({
        type: 'POST',
        url: '<?php echo $this->serverUrl() . $this->baseUrl();?>/ajax/switch-language-edit-right' ,
        dataType: 'json',
        async : true,
        cache: false,
        data:{
            'languageId': <?php echo $this->languageId;?>,
            'userId'    : userId
        },
        success:function(data) {
            $('#img-' + userId).html(data.icon);
        },
        error:function(error) {
            $('#img-' + userId).html(imgError);
        }
    });
});
$('.switchUserEditRightLabel').click(function() {
    var id = $(this).attr('for');
    $('#' + id).trigger('click');
});

<?php
$this->jQuery()->onLoadCaptureEnd();