<?php
$currentPage  = ceil(($this->offset + 1) / $this->recordsPerPage);
$nrOfPages    = ceil($this->rows / $this->recordsPerPage);
?>
<div id="headline">
    <h2><?php echo $this->lang->L_LOG;?></h2>
</div>
<form action="<?php echo $this->baseUrl();?>/log/index" method="post" id="myForm" onsubmit="setPageInactive();">
    <table class="bdr more-padding" summary="Filter options">
            <tr>
                <td class="vmiddle"><?php echo $this->lang->L_FILTER_BY_LANGUAGE;?>:</td>
                <td>
                    <select class="select" name="filterLanguage" id="filterLanguage" onchange="resetOffset();$('#myForm').submit();">
                        <?php echo $this->selectFilterLanguage;?>
                    </select>
                    <input type="hidden" id="offset" name="offset" value="<?php echo $this->offset;?>" />
                </td>
                <td class="vmiddle">
                    <button type="submit" class="Formbutton ui-corner-all" onclick="$('#filterLanguage').val('');resetOffset();">
                        <?php echo $this->getIcon('delete', '');?> <?php echo $this->lang->L_RESET;?>
                    </button>
                </td>
            </tr>
            <tr>
                <td class="vmiddle"><?php echo $this->lang->L_FILTER_BY_USER;?>:</td>
                <td>
                    <select class="select" name="filterUser" id="filterUser" onchange="resetOffset();$('#myForm').submit();">
                        <?php echo $this->selectFilterUser;?>
                    </select>
                </td>
                <td>
                    <button type="submit" class="Formbutton ui-corner-all" onclick="$('#filterUser').val('');resetOffset();">
                        <?php echo $this->getIcon('delete', '');?> <?php echo $this->lang->L_RESET;?>
                    </button>
                </td>
            </tr>
            <tr>
                <td class="vmiddle"><?php echo $this->lang->L_FILTER_BY_ACTION;?>:</td>
                <td>
                    <select class="select" name="filterAction" id="filterAction" onchange="resetOffset();$('#myForm').submit();">
                        <?php echo $this->selectFilterAction;?>
                    </select>
                </td>
                <td>
                    <button type="submit" class="Formbutton ui-corner-all" onclick="$('#filterAction').val('');resetOffset();">
                        <?php echo $this->getIcon('delete', '');?> <?php echo $this->lang->L_RESET;?>
                    </button>
                </td>
            </tr>
        </table>
        <div class="top-margin">
            <a href="#" <?php if($this->offset > 0): ?> title="<?php echo $this->lang->L_PREVIOUS_PAGE;?> (<?php echo $this->lang->L_SHORTCUT;?> ALT+C)"
                onclick="mySubmit('offset', '<?php echo $this->offset-$this->recordsPerPage;?>');"
                accesskey="c" class="Formbutton ui-corner-all"><?php echo $this->getIcon('Back', '', 16);?>
                <?php else: ?>
                class="Formbutton ui-corner-all"><?php echo $this->getIcon('BackDisabled', '', 16);?>
                <?php endif; ?>
            </a>

            <a href="#" <?php if($this->offset + $this->recordsPerPage < $this->rows): ?> title="<?php echo $this->lang->L_NEXT_PAGE;?> (<?php echo $this->lang->L_SHORTCUT;?> ALT+V)"
                onclick="mySubmit('offset', '<?php echo $this->offset+$this->recordsPerPage;?>');"
                accesskey="v" class="Formbutton ui-corner-all"><?php echo $this->getIcon('Forward', '', 16);?>
                <?php else: ?>
                class="Formbutton ui-corner-all"><?php echo $this->getIcon('ForwardDisabled', '', 16);?>
                <?php endif; ?>
            </a>
            <?php echo sprintf($this->lang->L_PAGE_X_OF_Y, $currentPage, $nrOfPages); ?> |
            <?php echo $this->lang->L_HITS;?>: <?php echo $this->numberFormat($this->rows);?>
            <span style="padding:0;margin:0;">|
                <?php echo $this->lang->L_ENTRIES_PER_PAGE;?>:
            <select name="recordsPerPage" onchange="setPageInactive();resetOffset();$('#myForm').submit();">
                <?php echo $this->selRecordsPerPage;?>
            </select>
        </span>

        </div>
</form>

<table class="bdr small" summary="List of log entries">
    <tr class="thead">
<?php if ($this->canDelete) { ?>
        <th>&nbsp;</th>
<?php } ?>
        <th>#</th>
        <th><?php echo $this->lang->L_DATETIME;?></th>
        <th><?php echo $this->lang->L_USER;?></th>
        <th><?php echo $this->lang->L_ACTION;?></th>
        <th><?php echo $this->lang->L_LANGUAGE;?></th>
        <th><?php echo $this->lang->L_KEY;?></th>
        <th><?php echo $this->lang->L_NEW_VALUE;?></th>
        <th><?php echo $this->lang->L_OLD_VALUE;?></th>
    </tr>
<?php
    $i = $this->offset+1;
    if (sizeof($this->logEntries) == 0) {
        ?>
        <tr class="<?php echo$this->cycle(array('row-even', 'row-odd'))->next();?>">
            <td colspan="8" class="error"><?php echo $this->lang->L_NO_HITS;?></td>
        </tr>

        <?php
    }
foreach ($this->logEntries as $entry)
{
?>
    <tr class="<?php echo$this->cycle(array('row-even', 'row-odd'))->next();?>">
        <?php
            if ($this->canDelete) {
                $delete = '<a href="#" title="' . $this->lang->L_DELETE_LOG_ENTRY . '" onclick="deleteLogEntry(\''
                            . $entry['id'] . '\');">';
                echo '<td>' . $delete;
                echo '<img src="' . $this->getIconSrc('delete') . '" style="padding-top:2px;" alt="" '
                    .'title="' . $this->lang->L_DELETE_LOG_ENTRY . '" height="10" width="10"/> ';
                echo '</a></td>';
            }
        ?>
        <td class="right"><?php echo $this->numberFormat($i);?>.</td>
        <td class="nowrap"><?php echo $entry['dt'];?></td>
        <td><?php echo $this->printTranslators($entry['user_id']);?></td>
        <td class="nowrap"><?php echo $entry['action'];?></td>
        <td class="nowrap">
            <?php
                if (isset($this->languages[$entry['lang_id']])) {
                    echo $this->languages[$entry['lang_id']]['name'] . ' (' . $this->languages[$entry['lang_id']]['locale'] . ')';
                } else {
                    echo '-';
                }
            ?>
        </td>
        <td>
            <?php
                if ($entry['key_id'] == 0) {
                    echo '-';
            } else {
                echo $entry['key'];
            }
            ;?>
        </td>
        <td><?php echo $this->out($entry['newValue']);?></td>
        <td><?php echo $this->out($entry['oldValue']);?></td>
    </tr>
<?php
    $i++;
}
?>
</table>
<script type="text/javascript">
function deleteLogEntry(id)
{
    if (confirm('<?php echo $this->jsEscape($this->lang->L_CONFIRM_DELETE_LOG_ENTRY);?>')) {
        $('#myForm').attr('action', '<?php echo $this->baseUrl();?>/log/delete/id/' + id);
        setPageInactive();
        $('#myForm').submit();
    }
}
</script>
