<?php
$projectConfig   = $this->config->getParam('project');
$interfaceConfig = $this->config->getParam('interface');
$dynamicConfig   = Msd_Registry::getDynamicConfig();
$guiLanguages    = $dynamicConfig->getParam('availableGuiLanguages');
$theme           = $interfaceConfig['theme'];
$language        = $interfaceConfig['language'];
$this->headMeta()
    ->appendHttpEquiv('content-language', $language)
    ->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8')
    ->appendHttpEquiv('expires', 'Wed, 26 Feb 1997 08:21:57 GMT')
    ->appendHttpEquiv('pragma', 'no-cache')
    ->appendHttpEquiv('Cache-Control', 'no-cache')
    ->appendName('author', 'Daniel Schlichtholz')
    ->appendName('robots', 'noindex,nofollow');

$this->jQuery()->addStylesheet($this->baseUrl().'/css/' . $theme . '/jquery/jquery-ui.custom.css');
$this->jQuery()->addStylesheet($this->baseUrl().'/css/' . $theme . '/fileuploader.css');
$this->jQuery()->addStylesheet($this->baseUrl().'/css/' . $theme . '/style.css');
$this->jQuery()->addStylesheet($this->baseUrl().'/css/' . $theme . '/jquery/jquery.ui.selectmenu.css');
$request = Zend_Controller_Front::getInstance()->getRequest();
if ($request->getControllerName() == 'index' && ($request->getActionName() == 'login' || $request->getActionName() == 'register')) {
    $this->jQuery()->addStylesheet($this->themeBaseUrl().'/login.css');
}
$this->jQuery()->addJavascriptFile($this->baseUrl('/js/script.js'));
$this->jQuery()->addJavascriptFile($this->baseUrl('/js/jquery/autogrow.js'));
$this->jQuery()->addJavascriptFile($this->baseUrl('/js/jquery/jquery.tmpl.min.js'));
$this->jQuery()->addJavascriptFile($this->baseUrl('/js/jquery/jquery.ui.selectmenu.js'));

$this->jQuery()->setLocalPath($this->baseUrl() . '/js/jquery/jquery.min.js');
$this->jQuery()->setUiLocalPath($this->baseUrl() . '/js/jquery/jquery-ui.min.js');
$this->jQuery()->setVersion('1.7.1');
$this->jQuery()->setUiVersion('1.8.5');
$this->jQuery()->uiEnable();

$messages = (string) $this->popUpMessage();
if ($this->dynamicConfig->getParam('optimizeTables') == true) {
    $this->partial('/helper/optimize-tables.phtml', array('lang' => $this->lang));
}
$this->jQuery()->onLoadCaptureStart();
?>
$('select').selectmenu({
    style:'dropdown'
});
$('#switchLanguage').selectmenu({
    style:'dropdown',
    width: 'auto',
    icons: [
    <?php foreach ($guiLanguages as $lang) { ?>
        {find: '.<?php echo $lang['locale'];?>'},
    <?php } ?>
    ],
    change: function() {
        $('#formSwitchLanguage').hide();
        // preserve inputs from other forms
        $('form:not(#formSwitchLanguage) :input').each(function() {
            $('#formSwitchLanguage').append(this);
        });
        $('#formSwitchLanguage').submit();
    }
});
var imgAjax  = '<?php echo $this->getIcon('ajax-loader');?>';
var imgError = '<?php echo $this->getIcon('Attention', $this->lang->L_ERROR, 16);?>';
<?php
$this->jQuery()->onLoadCaptureEnd();
?>
<?php echo $this->doctype();?>
<html xmlns="http://www.w3.org/1999/xhtml"
    lang="<?php echo $language?>"
    xml:lang="<?php echo $language?>">
<head>
    <title><?php echo $projectConfig['name'];?> - Online Translation Center</title>
    <?php
        echo (string) $this->jQuery();
        echo $this->headMeta() . "\n";
        echo $this->headScript() . "\n";?>
    <style type="text/css">
    <?php foreach ($guiLanguages as $lang) { ?>
        body .<?php echo $lang['locale'];?> .ui-selectmenu-item-icon {
            background-image:url("<?php echo $this->serverUrl() . $this->baseUrl();?>/images/flags/<?php echo $lang['locale'];?>.gif");
        }
    <?php } ?>
        body {direction: ltr;}
    </style>
</head>

<body>
    <div id="header"></div>
    <div id="container">
        <?php
            echo $messages;
            echo $this->menu($guiLanguages);
            if (!$this->isLogin) { ?>
                <div id="content"><?php
            }
            echo $this->layout()->content;
            if (!$this->isLogin) { ?>
                </div><?php
            }
        ?>
    </div>
    <div id="page-loader"><?php echo $this->getIcon('ajax-loader');?></div>
    <?php
        if ($this->dynamicConfig->getParam('optimizeTables') == true) {
            $this->dynamicConfig->setParam('optimizeTables', false);
        ?>
        <div id="optimizationError" style="display:none">
            <?php echo $this->lang->L_ERROR_OPTIMIZING_TABLES;?><br /><br />
            <span id="optimizeErrors"></span>
        </div>
    <?php } ?>
    <div class="spacer"></div>
    <div class="spacer"></div>
    <div id="footer">
        <p>
            <?php echo $this->lang->L_FOOTER_EXPLAIN;?> &middot;
            <a href="http://oTranCe.de/en/"><?php echo $this->lang->L_FOOTER_HOMEPAGE;?></a> &middot;
            <a href="http://oTranCe.de/en/team/"><?php echo $this->lang->L_FOOTER_TEAM;?></a> &middot;
            <a href="http://oTranCe.de/en/project/donate/"><?php echo $this->lang->L_FOOTER_DONATE;?></a>&nbsp;
        </p>
    </div>
</body>
</html>
