<?php
$i = 1;
?>
<h2>Home</h2>
<h4>Status of language packs:</h4>
<table class="bdr small" summary="List of languages and their maintainers">
    <tr class="thead">
        <th>#</th>
        <th colspan="3">Language</th>
        <th>Progress</th>
        <th><?php echo $this->getIcon('Ok', 'Done', 16);?></th>
        <th><?php echo $this->getIcon('Edit', 'To do', 16);?></th>
        <th>Done</th>
        <th>Status</th>
        <th>User with edit rights</th>
    </tr>
<?php
$cycleHelper = $this->cycle(array('row-even', 'row-odd'));
foreach ($this->status as $langId => $val)
{
    $greenBar = (int) $val['done'] * 2;
    $redBar = (int) 200-$greenBar;
?>
    <tr class="<?php echo $cycleHelper->next();?>">
        <td class="right"><?php echo $i;?>.</td>
        <td>
            <?php echo $this->printFlag($langId);?>
        </td>
        <td><?php echo $this->languages[$langId]['locale'];?></td>
        <td><?php echo $this->languages[$langId]['name'];?></td>
        <td class="right">
            <div style="width:200px;height:14px;border:1px solid #ccc;margin-top:2px;">
                <div class="greenBar" style="width:<?php echo $greenBar;?>px;">&nbsp;</div>
                <div class="redBar" style="width:<?php echo $redBar;?>px;">&nbsp;</div>
             </div>
             <div style="position:relative;top:-15px;left:-6px;"><?php echo $val['done'];?>%</div>
         </td>
        <td class="right"><?php echo $this->numberFormat($val['translated']);?></td>
        <td class="right">
            <?php
                if ($val['notTranslated'] == 0) {
                    echo '-';
                } else {
                    echo $this->numberFormat($val['notTranslated']);
        }
            ?>
        </td>
        <td class="right"><?php echo $val['done'];?>%</td>
        <td>
        <?php
            if ($val['done'] < 90) {
                echo '<span class="error">Needs work</span>';
            } elseif ($val['done']<98) {
                echo '<span class="ok">Ok</span>';
            } else {
                echo '<span class="ok">Perfect</span>';
            }
        ?>

        </td>
        <td><?php echo $this->printTranslators($val['translators']);?></td>
    </tr>
<?php
    $i++;
}
?>
</table>