<?php $this->jQuery()->addOnLoad("$('#user').focus();"); ?>
<div id="login">
    <h1>
        <br /><br />Translation-Center: Log in
    </h1>
        <br /><br />
    <div style="width:500px;margin: auto auto; vertical-align:middle;
        background: url(<?php echo $this->baseUrl(); ?>/css/otc/pics/User.png) no-repeat 5% 36%; ">
    <form action="<?php
        echo $this->url(
            array(
                'controller' => 'index',
                'action' => 'login',
            ),
            null,
            true
        ); ?>
        " method="post" enctype="multipart/formdata">
<?php
echo $this->form;
?>
</form>
</div>
</div>
<?php
$loginInfoFile = APPLICATION_PATH . '/../data/login-info.phtml';
if (file_exists($loginInfoFile) && is_readable($loginInfoFile)) {
    $loginInfoFile = realpath($loginInfoFile);
    $loginInfoDir = dirname($loginInfoFile);
    $this->addScriptPath($loginInfoDir);
    echo $this->render(basename($loginInfoFile));
}
