<?php $this->jQuery()->addOnLoad("$('#user').focus();");?>
<div id="logout">
<?php
echo $this->partial(
    'helper/switch-language-box.phtml',
    array(
         'lang'                  => $this->lang,
         'controller'            => 'index',
         'request'               => $this->request,
         'availableGuiLanguages' => $this->availableGuiLanguages,
    )
);

$forgotPasswordUrl = $this->url(array('controller'=>'index_password','action'=>'index'));
?>
</div>
<div id="login">
    <h1>
        <br /><br /><?php echo $this->lang->L_TRANSLATION_CENTER .': ' . $this->lang->L_LOGIN;?>
    </h1>
        <br /><br />
    <div style="width:600px;margin: auto auto; vertical-align:middle;
        background: url(<?php echo $this->themeBaseUrl(); ?>/pics/User.png) no-repeat 5% 36%; ">
    <form action="<?php
        echo $this->url(
            array(
                'controller' => 'index',
                'action' => 'login',
            ),
            null,
            true
        ); ?>
        " method="post" enctype="multipart/formdata">
    <?php echo $this->form; ?>
    </form>
    <?php printf($this->lang->L_GOTO_REGISTER_PAGE, $this->baseUrl() . '/register/index/'); ?><br>
    <?php printf($this->lang->L_GOTO_FORGOT_PASSWORD_PAGE, $forgotPasswordUrl); ?>
</div>
</div>
<?php
$loginInfoFile = APPLICATION_PATH . '/../data/login-info.phtml';
if (file_exists($loginInfoFile) && is_readable($loginInfoFile)) {
    $loginInfoFile = realpath($loginInfoFile);
    $loginInfoDir = dirname($loginInfoFile);
    $this->addScriptPath($loginInfoDir);
    echo $this->render(basename($loginInfoFile));
}

