<?php
$this->controller = $this->request->getControllerName();
$user             = new Application_Model_User();
?>
<div id="sidebar">
    <h2><?php echo $this->projectConfig['name'];?></h2>
    <div id="version">
        <a href="<?php echo $this->projectConfig['url'];?>" title="<?php echo $this->lang->L_HOME;?>">
            <?php if (!empty($this->projectConfig['logo']['large'])) { ?>
                <img src="<?php echo $this->baseUrl() . $this->projectConfig['logo']['large']; ?>" alt="<?php echo $this->lang->L_PROJECT_LOGO;?>" />
            <?php } ?>
        </a>
    </div>

    <div id="menu">
        <ul class="menu">
            <li
                <?php if ($this->controller == 'index') {
                    echo ' class="active"';
                };?>
                ><a href="<?php echo $this->baseUrl();?>/index/index"><?php echo $this->getIcon('Home', $this->lang->L_HOME, 20);?><?php echo $this->lang->L_HOME;?></a>
            </li>
            <?php
            if ($user->hasRight('editConfig')) {
                ?>
                <li
                    <?php if ($this->controller == 'settings') {
                        echo ' class="active"';
                    };?>
                    ><a href="<?php echo $this->baseUrl();?>/settings/index"><?php echo $this->getIcon('Configure', $this->lang->L_HOME, 20);?><?php echo $this->lang->L_CONFIGURATION;?></a>
                </li>
                <?php
            }
            if ($user->hasRight('showEntries')) {
             ?>
                <li
                    <?php if ($this->controller == 'entries') {
                        echo ' class="active"';
                    };?>
                ><a href="<?php echo $this->baseUrl();?>/entries/index"><?php echo $this->getIcon('Edit', '', 20);?><?php echo $this->lang->L_TRANSLATIONS;?></a>
                </li>
                <?php
            }
            if ($user->hasRight('showDownloads')) {
                ?>
                <li
                    <?php if ($this->controller == 'downloads') {
                        echo ' class="active"';
                    };?>
                ><a href="<?php echo $this->baseUrl();?>/downloads/"><?php echo $this->getIcon('Download', '', 20);?><?php echo $this->lang->L_DOWNLOADS;?></a>
                </li>
                <?php
            }
            if ($user->hasRight('showBrowseFiles')) {
                ?>
                <li
                    <?php if ($this->controller == 'browser') {
                        echo ' class="active"';
                    };?>
                ><a href="<?php echo $this->baseUrl();?>/browser/"><?php echo $this->getIcon('Reports', '', 20);?><?php echo $this->lang->L_FILEBROWSER;?></a>
                </li>
                <?php
            }
            if ($user->hasRight('showImport')) {
                ?>
                <li
                    <?php if ($this->controller == 'import') {
                        echo ' class="active"';
                    };?>
                    ><a href="<?php echo $this->baseUrl();?>/import"><?php echo $this->getIcon('OpenFile', '', 20);?><?php echo $this->lang->L_IMPORT;?></a>
                </li>
                <?php
            }
            if ($user->hasRight('showExport')) {
                ?>
                    <li
                        <?php if ($this->controller == 'export') {
                            echo ' class="active"';
                        };?>
                        ><a href="<?php echo $this->baseUrl();?>/export"><?php echo $this->getIcon('BackupDatabase', '', 20);?><?php echo $this->lang->L_EXPORT;?></a>
                    </li>
                <?php
            }
            if ($user->hasRight('showLog')) {
                ?>
                <li
                    <?php if ($this->controller == 'log') {
                        echo ' class="active"';
                    };?>
                    ><a href="<?php echo $this->baseUrl();?>/log"><?php echo $this->getIcon('log', '', 20);?><?php echo $this->lang->L_LOG;?></a>
                </li>
                <?php
            }
            if ($user->hasRight('showStatistics')) {
                ?>
                <li
                    <?php if ($this->controller == 'statistics') {
                        echo ' class="active"';
                    };?>
                    ><a href="<?php echo $this->baseUrl();?>/statistics"><?php echo $this->getIcon('Statistics', '', 20);?><?php echo $this->lang->L_STATISTICS;?></a>
                </li>
                <?php
            }
            if ($user->hasRight('admin')) {
                ?>
                <li
                    <?php if ($this->controller == 'admin') {
                        echo ' class="active"';
                    };?>
                    ><a href="<?php echo $this->baseUrl();?>/admin"><?php echo $this->getIcon('Admin', '', 20);?><?php echo $this->lang->L_ADMIN;?></a>
                </li>
                <?php
            }
            ?>
        </ul>
    </div>
</div>

<div id="logout">
    <div id="loggedin-user"><p>
        <strong><?php echo $this->getUsername();?></strong> |
        <a href="<?php echo $this->baseUrl();?>/index/logout/"><?php echo $this->lang->L_LOG_OUT;?></a></p>
    </div>
    <div id="icon"><?php echo $this->getIcon('LockUser', $this->lang->L_LOGGED_IN, 16);?></div>
</div>
