<?php
$interfaceConfig = $this->config->getParam('interface');
$theme = $interfaceConfig['theme'];
$this->controller = $this->request->getControllerName();
$this->action = $this->request->getActionName();
$user = new Application_Model_User();
?>
<div id="sidebar">

<a href="<?php echo $this->projectConfig['url'];?>"
    title="Project Home">
        <img src="<?php echo $this->baseUrl() . $this->projectConfig['logo']['small']; ?>" alt="<?php echo $this->projectConfig['name'];?>" /></a>

<div id="version">
    <a href="<?php echo $this->projectConfig['url'];?>" title="Project Home">
        <span class="version-line"><?php echo $this->projectConfig['name'];?></span>
    </a>
    <img src="<?php echo $this->baseUrl() . $this->projectConfig['logo']['large']; ?>" alt="Large project logo" />
</div>

<div id="menu">
    <ul class="menu">
        <li
            <?php if ($this->controller == 'index') {
                echo ' class="active"';
            };?>
            ><a href="<?php echo $this->baseUrl();?>/index/index"><?php echo $this->getIcon('Home', $this->lang->L_HOME, 20);?>Home</a>
        </li>
        <?php if ($user->hasRight('editConfig')) { ?>
            <li
                <?php if ($this->controller == 'settings') {
                    echo ' class="active"';
                };?>
                ><a href="<?php echo $this->baseUrl();?>/settings/index"><?php echo $this->getIcon('Configure', $this->lang->L_HOME, 20);?>Configuration</a>
            </li>
        <?php
        }
        if ($user->hasRight('showEntries')) {
        ?>
        <li
            <?php if ($this->controller == 'entries') {
                echo ' class="active"';
            };?>
        ><a href="<?php echo $this->baseUrl();?>/entries/index"><?php echo $this->getIcon('Edit', '', 20);?>Entries</a>
        </li>
        <?php
        }
        if ($user->hasRight('showDownloads')) {
        ?>
        <li
            <?php if ($this->controller == 'downloads') {
                echo ' class="active"';
            };?>
        ><a href="<?php echo $this->baseUrl();?>/downloads/"><?php echo $this->getIcon('Download', '', 20);?>Downloads</a>
        </li>
        <?php } ?>
        <li
            <?php if ($this->controller == 'browser') {
                echo ' class="active"';
            };?>
        ><a href="<?php echo $this->baseUrl();?>/browser/"><?php echo $this->getIcon('Reports', '', 20);?>Browse files</a>
        </li>
        <li
            <?php if ($this->controller == 'import') {
                echo ' class="active"';
            };?>
            ><a href="<?php echo $this->baseUrl();?>/import"><?php echo $this->getIcon('OpenFile', '', 20);?>Import</a>
        </li>
        <?php if ($user->hasRight('export')) { ?>
            <li
                <?php if ($this->controller == 'export') {
                    echo ' class="active"';
                };?>
                ><a href="<?php echo $this->baseUrl();?>/export"><?php echo $this->getIcon('BackupDatabase', '', 20);?>Export</a>
            </li>
        <?php } ?>
        <li
            <?php if ($this->controller == 'log') {
                echo ' class="active"';
            };?>
            ><a href="<?php echo $this->baseUrl();?>/log"><?php echo $this->getIcon('log', '', 20);?>Log</a>
        </li>
        <li
            <?php if ($this->controller == 'statistics') {
                echo ' class="active"';
            };?>
            ><a href="<?php echo $this->baseUrl();?>/statistics"><?php echo $this->getIcon('Statistics', '', 20);?>Statistics</a>
        </li>
        <?php if ($user->hasRight('admin')) { ?>
        <li
            <?php if ($this->controller == 'admin') {
                echo ' class="active"';
            };?>
            ><a href="<?php echo $this->baseUrl();?>/admin"><?php echo $this->getIcon('Admin', '', 20);?>Admin</a>
        </li>
        <?php } ?>
    </ul>
</div>

</div>

<div id="logout">
    <div id="username"><p>
        <strong><?php echo $this->getUsername(); ?></strong> |
        <a href="<?php echo $this->baseUrl();?>/index/logout/">Log out</a></p>
    </div>
    <div id="icon"><?php echo $this->getIcon('LockUser', $this->lang->L_LOGGED_IN, 16);?></div>
</div>
