<div id="login" class="register">
    <h1><br/><br/><?php echo $this->lang->L_REGISTER_TITLE; ?></h1>
    <br /><br />
    <div style="width:500px;margin: auto auto; vertical-align:middle; background: url(<?php echo $this->themeBaseUrl(); ?>/pics/User.png) no-repeat 5% 36%;">
        <form action="<?php echo $this->serverUrl() . $this->baseUrl(); ?>/index/register" method="post" enctype="multipart/formdata">
            <fieldset>
                <legend><?php echo $this->lang->L_REGISTER_INFORMATION; ?></legend>
                <table>
                    <tr>
                        <td><label for="user_name"><?php echo $this->lang->L_USERNAME; ?>:</label></td>
                        <td><input type="text" class="text" name="user[username]" id="user_name"/></td>
                    </tr>
                    <?php if (isset($this->errors['username'])) { ?>
                    <tr>
                        <td></td>
                        <td class="error"><?php echo implode('<br/>', $this->errors['username']);?></td>
                    </tr>
                    <?php } ?>
                    <tr>
                        <td><label for="user_pass1"><?php echo $this->lang->L_PASSWORD;?> (*):</label></td>
                        <td><input type="password" class="text" name="user[pass1]" id="user_pass1"/></td>
                    </tr>
                    <?php if (isset($this->errors['pass1'])) { ?>
                    <tr>
                        <td></td>
                        <td class="error"><?php echo implode('<br/>', $this->errors['pass1']);?></td>
                    </tr>
                    <?php } ?>
                    <tr>
                        <td><label for="user_pass2"><?php echo $this->lang->L_CONFIRM_PASSWORD;?> (*):</label></td>
                        <td><input type="password" class="text" name="user[pass2]" id="user_pass2"/></td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <div class="confirm-password-explain">
                                (*) <?php echo $this->lang->L_CONFIRM_PASSWORD_EXPLAIN;?>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td><button type="submit" class="Formbutton ui-corner-all"><?php echo $this->getIcon('save'); ?> <?php echo $this->lang->L_REGISTER; ?></button></td>
                    </tr>
                </table>
            </fieldset>
        </form>
    </div>
</div>
<?php
if ($this->registerSuccess) {
    $message = $this->lang->L_REGISTRATION_SUCCESSFUL_MESSAGE;
    $this->popUpMessage()->addMessage(
        'registerSuccess',
        'L_REGISTRATION_SUCCESSFUL_TITLE',
        nl2br($message),
        array(
            'modal' => true,
            'height' => 220,
            'width' => 400,
            'dialogClass' => 'info',
            'buttons' => array(
                'L_OK' => "function() { window.location.href='". $this->baseUrl() . "/index/login'; }",
            ),
        )
    );
}
