<?php
$currentPage  = ceil(($this->offset + 1) / $this->recordsPerPage);
$nrOfPages    = ceil($this->rows / $this->recordsPerPage);
?>
<a href="#" <?php if($this->offset > 0): ?> title="<?php echo $this->lang->L_PREVIOUS_PAGE;?> (<?php echo $this->lang->L_SHORTCUT;?> ALT+C)"
    onclick="mySubmit('offset', '<?php echo $this->offset-$this->recordsPerPage;?>');"
    accesskey="c" class="Formbutton ui-corner-all"><?php echo $this->getIcon('Back', '', 16);?>
    <?php else: ?>
    class="Formbutton ui-corner-all disabled"><?php echo $this->getIcon('BackDisabled', '', 16);?>
    <?php endif; ?>
</a>

<a href="#" <?php if($this->offset + $this->recordsPerPage < $this->rows): ?> title="<?php echo $this->lang->L_NEXT_PAGE;?> (<?php echo $this->lang->L_SHORTCUT;?> ALT+V)"
    onclick="mySubmit('offset', '<?php echo $this->offset+$this->recordsPerPage;?>');"
    accesskey="v" class="Formbutton ui-corner-all"><?php echo $this->getIcon('Forward', '', 16);?>
    <?php else: ?>
    class="Formbutton ui-corner-all disabled"><?php echo $this->getIcon('ForwardDisabled', '', 16);?>
    <?php endif; ?>
</a>
<?php echo sprintf($this->lang->L_PAGE_X_OF_Y, $currentPage, $nrOfPages); ?> |
<?php echo $this->lang->L_HITS;?>: <?php echo $this->numberFormat($this->rows);?>
