<h2><?php echo $this->lang->L_ADMIN;?> - <?php echo $this->lang->L_PROJECT;?></h2>
<?php
echo $this->partial('admin/head-navi.phtml', array('lang' => $this->lang));
/**
 * @var Zend_View_Helper_Cycle $cycle
 */
$cycle = $this->cycle(array('row-odd', 'row-even'));
$translateToFallback = $this->settings['translateToFallback'];
?>
<form action="<?php echo $this->baseUrl(); ?>/admin_project" method="post">
    <table class="bdr more-padding" summary="List of project settings">
        <tr class="thead">
            <th colspan="2">Project settings</th>
        </tr>
        <tr class="<?php echo $cycle->next(); ?>">
            <td><label for="name">Project title:</label></td>
            <td><input type="text" class="text" name="name" id="name" value="<?php echo $this->settings['name']; ?>" size="40"/></td>
        </tr>
        <tr class="<?php echo $cycle->next(); ?>">
            <td><label for="url">Project URL:</label></td>
            <td><input type="text" class="text" name="url" id="url" value="<?php echo $this->settings['url']; ?>" size="40"/></td>
        </tr>
        <tr class="<?php echo $cycle->next(); ?>">
            <td><label for="logo_large">Large project logo:</label>
            <br />(relative to project folder)</td>
            <td>
                <input type="text" class="text" name="logo[large]" id="logo_large" value="<?php echo $this->settings['logo']['large']; ?>" onkeyup="updatePreviewImage('large', this.value);" size="40"/><br/>
                <img style="padding:12px;" id="large_preview" src="<?php echo $this->baseUrl() . $this->settings['logo']['large']; ?>" alt="Large logo preview"/></td>
        </tr>
        <tr class="<?php echo $cycle->next(); ?>">
            <td>
                Fallback language:
            </td>
            <td><select name="fallbackLang" id="fallbackLang">
                <?php foreach ($this->languages as $language) { ?>
                <option value="<?php echo $language['id']; ?>"<?php echo ($language['id'] == $this->fallbackLanguageId) ? ' selected="selected"' : ''; ?>><?php echo $language['name']; ?> (<?php echo $language['locale']; ?>)</option>
                <?php } ?>
            </select></td>
        </tr>
        <tr class="<?php echo $cycle->next(); ?>">
            <td>
                <?php echo $this->lang->L_EXPORT_LANGUAGES;?>:<br />
                <?php echo $this->lang->L_EXPORT_LANGUAGES_EXPLAIN;?>
            </td>
            <td>
                <input type="radio" name="translateToFallback" id="translateToFallback_yes" value="1"
                    <?php echo $translateToFallback == 1 ? ' checked="checked"' : '';?>>
                    <label for="translateToFallback_yes"><?php echo $this->lang->L_YES;?></label>
                </input>&nbsp;
                <input type="radio" name="translateToFallback" id="translateToFallback_no" value="0"
                        <?php echo $translateToFallback == 0 ? ' checked="checked"' : '';?>>
                    <label for="translateToFallback_no"><?php echo $this->lang->L_NO;?></label>
                </input>
            </td>
        </tr>
        <tr class="<?php echo $cycle->next(); ?>">
            <td>&nbsp;</td>
            <td><button type="submit" class="Formbutton"><?php echo $this->getIcon('save', ''); ?> Save</button></td>
        </tr>
    </table>
</form>
<script type="text/javascript">
function updatePreviewImage(size, url)
{
    $('#' + size + '_preview').each(function() {
        $(this)[0].src = '<?php echo $this->baseUrl();?>' + url;
    });
}
</script>