<?php
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/fileuploader.js');
?>
<div id="headline">
    <h2><?php echo $this->lang->L_ADMIN;?> - <?php echo $this->lang->L_PROJECTS;?></h2>
</div>
<?php
echo $this->partial('admin/head-navi.phtml', array('lang' => $this->lang));
/**
 * @var Zend_View_Helper_Cycle $cycle
 */
$cycle = $this->cycle(array('row-odd', 'row-even'));
?>
<div>
    <table class="bdr small" summary="List of projects">
        <tr class="thead">
            <th>&nbsp;</th>
            <th><?php echo $this->lang->L_PROJECT_ID;?></th>
            <th><?php echo $this->lang->L_PROJECT_NAME;?></th>
            <th><?php echo $this->lang->L_PROJECT_EMAIL;?></th>
            <th><?php echo $this->lang->L_PROJECT_LOGO;?></th>
        </tr>
        <?php foreach ($this->projects as $projectId => $projectData) :?>
            <tr class="<?php echo $cycle->next();?>">
                <?php if ($this->user->hasRight('admTabProject')): ?>
                    <td class="ssmall nowrap top">&nbsp;
                        <a href="<?php echo $this->baseUrl(); ?>/admin_project/edit/project/<?php echo $projectId; ?>">
                            <?php echo $this->getIcon('Edit', $this->lang->L_CLICK_TO_INLINE_EDIT); ?>
                        </a>
                    </td>
                    <td><?php echo $projectId; ?></td>
                    <td><?php echo $projectData['name']; ?></td>
                    <td><?php echo $projectData['email']; ?>&nbsp;</td>
                    <td>
                        <a href="<?php echo $this->baseUrl(); ?>/admin_project/edit/project/<?php echo $projectId; ?>">
                            <img style="padding:12px;" id="preview"
                             src="<?php echo $this->baseUrl() . $projectData['logo_large']; ?>"
                             alt="<?php echo $this->lang->L_PREVIEW;?>"/>
                        </a>
                    </td>
                <?php endif; ?>
            </tr>
        <?php endforeach; ?>
    </table>
</div>
