<div id="headline">
    <h2><?php echo $this->lang->L_CONFIGURATION . ' - ' . $this->lang->L_USER;?></h2>
</div>
<?php
echo $this->partial('settings/head-navi.phtml', array('lang' => $this->lang,
    'vcsActivated' => $this->vcsActivated
));
?>
<h4><?php echo $this->lang->L_CHANGE_YOUR_PASSWORD; ?></h4>
<form action="<?php echo $this->baseUrl();?>/settings_profile/index" method="post">
    <table class="bdr" summary="Change the password of your user account.">
        <tr class="thead">
            <th colspan="2"><?php echo $this->lang->L_CHANGE_PASSWORD; ?></th>
        </tr>
    <tr class="row-even">
        <td><label for="oldPassword"><?php echo $this->lang->L_OLD_PASSWORD; ?> (*):</label></td>
        <td>
            <input type="password" name="oldPassword" id="oldPassword" class="text"/><?php
            if (isset($this->errors['oldPass'])) { ?>
                <span class="error"><?php echo implode('<br />', $this->errors['oldPass']);?></span><?php
            } ?>
        </td>
    </tr>
    <tr class="row-odd">
        <td><label for="newPassword"><?php echo $this->lang->L_NEW_PASSWORD; ?> (*):</label></td>
        <td>
            <input type="password" name="newPassword" id="newPassword" class="text"/><?php
            if (isset($this->errors['pass1'])) { ?>
                <span class="error"><?php echo implode('<br />', $this->errors['pass1']);?></span><?php
            } ?>
        </td>
    </tr>
        <tr class="row-even">
            <td><label for="newPasswordConfirm"><?php echo $this->lang->L_CONFIRM_PASSWORD; ?> (*):</label></td>
            <td>
                <input type="password" name="newPasswordConfirm" id="newPasswordConfirm" class="text"/>
            </td>
        </tr>
        <tr class="row-odd">
            <td colspan="2">
                <div class="confirm-password-explain">
                    (*) <?php echo $this->lang->L_CONFIRM_PASSWORD_EXPLAIN;?>
                </div>
            </td>
        </tr>
    <tr class="row-even">
        <td>&nbsp;</td>
        <td>
        </td>
    </tr>
    </table>
    <div class="spacer"></div>
    <button type="submit"
            class="Formbutton ui-corner-all"><?php echo $this->getIcon('save', '');?> <?php echo $this->lang->L_SAVE_PASSWORD; ?></button>
    </div>
</form>
<div class="spacer"></div>
<?php
if (isset($this->saved)) {
    $this->showNotification(
        $this->saved,
        $this->lang->L_YOUR_SETTINGS_HAVE_BEEN_SAVED_SUCCESSFULLY,
        $this->lang->L_ERROR_SAVING_CHANGE . '.<br>' . $this->lang->L_TRY_AGAIN
    );
}
