#!/bin/bash
MYSQL_HOST="localhost"
MYSQL_USER="root"
MYSQL_PASS=""
MYSQL_DB="otrance_setup"

REPO_DIR="/srv/www/otc/"
SETUP_DIR="/srv/www/otc_setup"
TEMP_DIR="/tmp/otc"
OTC_PACKAGE="/srv/www/update.otrance.org/files/otrance-1.0.0.zip"
HTTPD_USER="kyoya:www"

if [ -f setup.conf ]; then
	. setup.conf
fi

checkResult() {
	if [ $? -eq 0 ]; then
		echo -ne "\033[1;32m OK"
	else
		echo -ne "\033[1;31m failed"
	fi
	echo -e "\033[0m"
}

if [ -n "$MYSQL_HOST" ]; then
	MYSQL_HOST="-h$MYSQL_HOST"
fi

if [ -n "$MYSQL_USER" ]; then
	MYSQL_USER="-u$MYSQL_USER"
fi

if [ -n "$MYSQL_PASS" ]; then
	MYSQL_PASS="-p$MYSQL_PASS"
fi

echo -n "Removing DB tables from $MYSQL_DB ..."
mysql $MYSQL_HOST $MYSQL_USER $MYSQL_PASS $MYSQL_DB -e 'DROP TABLE `conversions`, `exportlog`, `filetemplates`, `history`, `keys`, `languages`, `translations`, `userrights`, `users`, `usersettings`, `user_languages`;'
checkResult

echo "Cleaning up $SETUP_DIR ..."
cd "$SETUP_DIR"

echo -n "Removing files ..."
sudo rm -rf *
checkResult

echo -n "Creating public directory ..."
sudo mkdir public
checkResult

echo -n "Changing Owner ..."
sudo chown -R $HTTPD_USER public
checkResult

echo -n "Changing permissions ..."
sudo chmod -R ug+rwX public
checkResult

if [ -d "$TEMP_DIR" ]; then
	echo -n "Creating temporary directory $TEMP_DIR ..."
	mkdir -p "$TEMP_DIR"
	checkResult
fi

echo -n "Exporting OTC to $TEMP_DIR ..."
cd "$TEMP_DIR"
svn export "$REPO_DIR" . --force
checkResult

echo -n "Copying setup to $SETUP_DIR/public/ ..."
cp -r setup/ "$SETUP_DIR/public/"
checkResult

echo -n "Creating OTC package $OTC_PACKAGE ..."
zip -ur9 "$OTC_PACKAGE" application/ cli/ data/ docs/ library/ modules/ public/
checkResult

echo -n "Removing temporary files ..."
rm -rf *
checkResult

