<?php
$sortDirection = isset($this->sortDirection) ? $this->sortDirection : SORT_DESC;
$sortDirection = $sortDirection == SORT_ASC ? SORT_DESC : SORT_ASC;
$sortParams = array(
    'controller'=>'statistics',
    'action'=>'index',
    'direction' => $sortDirection
);
$canSeeLog = $this->user->hasRight('showLog');
$filterByUser = array(
    'controller'=>'log',
    'action'=>'index',
    'filterAction' => 'changed'
);
?>
<div id="headline">
    <h2><?php echo $this->lang->L_STATISTICS;?></h2>
</div>
<h4><?php echo $this->lang->L_ACTIVITIES;?>:</h4>
<table class="bdr small" summary="Activity statistics of users">
    <tr class="thead">
        <th>#</th>
        <th>
            <a href="<?php echo $this->url(array_merge($sortParams, array('sortfield' => 'username')));?>">
                <?php echo $this->lang->L_USER;?>
            </a>
        </th>
        <th colspan="3">
            <a href="<?php echo $this->url(array_merge($sortParams, array('sortfield' => 'locale')));?>">
                <?php echo $this->lang->L_LANGUAGE;?>
            </a>
        </th>
        <th>
            <a href="<?php echo $this->url(array_merge($sortParams, array('sortfield' => 'editActions')));?>">
                <?php echo $this->lang->L_EDITED;?>
            </a>
        </th>
        <th>
            <a href="<?php echo $this->url(array_merge($sortParams, array('sortfield' => 'editActionsTotal')));?>">
                <?php echo $this->lang->L_EDITED_TOTAL;?>
            </a>
        </th>
        <th>
            <a href="<?php echo $this->url(array_merge($sortParams, array('sortfield' => 'lastAction')));?>">
                <?php echo $this->lang->L_LATEST_ACTIVITY;?>
            </a>
        </th>
    </tr>
    <?php
    $i = 0;
    $cycleHelper = $this->cycle(array('row-even', 'row-odd'));
    $lastUser = '';
    if (empty($this->userStatistics)) { ?>
        <tr class="row-odd">
            <td colspan="7">
                <div class="error"><?php echo $this->lang->L_NO_HITS;?>.</div>
            </td>
        </tr><?php
    }
    $lastUserId = 0;

    foreach ($this->userStatistics as $values) {
        $userId = $values['user_id'];
        if ($lastUserId !== $userId) {
            $userChanged = true;
            $i++;
        } else {
            $userChanged = false;
        } ?>
        <tr class="<?php echo $cycleHelper->next();?>">
            <td class="right">&nbsp;<?php if ($userChanged) { echo $i .'.'; };?></td>
            <td>&nbsp;<?php
                if ($userChanged) {
                    if ($canSeeLog) {
                        $filterByUser['filterUser'] = $userId;
                        $filterByLanguageParams = $filterByUser;
                        $filterByLanguageParams['filterLanguage'] = $values['lang_id'];
                        echo '<a title="' . $this->lang->L_EDIT . '" href="'
                            . $this->url($filterByUser) .'">'
                            . $this->escape($this->printTranslators($userId)) .'</a>';
                    } else {
                        echo $this->printTranslators($userId);
                    }
                }
                $filterByLanguageParams['filterLanguage'] = $values['lang_id'];?>
            </td>
            <td>
                <a href="<?php echo $this->url($filterByLanguageParams);?>">
                    <?php echo $this->printFlag($values['lang_id'], 16);?>
                </a>
            </td>
            <td>
                <a href="<?php echo $this->url($filterByLanguageParams);?>">
                    <?php echo $this->languages[$values['lang_id']]['locale'];?>
                </a>
            </td>
            <td>
                <a href="<?php echo $this->url($filterByLanguageParams);?>">
                    <?php echo $this->languages[$values['lang_id']]['name'];?>
                </a>
            </td>
            <td class="right">
                <a href="<?php echo $this->url($filterByLanguageParams);?>">
                    <?php echo $this->numberFormat($values['editActions']);?>
                </a>
            </td>
            <td class="right">
                <?php
                if ($userChanged) {
                    if ($canSeeLog) { ?>
                        <a href="<?php echo $this->url($filterByUser);?>">
                            <?php echo $this->numberFormat($values['editActionsTotal']);?>
                        </a><?php
                    } else {
                        echo $this->numberFormat($values['editActionsTotal']);
                    }
                }?>
            </td>
            <td class="right">
                <?php if ($userChanged) {
                    echo $values['lastAction'];
                }?>
            </td>
        </tr>
        <?php
        $lastUserId = $userId;
    } ?>
</table>
