<?php
$code = <<<CODE
/**
 * This file is part of OXID eShop Community Edition.
...
 * @link      http://www.oxid-esales.com
 */
\$sLangName  = "English";
\$aLang = array(
'charset'                                           => 'ISO-8859-15',
'fullDateFormat'                                    => 'Y-m-d H:i:s',
...
'ALIST_META_DESCRIPTION_PREFIX'                     => "You are here:",
);
CODE
?>
<h4>Oxid importer information:</h4>
<table class="bdr more-padding" summary="">
<tr class="row-even">
    <td class="small">Author:</td>
    <td class="small">
        Stefan Krenz, Daniel Schlichtholz
    </td>
</tr>

<tr class="row-odd">
    <td class="small">Description:</td>
    <td class="small">
        This importer is intended to import language files from Oxid eShop.<br />
        It tries to extract the keys and values from typical structure of Oxid's language files.
    </td>
</tr>
<tr class="row-even">
    <td class="small">Structure that can be detected:</td>
    <td class="small">
        <pre><?php echo $this->out($code);?></pre>
    </td>
</tr>
<tr class="row-odd">
    <td class="small">Ignored constants:</td>
    <td class="small">
        $aLang will be examined.
        The constant "charset" is ignored. The export will always be encoded in UTF-8!<br />
    </td>
</tr>
    <tr class="row-even">
        <td class="small">Note:</td>
        <td class="small">
            If you discover character encoding problems, copy &amp; paste the text into the text box
            instead of uploading it. Or try to use the convert button until all characters are shown correctly.
        </td>
    </tr>

</table>
