<?php
$code = <<<CODE
/**
 * This file is part of OXID eShop Community Edition.
...
 * @link      http://www.oxid-esales.com
 */
\$sLangName  = "English";
\$aLang = array(
'charset'                                           => 'ISO-8859-15',
'fullDateFormat'                                    => 'Y-m-d H:i:s',
...
'ALIST_META_DESCRIPTION_PREFIX'                     => "You are here:",
);
CODE
?>
<h4>Oxid importer information:</h4>
<table class="bdr more-padding">
<tr class="row-even">
    <td class="small">Author:</td>
    <td class="small">
        Stefan Krenz, Daniel Schlichtholz
    </td>
</tr>

<tr class="row-odd">
    <td class="small">Description:</td>
    <td class="small">
        This importer is meant to be used when importing language files from Oxid eShop.<br />
        It tries to extract the keys and values from the file.
    </td>
</tr>
<tr class="row-even">
    <td class="small">Structure that can be detected:</td>
    <td class="small">
        <pre><?php echo $this->out($code);?></pre>
    </td>
</tr>
<tr class="row-odd">
    <td class="small">Ignored constants:</td>
    <td class="small">
        The constant "charset" is ignored. The file must be encoded in utf8!<br />
    </td>
</tr>
    <tr class="row-even">
        <td class="small">Note:</td>
        <td class="small">
            If you discover character set problems, copy & paste the text into the text box instead of uploading it.
        </td>
    </tr>

</table>
