<div id="headline">
    <h2><?php echo $this->lang->L_START_ANALYZE;?>:</h2>
</div>
<p>
    <?php echo sprintf($this->lang->L_FOUND_X_KEYS, $this->numberFormat(sizeof($this->extractedData)));?>
    <br /><?php echo $this->lang->L_START_IMPORT_BY_CLICKING_BUTTON;?>
    <br /><br />
    <button type="button" class="Formbutton ui-corner-all" id="importButton">
    <?php echo $this->getIcon('save', $this->lang->L_IMPORT_TO_DATABASE);?> <?php echo $this->lang->L_IMPORT_TO_DATABASE;?>
    </button>
</p>

<table class="bdr more-padding" summary="Extracted key-value pairs">
<tr class="thead">
    <th><?php echo $this->lang->L_ACTION;?></th>
    <th class="right">#</th>
    <th><?php echo $this->lang->L_KEY;?></th>
    <th><?php echo $this->lang->L_VALUE;?></th>
</tr>
<?php
$cycleHelper = $this->cycle(array('row-even', 'row-odd'));
$i=1;
foreach ($this->extractedData as $key => $val) { ?>
    <tr class="<?php echo $cycleHelper->next();?> small">
        <td class="importLineHeight">
            <span id="<?php echo $key;?>" class="import"></span>
        </td>
        <td class="right"><?php echo $this->numberFormat($i);?>.</td>
        <td><?php echo $this->out($key);?></td>
        <td><?php echo $this->out($val);?></td>
    </tr>
<?php
    $i++;
}
?>
</table>
<div id="importInfo">
    <span class="headline"><?php echo $this->lang->L_IMPORT_STATUS;?>:</span>
    <table style="width:100%" class="small" summary="Import status">
        <tr>
            <td><?php echo $this->lang->L_KEYS_TOTAL;?>:</td>
            <td class="right"><?php echo sizeof($this->extractedData)?></td>
        </tr>
        <tr>
            <td><?php echo $this->lang->L_KEYS_PROCESSED;?>:</td>
            <td class="right"><span id="processed">0</span></td>
        </tr>
        <tr>
            <td><?php echo $this->lang->L_KEYS_TO_IMPORT;?>:</td>
            <td class="right"><span id="toImport"><?php echo sizeof($this->extractedData)?></span></td>
        </tr>
        <tr>
            <td><?php echo $this->lang->L_SAVED_SUCCESSFULLY;?>:</td>
            <td class="right"><span id="savedSuccessfully">0</span></td>
        </tr>
        <tr>
            <td><?php echo $this->lang->L_SKIPPED;?>:</td>
            <td class="right"><span id="skipped">0</span></td>
        </tr>
        <tr>
            <td><?php echo $this->lang->L_ERRORS;?>:</td>
            <td class="right"><span id="errors">0</span></td>
        </tr>
        <tr>
            <td><?php echo $this->lang->L_DONE;?>:</td>
            <td class="right"><span id="done">-</span></td>
        </tr>
    </table>
</div>
<?php
$this->jQuery()->onLoadCaptureStart();
?>
$('#importButton').click(function () {
    $('.import').each(function (index, domElement) {
        key = domElement.id;
        importValues.push(key);
    });
    $('#importButton').attr('disabled','disabled');
    doImport();
});
<?php   $this->jQuery()->onLoadCaptureEnd(); ?>
<script type="text/javascript">
//<![CDATA[
var importValues = new Array();
var imgLoader = '<?php echo $this->getIcon('ajax-loader','');?>';
var imgOk = '<?php echo $this->getIcon('Ok', $this->lang->L_SAVED_SUCCESSFULLY, 16);?>';
var imgError = '<?php echo $this->getIcon('Attention', $this->lang->L_ERROR_SAVING_KEY, 16);?>';
var imgNoEditRight = '<?php echo $this->getIcon('NotOk', $this->lang->L_YOU_ARE_NOT_ALLOWED_TO_EDIT_THIS_LANGUAGE, 16);?>';
var imgNoAddRight = '<?php echo $this->getIcon('NotOk', $this->lang->L_YOU_ARE_NOT_ALLOWED_TO_ADD_NEW_KEYS, 16);?>';
var imgSameContentAsFallbackLanguage = '<?php echo $this->getIcon('Attention', $this->lang->L_CONTENT_IS_THE_SAME_AS_IN_FALLBACK_LANGUAGE, 16);?>';
var keysToProcess = new Array();
var requestUrl = '<?php echo $this->baseUrl();?>/ajax/import.key/';

function doImport() {
    // get next keys
    keysToProcess = importValues.slice(0,15);
    // remove copied items from old array
    importValues.reverse();
    for (var i=0; i < keysToProcess.length;i++) {
        importValues.pop();
    }
    importValues.reverse();

    if (keysToProcess.length > 0) {
        // need to save some more keys -> show ajax loader
        $.each(keysToProcess, function () {
               $('#' + this).html(imgLoader);
            }
        );

        $.ajax({
            'type':'POST',
            'url':requestUrl,
            'data':{
                'languageId':<?php echo $this->language;?>,
                'fileTemplate':<?php echo $this->fileTemplate;?>,
                'keys': keysToProcess
            },
            'dataType':'json',
            'success':function(data) {
                if (data.length > 0) {
                    lastKey = '';
                    $.each(data, function () {
                        setState(this.key,this.result);
                        lastKey = this.key;
                    });
                    scrollToId(lastKey);
                    calcDone();
                    doImport();
                } else {
                    showError(data);
                }
            },
            error:function(error) {
                showError(error.responseText);
            }
        });
    } else {
        // show finish popup
        $('#importDone').dialog("open");
    }
}

function showError(error) {
    $('#requestError').html(error);
    $('#requestError').dialog("open");
}

function setState(id, state) {
    var content = '';
    switch (state) {
        case 1:
            content = imgOk;
            increase('savedSuccessfully');
            break;
        case 2:
            content = imgNoEditRight;
            increase('errors');
            break;
        case 3:
            content = imgNoAddRight;
            increase('errors');
            break;
        case 4:
            content = imgSameContentAsFallbackLanguage;
            increase('skipped');
            break;
        default:
            content = imgError;
            increase('errors');
            break;
    }
    $('#' + id).html(content);
    decrease('toImport');
    increase('processed');
}

function calcDone()
{
    var done = $('#processed').html();
    var total = <?php echo sizeof($this->extractedData);?>;
    var percentage = done * 100 / total;
    $('#done').html(Math.round(percentage) + '%');
}
/* for our "lovely" IE which gets confused and doesn't show the content if there are more than 903 language keys */
setPageActive();
//]]>
</script>
<?php
$this->jQuery()->onLoadCaptureStart();
$this->popUpMessage()->addMessage(
    'importDone',
    $this->lang->L_DONE,
    $this->lang->L_IMPORT_DONE,
    array(
        'modal' => true,
        'height' => 140,
        'width' => 440,
        'dialogClass' => 'info',
        'autoOpen' => false,
        'buttons' => array(
                        'L_EDIT_ENTRIES' => 'function() {
                                    $(this).dialog("close");
                                    window.location.href="'. $this->serverUrl() . $this->baseUrl().'/entries/index";
                                }',
                        'L_IMPORT_ANOTHER_FILE' => 'function() {
                            $(this).dialog("close");
                            window.location.href="'. $this->serverUrl() . $this->baseUrl().'/import/index";
                        }'
                    )
    )
);

$this->popUpMessage()->addMessage(
    'requestError',
    $this->lang->L_ERROR,
    $this->lang->L_ERROR_AJAX,
    array(
        'modal' => true,
        'height' => 450,
        'width' => 600,
        'dialogClass' => 'error',
        'autoOpen' => false,
        'buttons' => array(
                        'L_RETRY' => 'function() {
                                    $(this).dialog("close");
                                    doImport();
                                }'
                    )
    )
);
$this->jQuery()->onLoadCaptureEnd();
