<div>
<button type="button" class="Formbutton ui-corner-all" onclick="window.location.href='<?php echo $this->serverUrl() . $this->baseUrl();?>/import/index'">
    <?php echo $this->getIcon('OpenFile', $this->lang->L_IMPORT_ANOTHER_FILE, 16);?> <?php echo $this->lang->L_IMPORT_ANOTHER_FILE;?>
</button>
<button type="button" class="Formbutton ui-corner-all" onclick="window.location.href='<?php echo $this->serverUrl() . $this->baseUrl();?>/entries/index'">
    <?php echo $this->getIcon('Edit', $this->lang->L_EDIT_ENTRIES, 16);?> <?php echo $this->lang->L_EDIT_ENTRIES;?>
</button>
</div>