<h2>Import language data</h2>
<h4>Import settings:</h4>
<form enctype="multipart/form-data" action="<?php echo $this->baseUrl();?>/import/index" method="post" id="myForm"
    onsubmit="setPageInactive()">
<table class="bdr more-padding small" summary=""  style="margin-bottom:8px;">
    <tr class="row-even">
        <td>Data is for language:</td>
        <td>
            <select name="selectedLanguage" id="selectedLanguage" onchange="$('#myForm').submit()">
                <?php echo $this->selLanguage;?>
            </select>
        </td>
    </tr>
    <tr class="row-odd">
        <td>Extracted data is for file:</td>
        <td>
            <select name="selectedFileTemplate" id="selectedFileTemplate">
                <?php echo $this->selFileTemplate;?>
            </select>
        </td>
    </tr>
    <tr class="row-even">
        <td>Use analyzer:</td>
        <td>
            <select name="selectedAnalyzer" id="selectedAnalyzer" onchange="$('#myForm').submit()">
                <?php echo $this->selAnalyzer;?></select>
                <span style="float:right">
                    <a href="#" title="show info" id="showImporterInfo">
                        <?php echo $this->getIcon('Info', '', 16);?>
                    </a>
                </span>
        </td>
    </tr>

    <tr class="row-odd">
        <td>
            Upload a file:
        </td>
        <td>
            <input type="file" class="text" name="fileUploaded" id="fileUploaded" />
            <button type="submit" class="Formbutton">
            <?php echo $this->getIcon('OpenFile', '', 16);?> Upload file
            </button>
        </td>

    </tr>
</table>
<div class="invisible" style="display:none" id="importerInfo">
<?php
    echo $this->analyzer->getInfo($this);
    echo "<br />";
?>
</div>
<?php
if ($this->importData > '') { ?>
    <h4>Check characters!</h4>
    <p>
    If you discover "weird" looking characters you can try to convert them.<br />
    Selected a character set in the select box and hit the button "Convert data from".
    You can try different character sets until the text is ok.
    Each conversion is taken from the originally uploaded file.<br />
    If everything looks good, start to analyze the data.
    </p>
    <p>
        <button class="Formbutton" type="submit" name="convert">
        <?php echo $this->getIcon('Ok', 'Convert data', 16);?> Convert data from:
        </button>
        <select name="selectedCharset" id="selectedCharset">
            <?php echo $this->selCharset;?>
        </select>
    </p>
    <?php
} ?>
<h4>Data to analyze:</h4>
<p>
    <button class="Formbutton" type="submit" name="analyze">
    <?php echo $this->getIcon('Ok', 'Start analyzing data', 16);?> Start analyzing
    </button>
</p>

<p>
    <textarea name="importData" id="importData" cols="120" rows="1"><?php echo $this->importData;?></textarea>
    <br /><br />

    <button class="Formbutton" type="submit" name="analyze">
    <?php echo $this->getIcon('Ok', 'Start analyzing data', 16);?> Start analyzing
    </button>
</p>
</form>
<?php $this->jQuery()->onLoadCaptureStart();?>
$('#showImporterInfo').click(function () {
    $('#importerInfo').toggle('blind', {}, 1000);
});
$("textarea").autoGrow();
<?php
if (isset($this->conversionError)) {
    $this->popUpMessage()->addMessage(
        'conversionError',
        'Error',
        'Sorry, data couldn\'t be interpreted as ' . $this->targetCharset .'.',
        array(
            'modal' => true,
            'height' => 160,
            'width' => 260,
            'dialogClass' => 'error',
        )
    );
}
$this->jQuery()->onLoadCaptureEnd();?>
