<div id="headline">
    <h2><?php echo $this->lang->L_IMPORT;?></h2>
</div>
<h4><?php echo $this->lang->L_IMPORT_SETTINGS;?>:</h4>
<form enctype="multipart/form-data" action="<?php echo $this->baseUrl();?>/import/index" method="post" id="myForm"
    onsubmit="setPageInactive()">
<table class="bdr more-padding small" summary=""  style="margin-bottom:8px;">
    <tr class="row-even">
        <td class="vmiddle"><?php echo $this->lang->L_TARGET_LANGUAGE;?>:</td>
        <td>
            <select name="selectedLanguage" id="selectedLanguage" onchange="$('#myForm').submit()">
                <?php echo $this->selLanguage;?>
            </select>
        </td>
    </tr>
    <tr class="row-odd">
        <td class="vmiddle"><?php echo $this->lang->L_TARGET_FILE;?>:</td>
        <td>
            <select name="selectedFileTemplate" id="selectedFileTemplate">
                <?php echo $this->selFileTemplate;?>
            </select>
        </td>
    </tr>
    <tr class="row-even">
        <td class="vmiddle"><?php echo $this->lang->L_USE_ANALYZER;?>:</td>
        <td>
            <select name="selectedAnalyzer" id="selectedAnalyzer" onchange="$('#myForm').submit()">
                <?php echo $this->selAnalyzer;?></select>
                <span style="float:right">
                    <a href="#" title="show info" id="showImporterInfo">
                        <?php echo $this->getIcon('Info', '', 16);?>
                    </a>
                </span>
        </td>
    </tr>

    <tr class="row-odd">
        <td class="vmiddle"><?php echo $this->lang->L_UPLOAD_FILE;?>:</td>
        <td>
            <input type="file" class="text" name="fileUploaded" id="fileUploaded" />
            <button type="submit" class="Formbutton">
            <?php echo $this->getIcon('OpenFile', '', 16);?> <?php echo $this->lang->L_UPLOAD_FILE;?>
            </button>
        </td>

    </tr>
</table>
<div class="invisible" style="display:none" id="importerInfo">
<?php
    echo $this->analyzer->getInfo($this);
    echo "<br />";
?>
</div>
<?php
if ($this->importData > '') { ?>
    <h4><?php echo $this->lang->L_CHECK_CHARS;?></h4>
    <p><?php echo $this->lang->L_CHECK_CHARS_EXPLAIN;?></p>
    <p>
        <button class="Formbutton" type="submit" name="convert">
        <?php echo $this->getIcon('Ok', 'Convert data', 16);?> <?php echo $this->lang->L_CONVERT_CHARS_FROM;?>:
        </button>
        <select name="selectedCharset" id="selectedCharset">
            <?php echo $this->selCharset;?>
        </select>
    </p>
    <?php
} ?>
<h4><?php echo $this->lang->L_DATA_TO_ANALYZE;?>:</h4>
<p>
    <button class="Formbutton" type="submit" name="analyze">
    <?php echo $this->getIcon('Ok', $this->lang->L_START_ANALYZE, 16);?> <?php echo $this->lang->L_START_ANALYZE;?>
    </button>
</p>

<p>
    <textarea name="importData" id="importData" cols="120" rows="1"><?php echo $this->importData;?></textarea>
    <br /><br />

    <button class="Formbutton" type="submit" name="analyze">
    <?php echo $this->getIcon('Ok', $this->lang->L_START_ANALYZE, 16);?> <?php echo $this->lang->L_START_ANALYZE;?>
    </button>
</p>
</form>
<?php $this->jQuery()->onLoadCaptureStart();?>
$('#showImporterInfo').click(function () {
    $('#importerInfo').toggle('blind', {}, 1000);
});
$("textarea").autoGrow();
<?php
if (isset($this->conversionError)) {
    $this->popUpMessage()->addMessage(
        'conversionError',
        'Error',
        $this->jsEscape(sprintf($this->lang->L_ERROR_CONVERTING, $this->targetCharset)),
        array(
            'modal' => true,
            'height' => 160,
            'width' => 260,
            'dialogClass' => 'error',
        )
    );
}
$this->jQuery()->onLoadCaptureEnd();?>
