<table class="bdr" style="width:100%">
    <tr class="thead">
        <th colspan="2">Content of file <?php echo $this->filename; ?></th>
    </tr>
<?php
    if (is_array($this->fileContent)) {
        $highlightedCode = highlight_string(implode("", $this->fileContent), true);
            ?>
        <tr class="row-odd">
            <td class="code right"><?php echo (implode("<br/>", range(1, count($this->fileContent)))); ?></td>
            <td class="code nowrap"><?php echo str_replace("\t", '&nbsp;&nbsp;&nbsp;&nbsp;', $highlightedCode); ?></td>
        </tr>
<?php
    } else {
?><tr><td class="error" colspan="2"><?php echo $this->fileContent; ?></td></tr><?php
    }
?>
</table>
