<?php
$interfaceConfig = $this->config->getParam('interface');
$theme = $interfaceConfig['theme'];
?>
<h2>Browse exported files</h2>
<div id="treeBrowser">
    <table class="bdr" summary="Tree of files you can browse">
        <tr class="thead">
            <th colspan="2">Select a file:</th>
        </tr>
        <tr>
            <td id="fileTree" class="bdr"></td>
            <td class="nowrap"><div id="fileContent">Select a file</div></td>
        </tr>
    </table>
</div>
<?php
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/jquery/jquery.jstree.js');
?>
<script type="text/javascript">
<?php $this->jQuery()->onLoadCaptureStart(); ?>
    $.jstree._themes = '<?php echo $this->baseUrl() . '/css/' . $theme . '/jquery/jstree/themes/'; ?>';
    $('#fileTree').jstree({
        'plugins':['json_data','themes','ui'],
        'json_data':{
            'data':<?php echo json_encode($this->fileTree); ?>
        },
        'themes':{
            'theme':'tree'
        },
        'core':{
            'animation':250
        },
        'ui':{
            'select_limit':1
        }
    }).bind('loaded.jstree', function(event, data) {
    <?php if ($this->entryCount <= 30) { ?>
        data.inst.open_all(-1, true);
    <?php } ?>
    });
<?php
$this->jQuery()->onLoadCaptureEnd();
$this->jQuery()->javascriptCaptureStart();
?>
function loadFileContent(filename)
{
    setPageInactive();
    var requestUrl = '<?php echo $this->baseUrl();?>/browser/file/';
    $.ajax({
        'type':'POST',
        'url':requestUrl,
        'data':{
            'filename':filename
        },
        success:function(data) {
            $('#fileContent').html(data);
            setPageActive();
        },
        error:function(error) {
            $('#fileContent').html('Error with ajax request!');
            setPageActive();
        }
    });
}
<?php $this->jQuery()->javascriptCaptureEnd(); ?>
</script>
