<?php
$i = 1;
$projectConfig = $this->config->getParam('project');
?>
<h2>Configuration</h2>
<h4>You are allowed to edit:</h4>
<table class="bdr small" summary="List of languages you are allowed to edit">
    <tr class="thead">
        <th>#</th>
        <th colspan="3">Language</th>
    </tr>
<?php
    foreach ($this->editLanguages as $lang)
    {
        $langId = $lang;
        $langName = $this->languages[$langId]['name'];
        $langLocale = $this->languages[$langId]['locale'];
    ?>
        <tr class="<?php echo $this->cycle(array('row-even', 'row-odd'))->next();?>">
            <td class="right"><?php echo $i;?>.</td>
            <td>
                <?php echo $this->printFlag($langId);?>
            </td>
            <td><?php echo $langLocale;?></td>
            <td><?php echo $langName;?></td>
        </tr>
    <?php
        $i++;
    }
    ?>
</table>

<br />
<h4>Entries per page:</h4>
<form action="<?php echo $this->baseUrl();?>/settings/index" method="post">
<p>
    Select how many entries should be shown per page:
    <select name="recordsPerPage">
        <?php echo $this->selRecordsPerPage;?>
    </select>
    <button type="submit" class="Formbutton"><?php echo $this->getIcon('save', '');?> Save settings</button>
</p>
<h4>Select your reference language(s):</h4>
 <p>
    The selected languages will be shown as a reference when you edit a
    language variable.
    This should help you to easily translate the current variable.
</p>
<table class="bdr" summary="List of all languages you can select as a reference">
    <tr class="thead">
        <th>#</th>
        <th colspan="4">Language</th>
    </tr>
    <?php
    $i = 1;
    /**
     * @var Zend_View_Helper_Cycle $cycle
     */
    $cycle = $this->cycle(array('row-even', 'row-odd'));
    foreach ($this->languages as $key => $language)
    {
        $id = 'lang_'.$language['id'];
        $langId = $language['id'];
        $langName = $this->languages[$langId]['name'];
        $langLocale = $this->languages[$langId]['locale'];

    ?>
        <tr class="<?php echo $cycle->next();?>">
            <td class="right"><?php echo $i;?>.</td>
            <td>
                <label for="<?php echo $id;?>">
                    <?php echo $this->printFlag($key);?>
                </label>
            </td>
            <td>
                <label for="<?php echo $id;?>"><?php echo $langLocale;?></label>
            </td>
            <td>
                <label for="<?php echo $id;?>"><?php echo $langName;?></label>
            </td>
            <td>
                <input type="checkbox" class="checkbox" value="<?php echo $language['id']; ?>" name="selLangs[]" id="<?php echo $id;?>"
                <?php
                    if (in_array($key, $this->refLanguagesSelected)) {
                        echo ' checked="checked"';
                    }
                ?>
                />
            </td>
        </tr>
    <?php
        $i++;
    }
    ?>
</table>
<br />
<?php
if ($projectConfig['vcsActivated'] > 0) {
    ?>
<br />
<h4>Personal Version Control System (VCS) credentials:</h4>
    <p>
        Enter at least the username of your personal VCS credentials.
    </p>
<table class="bdr" summary="Credentials for VCS access.">
    <tr class="thead">
        <th colspan="2">VCS Credentials</th>
    </tr>
    <tr class="row-odd">
        <td><label for="vcsUser">Username:</label></td>
        <td><input type="text" class="text" name="vcsUser" id="vcsUser" value="<?php echo $this->vcsUser; ?>"/></td>
    </tr>
    <tr class="row-even">
        <td><label for="vcsPass">
                Password:<br />
                (* only enter if you want to change the current password)
            </label></td>
        <td><input type="password" class="text" name="vcsPass" id="vcsPass"/></td>
    </tr>
    <tr class="row-odd">
        <td><label for="vcsPass2">Confirm password:</label></td>
        <td><input type="password" class="text" name="vcsPass2" id="vcsPass2"/></td>
    </tr>
    <tr class="row-even">
        <td></td>
        <td><button type="button" onclick="$('#confirmVCDeletion').dialog('open');" class="Formbutton"><?php echo $this->getIcon('delete', ''); ?> Delete credentials</button></td>
    </tr>
</table>
<?php } ?>
<p>
    <br />
    <button type="submit" class="Formbutton"><?php echo $this->getIcon('save', '');?> Save settings</button>
    <br /><br />
</p>
</form>

<?php
$this->popUpMessage()->addMessage(
    'confirmVCDeletion',
    'Confirm delete of VCS credentials',
    'Are your sure, that you want delete your personal VCS credentials?',
    array(
        'modal' => true,
        'height' => 160,
        'width' => 260,
        'dialogClass' => 'info',
        'autoOpen' => false,
        'buttons' => array(
            'Yes' => 'function() { window.location.href="' . $this->baseUrl() . '/settings/delete-credentials/"; $(this).dialog("close"); }',
            'No' => 'function() { $(this).dialog("close"); }',
        ),
    )
);
if (isset($this->saved)) {
    if ($this->saved !== false) {
        $this->popUpMessage()->addMessage(
            'settingsSaved',
            'Success',
            'Your settings have been saved successfully.',
            array(
                'modal' => true,
                'height' => 160,
                'width' => 260,
                'dialogClass' => 'info',
            )
        );
    } else {
        $this->popUpMessage()->addMessage(
            'settingsNotSaved',
            'Error',
            'There was an error while saving your settings.<br>Please try again.',
            array(
                'modal' => true,
                'height' => 160,
                'width' => 260,
                'dialogClass' => 'info',
            )
        );
    }
};