<?php
$i = 1;
$projectConfig = $this->config->getParam('project');
echo $this->partial('settings/head-navi.phtml', array('lang' => $this->lang, 'vcsActivated' => $this->vcsActivated));
?>

<div id="headline">
    <h2><?php echo $this->lang->L_CONFIGURATION . ' - ' . $this->lang->L_GENERAL;?></h2>
</div>
<form action="<?php echo $this->baseUrl();?>/settings/index" method="post">
    <h4><?php echo $this->lang->L_INTERFACE_LANGUAGE;?>:</h4>

    <p>
        <?php echo $this->lang->L_SELECT_LANGUAGE_OF_INTERFACE;?>:
        <select name="interfaceLanguage">
            <?php echo $this->selInterfaceLanguage;?>
        </select>
    </p>

    <h4><?php echo $this->lang->L_ENTRIES_PER_PAGE;?>:</h4>

    <p>
        <?php echo $this->lang->L_SELECT_HOW_MANY_ENTRIES_SHOULD_BE_SHOWN_PER_PAGE;?>:
        <select name="recordsPerPage">
            <?php echo $this->selRecordsPerPage;?>
        </select>
    </p>
    <p>
        <button type="submit"
                class="Formbutton ui-corner-all"><?php echo $this->getIcon('save', '');?> <?php echo $this->lang->L_SAVE_SETTINGS;?></button>
    </p>
</form>
<div class="spacer"></div>

<?php
    ?>
    <div class="spacer"></div>
<?php
if (isset($this->saved)) {
    $this->showNotification(
        $this->saved,
        $this->lang->L_YOUR_SETTINGS_HAVE_BEEN_SAVED_SUCCESSFULLY,
        $this->lang->L_ERROR_SAVING_CHANGE . '.<br>' . $this->lang->L_TRY_AGAIN
    );
};
