<?php
$i = 1;
?>
<div id="content">
<h2>Configuration</h2>
<h4>You are allowed to edit:</h4>
<table class="bdr">
    <tr class="thead">
        <th>#</th>
        <th colspan="3">Language</th>
    </tr>
<?php
    foreach ($this->editLanguages as $lang)
    {
        $langId = $lang;
        $langName = $this->languages[$langId]['name'];
        $langLocale = $this->languages[$langId]['locale'];
    ?>
        <tr class="<?php echo $this->cycle(array('row-even', 'row-odd'))->next();?>">
            <td class="small right"><?php echo $i;?>.</td>
            <td class="small">
                <img src="<?php echo $this->baseUrl() . '/images/flags/' . $langLocale;?>.gif"
                     alt="<?php echo $langLocale;?>" title="<?php echo $langLocale;?>" width="25" height="15"/>
            </td>
            <td class="small"><?php echo $langLocale;?></td>
            <td class="small"><?php echo $langName;?></td>
        </tr>
    <?php
        $i++;
    }
    ?>
</table>

<br />
<h4>Entries per page:</h4>
<form action="<?php echo $this->baseUrl();?>/settings/index" method="post">
<p>
    Select how many entries should be shown per page:
    <select name="recordsPerPage">
        <?php echo $this->selRecordsPerPage;?>
    </select>
    <button type="submit" class="Formbutton"><?php echo $this->getIcon('save', '');?> Save settings</button>
</p>
<h4>Select your reference language(s):</h4>
 <p>
    The selected languages will be shown as a reference when you edit a
    language variable.
    This should help you to easily translate the current variable.
</p>
<table class="bdr">
    <tr class="thead">
        <th>#</th>
        <th colspan="4">Language</th>
    </tr>
    <?php
    $i=1;
    foreach ($this->languages as $key => $language)
    {
        $id = 'lang_'.$language['id'];
        $langId = $language['id'];
        $langName = $this->languages[$langId]['name'];
        $langLocale = $this->languages[$langId]['locale'];

    ?>
        <tr class="<?php echo$this->cycle(array('row-even', 'row-odd'))->next();?>">
            <td class="small right"><?php echo $i;?>.</td>
            <td class="small">
                <label for="<?php echo $id;?>">
                <img src="<?php echo $this->baseUrl() . '/images/flags/' . $langLocale;?>.gif"
                     alt="<?php echo $langLocale;?>" title="<?php echo $langLocale;?>" width="25" height="15"/>
                </label>
            </td>
            <td class="small">
                <label for="<?php echo $id;?>"><?php echo $langLocale;?></label>
            </td>
            <td class="small">
                <label for="<?php echo $id;?>"><?php echo $langName;?></label>
            </td>
            <td class="small">
                <input type="checkbox" class="checkbox" value="1" name="<?php echo $id;?>" id="<?php echo $id;?>"
                <?php
                    if (in_array($key, $this->refLanguagesSelected)) {
                        echo ' checked="checked"';
                    }
                ?>
                />
            </td>
        </tr>
    <?php
        $i++;
    }
    ?>
</table>
<p>
    <br />
    <button type="submit" class="Formbutton"><?php echo $this->getIcon('save', '');?> Save settings</button>
    <br /><br />
</p>
</form>
</div>

<?php
if (isset($this->saved)) {
    if ($this->saved !== false) {
        $this->popUpMessage()->addMessage(
            'settingsSaved',
            'Success',
            'Your settings have been saved successfully.',
            array(
                'modal' => true,
                'height' => 160,
                'width' => 260,
                'dialogClass' => 'info',
            )
        );
    } else {
        $this->popUpMessage()->addMessage(
            'settingsNotSaved',
            'Error',
            'There was an error while saving your settings.<br>Please try again.',
            array(
                'modal' => true,
                'height' => 160,
                'width' => 260,
                'dialogClass' => 'info',
            )
        );
    }
};