<tr class="thead">
   <th colspan="2"><?php echo $this->lang->L_ACCOUNT_SETTINGS;?></th>
</tr>
<tr class="row-odd">
    <td><?php echo $this->lang->L_USERACCOUNT_IS_ACTIVE;?>:</td>
    <td>
        <input type="radio" name="active" id="user_active_yes" value="1"
            <?php if ($this->userData['active'] == 1) { ?>
                checked="checked"
            <?php } ?>
        />
        <label for="user_active_yes"> <?php echo $this->lang->L_YES;?></label>
        &nbsp;&nbsp;
        <input type="radio" name="active" id="user_active_no" value="0"
            <?php if ($this->userData['active'] == 0) { ?>
                checked="checked"
            <?php } ?>
        />
        <label for="user_active_no"> <?php echo $this->lang->L_NO;?></label>
    </td>
</tr>

<tr class="row-even">
    <td><?php echo $this->lang->L_USERNAME;?>:</td>
    <td>
        <input type="text" class="text" name="username" id="username" value="<?php echo $this->out($this->userData['username']);?>"/><br/>
        <?php if (isset($this->errors['username'])) {?><span class="error"><?php echo implode('<br/>', $this->errors['username']); ?></span><?php } ?>
    </td>
</tr>

<tr class="row-odd">
    <td><?php echo $this->lang->L_PASSWORD;?> (*):</td>
    <td>
        <input type="password" class="text" name="pass1" id="pass1" value="" autocomplete="off"/><br/>
        <?php if (isset($this->errors['pass1'])) {?><span class="error"><?php echo implode('<br/>', $this->errors['pass1']); ?></span><?php } ?>
    </td>
</tr>

<tr class="row-even">
    <td><?php echo $this->lang->L_CONFIRM_PASSWORD;?> (*):</td>
    <td>
        <input type="password" class="text" name="pass2" id="pass2" value="" autocomplete="off"/>
    </td>
</tr>

<tr class="row-odd">
    <td colspan="2">
        <div class="confirm-password-explain">
            (*) <?php echo $this->lang->L_CONFIRM_PASSWORD_EXPLAIN;?>
        </div>
    </td>
</tr>
