<?php
$cycleHelper = $this->cycle(array('row-even', 'row-odd'));
?>
<tr class="thead">
    <th colspan="2"><?php echo $this->lang->L_ADMIN_RIGHTS;?></th>
</tr>

<?php
$rights = array(
    'admTabProject',
    'editProject',
    'editUsers',
    'addUser',
    'deleteUsers',
    'editLanguage',
    'addLanguage',
    'deleteLanguage',
    'editTemplate',
    'addTemplate',
    'editImporter',
    'editVcs',
    'editTlServices',
);

foreach ($rights as $right) {
    $rightDescription = 'L_RIGHT_EXPLAIN_' . strtoupper($right);
?>
    <tr class="<?php echo $cycleHelper->next();?>">
        <td colspan="2">
            <label for="<?php echo $right;?>" id="label-<?php echo $right;?>"
                class="switchRightLabel floatLeft" title="<?php echo $this->lang->L_CHANGE_RIGHT;?>">
                <?php echo $this->lang->$rightDescription;?>:
            </label>
            <div id="<?php echo $right;?>" class="switchRight right">
                <?php
                    echo $this->printStatusIcon(
                        !empty($this->userRights[$right]) && $this->userRights[$right] > 0,
                        $this->lang->L_CHANGE_RIGHT
                    );?>
            </div>
        </td>
    </tr>
<?php
}
