<?php
$i = 1;
$cycleHelper = $this->cycle(array('row-even', 'row-odd'));
?>
<table class="bdr more-padding small" style="float:left;" summary="List of editable languages">
    <tr class="thead">
        <th class="right">#</th>
        <th colspan="4">
            <div class="floatLeft"><?php echo $this->lang->L_LANGUAGE;?></div>
            <div class="right"><?php echo $this->lang->L_CAN_EDIT;?></div>
        </th>
    </tr>
    <?php
        foreach ($this->languages as $language) {
            $label = '<label for="lang-' . $language['id'] .'" class="switchLanguageEditRightLabel">';
            ?>
            <tr class="<?php echo $cycleHelper->next();?>">
                <td class="right vmiddle">
                    <?php echo $label . $this->numberFormat($i);?>.</label>
                </td>
                <td class="vmiddle">
                    <?php echo $label . $this->printFlag($language['id']);?></label>
                </td>
                <td class="vmiddle">
                    <?php echo $label . $language['locale'];?></label>
                </td>
                <td class="vmiddle"><?php echo $label . $language['name'];?></label></td>
                <td class="vmiddle">
                    <div id="lang-<?php echo $language['id'];?>" class="switchLanguageEditRight">
                        <?php
                            echo $this->printStatusIcon(
                                in_array($language['id'], $this->editLanguages),
                                $this->lang->L_CHANGE_RIGHT
                            );?>
                    </div>
                </td>
            </tr>
            <?php
            $i++;
        } ?>
</table>
<?php
$this->jQuery()->onLoadCaptureStart(); ?>
$('.switchLanguageEditRight').click(function() {
    var id = this.id.replace(/lang-/, '');
    $(this).html(imgAjax);
    $.ajax({
        type: 'POST',
        url: '<?php echo $this->serverUrl() . $this->baseUrl();?>/ajax/switch-language-edit-right',
        dataType: 'json',
        async : true,
        cache: false,
        data:{
            'languageId': id,
            'userId'    : <?php echo $this->userData['id'];?>
        },
        success:function(data) {
            $('#lang-' + id).html(data.icon);
        },
        error:function(error) {
            $('#lang-' + id).html(imgError);
        }
    });
});
$('.switchLanguageEditRightLabel').click(function() {
    var id = $(this).attr('for');
    $('#' + id).trigger('click');
});

<?php
$this->jQuery()->onLoadCaptureEnd();