<?php
$i = 1;
$cycleHelper = $this->cycle(array('row-even', 'row-odd'));
?>
<table class="bdr more-padding small" style="float:left;" summary="List of editable languages">
    <tr class="thead">
        <th class="right">#</th>
        <th colspan="3">Language</th>
        <th>Can edit</th>
        <th><?php echo $this->lang->L_STATUS;?></th>
    </tr>
    <?php
        foreach ($this->languages as $language) {
            $label = '<label for="lang-' . $language['id'] .'">';
        ?>
        <tr class="<?php echo $cycleHelper->next();?>">
            <td class="right">
                <?php echo $label . $this->numberFormat($i);?>.</label>
            </td>
            <td>
                <?php echo $label . $this->printFlag($language['id']);?></label>
            </td>
            <td>
                <?php echo $label . $language['locale'];?></label>
            </td>
            <td><?php echo $label . $language['name'];?></label></td>
            <td>
                <input type="checkbox" class="switchLanguageEditRight"
                    name="lang-<?php echo $language['id'];?>"
                    id="lang-<?php echo $language['id'];?>"
                    <?php if (in_array($language['id'], $this->editLanguages)) { ?>
                        checked="checked"
                    <?php };?>
                />
            </td>
            <td>
                <label for="lang-<?php echo $language['id'];?>"  id="img-<?php echo $language['id'];?>">
                    <?php
                        if (in_array($language['id'], $this->editLanguages)) {
                            echo $this->getIcon('Ok', $this->lang->L_YES, 16);
                        } else {
                            echo $this->getIcon('NotOk', $this->lang->L_NO, 16);
                        }
                    ;?>
                </label>
            </td>
        </tr>
        <?php
            $i++;
        } ?>
</table>
<?php
$this->jQuery()->onLoadCaptureStart(); ?>
var imgAjax  = '<?php echo $this->getIcon('ajax-loader');?>';
var imgError = '<?php echo $this->getIcon('NotOk', '', 16);?>';
$('.switchLanguageEditRight').change(function() {
    var languageId = this.id.replace(/lang-/, '');
    $('#img-' + languageId).html(imgAjax);
    $.ajax({
        type: 'POST',
        url: '<?php echo $this->serverUrl() . $this->baseUrl();?>/ajax/switch-language-edit-right' ,
        dataType: 'json',
        async : true,
        cache: false,
        data:{
            'languageId': languageId,
            'userId'    : <?php echo $this->userData['id'];?>
        },
        success:function(data) {
            $('#img-' + languageId).html(data.icon);
        },
        error:function(error) {
            $('#img-' + languageId).html(imgError);
        }
    });
});
<?php
$this->jQuery()->onLoadCaptureEnd();