<?php
$cycleHelper = $this->cycle(array('row-even', 'row-odd'));
?>
<tr class="thead">
    <th colspan="2"><?php echo $this->lang->L_MENUE_RIGHTS;?></th>
</tr>

<?php
$menueRights = array(
    'editConfig',
    'showEntries',
    'showConnector',
    'showDownloads',
    'showBrowseFiles',
    'showImport',
    'showExport',
    'showLog',
    'showStatistics',
    'admin',
    'editTlServices',
);

foreach ($menueRights as $right) {
    $rightDescription = 'L_RIGHT_EXPLAIN_' . strtoupper($right);
?>
    <tr class="<?php echo $cycleHelper->next();?>">
        <td colspan="2">
            <label title="<?php echo $this->lang->L_CHANGE_RIGHT;?>" for="<?php echo $right;?>" id="label-<?php echo $right;?>"
                class="switchRightLabel floatLeft">
                <?php echo $this->lang->$rightDescription;?>:
            </label>
        <div title="<?php echo $this->lang->L_CHANGE_RIGHT;?>" id="<?php echo $right;?>" class="switchRight right">
            <?php
                echo $this->printStatusIcon(
                    !empty($this->userRights[$right]) && $this->userRights[$right] > 0,
                    $this->lang->L_CHANGE_RIGHT
                );?>
        </div>
        </td>
    </tr>
<?php
}
