<div id="headline">
    <h2><?php echo $this->lang->L_ADMIN;?> - <?php echo $this->lang->L_VCS;?></h2>
</div>
<?php
echo $this->partial('admin/head-navi.phtml', array('lang' => $this->lang));
$projectConfig = $this->config->getParam('project');
$cycleHelper = $this->cycle(array('row-even', 'row-odd'));
?>
<h4><?php echo $this->lang->L_VCS_SETTINGS;?>:</h4>
<form action="" method="post" id="exportConfigForm">
    <table class="bdr more-padding" summary="Set fallback language">
        <tr class="thead">
            <th colspan="2"><?php echo $this->lang->L_VCS;?></th>
        </tr>
        <tr class="<?php echo $cycleHelper->next();?>">
            <td><?php echo $this->lang->L_PROJECT_USES_VCS;?>:</td>
            <td>
                <input type="radio" name="vcsActivated" id="vcs_active_yes" value="1"
                    <?php if ($projectConfig['vcsActivated'] == 1) { ?>
                        checked="checked"
                    <?php } ?>
                />
                <label for="vcs_active_yes"> <?php echo $this->lang->L_YES;?></label>
                &nbsp;&nbsp;
                <input type="radio" name="vcsActivated" id="vcs_active_no" value="0"
                    <?php if ($projectConfig['vcsActivated'] == 0) { ?>
                        checked="checked"
                    <?php } ?>
                />
                <label for="vcs_active_no"> <?php echo $this->lang->L_NO;?></label>
            </td>
        </tr>

        <tr class="<?php echo $cycleHelper->next(); ?>">
            <td><?php echo $this->lang->L_VCS_REVERT_BEFORE_UPDATE; ?></td>
            <td>
                <input type="radio" id="vcsRevertBeforeUpdateYes" name="vcsRevertBeforeUpdate" value="1"<?php if ($this->vcsConfig['revertBeforeUpdate'] == 1) { ?> checked="checked"<?php } ?>/>
                <label for="vcsRevertBeforeUpdateYes"> <?php echo $this->lang->L_YES;?></label>
                &nbsp;&nbsp;
                <input type="radio" id="vcsRevertBeforeUpdateNo" name="vcsRevertBeforeUpdate" value="0"<?php if ($this->vcsConfig['revertBeforeUpdate'] == 0) { ?> checked="checked"<?php } ?>/>
                <label for="vcsRevertBeforeUpdateNo"> <?php echo $this->lang->L_NO;?></label>
            </td>
        </tr>

        <tr class="<?php echo $cycleHelper->next(); ?>">
            <td><?php echo $this->lang->L_VCS_COPY_TO_CHECKOUT_PATH; ?></td>
            <td>
                <input type="radio" id="vcsCopyToCOPathYes" name="vcsCopyToCOPath" value="1"<?php if ($this->vcsConfig['copyToCOPath'] == 1) { ?> checked="checked"<?php } ?>/>
                <label for="vcsCopyToCOPathYes"> <?php echo $this->lang->L_YES;?></label>
                &nbsp;&nbsp;
                <input type="radio" id="vcsCopyToCOPathNo" name="vcsCopyToCOPath" value="0"<?php if ($this->vcsConfig['copyToCOPath'] == 0) { ?> checked="checked"<?php } ?>/>
                <label for="vcsCopyToCOPathNo"> <?php echo $this->lang->L_NO;?></label>
            </td>
        </tr>

        <tr class="<?php echo $cycleHelper->next();?>">
            <td><label for="vcsAdapter"><?php echo $this->lang->L_CURRENT_VCS_ADAPTER;?>:</label></td>
            <td>
                <select name="vcsAdapter" id="vcsAdapter" onchange="$('#exportConfigForm').submit();">
                <?php foreach ($this->vcsAvailAdapter as $vcsAdapter) {
                    $isSeleted = (bool) (strtolower($vcsAdapter) == strtolower($this->vcsConfig['adapter']));
                ?>
                    <option value="<?php echo $vcsAdapter; ?>"<?php echo $isSeleted ? ' selected="selected"' : ''; ?>><?php echo str_replace('_', ' ', $vcsAdapter); ?></option>
                <?php } ?>
                </select>
            </td>
        </tr>
        <tr class="<?php echo $cycleHelper->next();?>">
            <td><label for="vcsCommitMessage"><?php echo $this->lang->L_COMMIT_MESSAGE;?>:</label></td>
            <td><input type="text" class="text width300" name="vcsCommitMessage" id="vcsCommitMessage" value="<?php echo $this->vcsConfig['commitMessage']; ?>" /></td>
        </tr>
        <tr class="thead">
            <th colspan="2"><?php echo $this->lang->L_VCS_ADAPTER_OPTIONS;?></th>
        </tr><?php
        foreach ($this->vcsAdapterParams as $optionName => $optionDisplayName) {
            if (isset($this->vcsConfig['options'][$optionName])) {
                $optionValue = $this->vcsConfig['options'][$optionName];
            } else {
                $optionValue = '';
            }
            ?>
            <tr class="<?php echo $cycleHelper->next(); ?>">
                <td><label for="options_<?php echo $optionName; ?>"><?php echo $optionDisplayName; ?></label></td>
                <td><?php
                        if (stripos($optionName, 'password') !== false) { ?>
                            <input type="password" class="text width300" name="vcsOptions[<?php echo $optionName; ?>]" id="options_<?php echo $optionName; ?>" value="<?php echo $optionValue; ?>" /><?php
                        } else { ?>
                            <input type="text" class="text width300" name="vcsOptions[<?php echo $optionName; ?>]" id="options_<?php echo $optionName; ?>" value="<?php echo $optionValue; ?>" /><?php
                        }
                    ?>
                </td>
            </tr>
            <?php
        } ?>
        <tr class="<?php echo $cycleHelper->next(); ?>">
            <td>&nbsp;</td>
            <td><button type="submit" class="Formbutton ui-corner-all" name="saveButton"><?php echo $this->getIcon('save'); ?> <?php echo $this->lang->L_SAVE;?></button></td>
        </tr>
    </table>
</form>
<?php
$this->jQuery()->addOnLoad('$("textarea").autoGrow();');
if (isset($this->saved)) {
    $this->showNotification(
        $this->saved,
        $this->lang->L_YOUR_SETTINGS_HAVE_BEEN_SAVED_SUCCESSFULLY,
        $this->lang->L_ERROR_SAVING_CHANGE . '.<br>' . $this->lang->L_TRY_AGAIN
    );
}
