<?php
$userData = $this->userData;
$userRights = $this->userRights;
$inputNamesMap = array(
    'user_name' => 'Username',
    'pass1'     => 'Password',
);
?>
<div id="headline">
    <h2><?php echo $this->lang->L_ADMIN . ' - ' . $this->lang->L_EDIT_USER;?></h2>
</div>
<?php
echo $this->partial('admin/head-navi.phtml', array('lang' => $this->lang));
if ($userData['id'] == 0) { ?>
    <h4><?php echo $this->lang->L_CREATE_NEW_USER_ACCOUNT;?></h4>
<?php
} else { ?>
    <h4><?php echo sprintf($this->lang->L_ACCOUNT_OF_USER_WITH_ID, $userData['id']);?></h4>
<?php } ?>

<form action="<?php echo $this->baseUrl() . '/admin_users/edit/id/' . $userData['id'];?>" method="post">
<table class="bdr more-padding small" style="float:left;margin: 0 12px 12px 0;" summary="User account settings">
<?php
echo $this->partial(
    'admin/users/edit/account-settings.phtml',
    array(
        'userData' => $userData,
        'errors'   => $this->errors,
        'lang'     => $this->lang
    )
);
?>
    <tr class="row-even">
        <td>&nbsp;</td>
        <td>
            <button type="submit" class="Formbutton ui-corner-all" name="saveAccount">
                <?php echo $this->getIcon('save', ''). ' ' . $this->lang->L_SAVE;?>
            </button>
        </td>
    </tr>
<?php
if ($userData['id'] > 0) {
    echo $this->partial('admin/users/edit/menu-rights.phtml',
        array('userRights' => $userRights, 'lang' => $this->lang)
    );
    echo $this->partial('admin/users/edit/general-rights.phtml',
        array('userRights' => $userRights, 'lang' => $this->lang)
    );
    echo $this->partial('admin/users/edit/admin-rights.phtml',
        array('userRights' => $userRights, 'lang' => $this->lang)
    );
}
?>
</table>
<?php
if ($userData['id'] > 0) {
    echo $this->partial('admin/users/edit/languages.phtml',
            array(
                'languages'     => $this->languages,
                'editLanguages' => $this->editLanguages,
                'userData'      => $userData,
                'lang'          => $this->lang,
            )
        );
}
?>
</form>
<?php
if (!empty($this->errors)) {
    $inputErrors = '<table>';
    foreach ($this->errors as $inputName => $inputError) {
        if (array_key_exists($inputName, $inputNamesMap)) {
            $inputName = $inputNamesMap[$inputName];
        }
        $inputErrors .= '<tr><td class="error">' . $inputName . ':</td><td class="error">'
            . implode('<br/>', $inputError) . '</td></tr>';
    }
    $inputErrors .= '</table>';
    $this->popUpMessage()->addMessage(
        'settingsNotSaved',
        $this->lang->L_ERROR,
        $this->lang->L_ERROR_VALIDATING_INPUTS . ':<br /><br />' . $inputErrors
            . '<br /><br />' . $this->lang->L_PLEASE_CORRECT_INPUT .'.',
        array(
            'modal' => true,
            'width' => 400,
            'dialogClass' => 'info',
        )
    );
};

if (isset($this->saved)) {
    $this->showNotification(
        $this->saved,
        $this->lang->L_SAVED_SUCCESSFULLY . '.',
        $this->lang->L_SAVED_UNSUCCESSFULLY . '!'
    );
}
$this->jQuery()->onLoadCaptureStart();
if ($this->user->hasRight('addUser')) { ?>
    $('.switchRight').click(function() {
        var id = this.id;
        $(this).html(imgAjax);
        $.ajax({
            type: 'POST',
            url: '<?php echo $this->serverUrl() . $this->baseUrl();?>/ajax/switch-right' ,
            dataType: 'json',
            async : true,
            cache: false,
            data:{
                'right' : this.id,
                'userId': <?php echo $this->userData['id'];?>
            },
            success:function(data) {
                $('#' + id).html(data.icon);
            },
            error:function(error) {
                $('#' + id).html(imgError);
            }
        });
    });
    $('.switchRightLabel').click(function() {
        var id = this.id.replace(/label-/, '');
        $('#' + id).trigger('click');
    });<?php
} else {
    // user doesn't have the right to edit user rights
    $this->popUpMessage()->addMessage(
        'notAllowed',
        $this->lang->L_ERROR,
        $this->lang->L_YOU_ARE_NOT_ALLOWED_TO_CHANGE_THIS_RIGHT,
        array(
            'modal' => true,
            'autoOpen' => false,
            'width' => 250,
            'dialogClass' => 'info',
        )
    ); ?>
    $('.switchRight').click(function() {
        $('#notAllowed').dialog("open");
    });
    $('.switchRightLabel').click(function() {
        $('#notAllowed').dialog("open");
    });

<?php
}
$this->jQuery()->onLoadCaptureEnd();
