<?php
$user = $this->user;
$userRights = $this->userRights;
$inputNamesMap = array(
    'user_name' => 'Username',
    'pass1' => 'Password',
);
?>
<h2>Admin - Edit User</h2>
<?php
echo $this->partial('admin/head-navi.phtml', array('userRights' => $userRights));
if ($user['id'] == 0) { ?>
    <h4>Create new user account</h4>
<?php
} else { ?>
    <h4>Account of user with id <?php echo $user['id'];?></h4>
<?php } ?>

<form action="<?php echo $this->baseUrl() . '/admin_users/edit/id/' . $user['id'];?>" method="post">
<table class="bdr more-padding small" style="float:left;margin: 0 12px 12px 0;" summary="User account settings">
<?php
echo $this->partial('admin/users/edit/account-settings.phtml',
        array('user' => $user, 'errors' => $this->errors)
    );

echo $this->partial('admin/users/edit/menu-rights.phtml',
        array('userRights' => $userRights)
    );
echo $this->partial('admin/users/edit/general-rights.phtml',
        array('userRights' => $userRights)
    );
?>

    <tr class="row-even">
        <td>&nbsp;</td>
        <td>
            <button type="submit" class="Formbutton" name="saveAccount">
                <?php echo $this->getIcon('save', '');?> Save
            </button>
        </td>
    </tr>
</table>
<?php
echo $this->partial('admin/users/edit/languages.phtml',
        array('languages' => $this->languages, 'editLanguages' => $this->editLanguages)
    );
?>
</form>
<?php
if (!empty($this->errors)) {
    $inputErrors = '<table>';
    foreach ($this->errors as $inputName => $inputError) {
        if (array_key_exists($inputName, $inputNamesMap)) {
            $inputName = $inputNamesMap[$inputName];
        }
        $inputErrors .= '<tr><td class="error">' . $inputName . '</td><td class="error">'
            . implode('<br/>', $inputError) . '</td></tr>';
    }
    $inputErrors .= '</table>';
    $this->popUpMessage()->addMessage(
        'settingsNotSaved',
        'Error',
        'Error validating your inputs:<br /><br /><span class="error">' . $inputErrors
            .'</span><br /><br />Please correct your input.',
        array(
            'modal' => true,
            'height' => 200,
            'width' => 360,
            'dialogClass' => 'info',
        )
    );
};

if (isset($this->saveMessage) && $this->saveMessage === true) {
    $this->popUpMessage()->addMessage(
        'settingsSaved',
        'Ok',
        'Your changes have been saved successfully.',
        array(
            'modal' => true,
            'height' => 130,
            'width' => 340,
            'dialogClass' => 'info',
        )
    );
};

if (isset($this->saveErrorMessage)) {
    $this->popUpMessage()->addMessage(
        'settingsSaved',
        'Error',
        'An error occured while saving your changes.<br />Please try again.',
        array(
            'modal' => true,
            'height' => 170,
            'width' => 340,
            'dialogClass' => 'info',
        )
    );
}
