<h2>Admin - Users</h2>
<?php
echo $this->partial('admin/head-navi.phtml');
?>
<form action="<?php echo $this->baseUrl();?>/admin_users/" method="post" id="myForm">
<?php
echo $this->partial('/helper/search-users.phtml', array(
        'user'              => $this->user,
        'filterUser'        => $this->filterUser,
        'hits'              => $this->hits,
        'offset'            => $this->offset,
        'recordsPerPage'    => $this->recordsPerPage,
        'selRecordsPerPage' => $this->selRecordsPerPage
    )
);

?>
</form>

<table class="bdr small" summary="Userlist">
    <tr class="thead">
        <th>&nbsp;</th>
        <th>#</th>
        <th>Id</th>
        <th>Username</th>
        <th>Active</th>
        <th>Can edit</th>
    </tr>
<?php

$i = 1;
if ($this->hits == 0) { ?>
    <tr class="row-odd">
        <td colspan="6" class="error">Sorry, no hits.</td>
    </tr>

<?php
}
foreach ($this->users as $userId => $user)
{
    $i += $this->offset;
    $cycleHelper = $this->cycle(array('row-even', 'row-odd'));
    $edit = '<a href="'.$this->baseUrl().'/admin_users/edit/id/'.$userId .'" title="Edit user">';
    ?>
    <tr class="<?php echo $cycleHelper->next();?>">
        <td>
            <?php echo $edit . $this->getIcon('Edit', '');?></a>
            <?php if ($this->user->hasRight('deleteUsers')) { ?>
                <a href="#" id="deleteUser-<?php echo $userId;?>" class="deleteUser" title="Delete user">
                    <?php echo $this->getIcon('delete', '');?>
                </a>
            <?php } ?>
        </td>
        <td class="right">
            <?php echo $this->numberFormat($i);?>.
        </td>
        <td class="right">
            <?php echo $user['id'];?>
        </td>
        <td><?php echo $edit . $user['username'];?></a></td>
        <td>
            <div id="img-<?php echo $userId;?>" class="switchUserEditRight">
                <?php
                    if ($user['active'] == 1) {
                        echo $this->getIcon('Ok', $this->lang->L_YES, 16);
                    } else {
                        echo $this->getIcon('NotOk', $this->lang->L_NO, 16);
                    };
                ?>
            </div>
        </td>
        <td>
            <?php
                $languageEditRights = $this->userModel->getUserLanguageRights($userId, false);
                if (empty($languageEditRights)) {
                    echo '<i>Nothing</i>';
                }
            ?>
            <table summary="Flags of edit languages">
            <tr>
                <?php
                foreach ($languageEditRights as $langId) {
                if (isset($this->languages[$langId])) {
                ?>
                    <td>
                        <?php echo $this->printFlag($langId, 20);?>
                    </td>
                    <td><?php echo $this->languages[$langId]['locale'];?></td>
                    <td><?php echo $this->languages[$langId]['name'];?></td>
            <?php
                }
            } ?>
            </tr>
            </table>
        </td>
    </tr>
    <?php
    $i++;
}
?>
</table>
<div id="confirmDeleteUser" style="display:none">
    Are you really sure you want to delete this user?<br />
    This will also remove all rights, settings and log entries of this user.
</div>
<script type="text/javascript">
<?php $this->jQuery()->onLoadCaptureStart(); ?>
$('.deleteUser').click(function() {
    var a=this;
    $('#confirmDeleteUser').dialog({
        autoOpen: true,
        modal: true,
        title: 'Really delete?',
        width: 380,
        height: 160,
        buttons : {
                    "Yes, delete user": function() {
                        var id = a.id.replace(/deleteUser-/, '');
                        $('#deleteUser').attr('value', id);
                        $('#myForm').submit();
                    },
                    "Cancel": function() {
                        $(this).dialog("close");
                    }
                  }
    })
});
$('.switchUserEditRight').click(function() {
    var userId = this.id.replace(/img-/, '');
    $('#img-' + userId).html(imgAjax);
    $.ajax({
        type: 'POST',
        url: '<?php echo $this->serverUrl() . $this->baseUrl();?>/ajax/switch-user-status' ,
        dataType: 'json',
        async : true,
        cache: false,
        data:{
            'userId'    : userId
        },
        success:function(data) {
            $('#img-' + userId).html(data.icon);
        },
        error:function(error) {
            $('#img-' + userId).html(imgError);
        }
    });
});
<?php
if (isset($this->userDeleted)) {
    if ($this->userDeleted == true) {
        $this->popUpMessage()->addMessage(
            'userDeleted',
            'Success',
            'The user has been deleted successfully.<br />All log entries, settings and rights have been removed too.',
            array(
                'modal' => true,
                'height' => 160,
                'width' => 340,
                'dialogClass' => 'info',
            )
        );
    } else {
        $this->popUpMessage()->addMessage(
            'userDeleted',
            'Error',
            'There was an error deleting this user.<br />Please try again.',
            array(
                'modal' => true,
                'height' => 140,
                'width' => 340,
                'dialogClass' => 'info',
            )
        );

    }
}
$this->jQuery()->onLoadCaptureEnd(); ?>
</script>
