<div id="headline">
    <h2><?php echo $this->lang->L_ADMIN;?> - <?php echo $this->lang->L_USERS;?></h2>
</div>
<?php
echo $this->partial('admin/head-navi.phtml', array('lang' => $this->lang));
?>
<form action="<?php echo $this->baseUrl();?>/admin_users/" method="post" id="myForm">
<?php
echo $this->partial('/helper/search-users.phtml', array(
        'lang'              => $this->lang,
        'user'              => $this->user,
        'filterUser'        => $this->filterUser,
        'hits'              => $this->hits,
        'offset'            => $this->offset,
        'recordsPerPage'    => $this->recordsPerPage,
        'selRecordsPerPage' => $this->selRecordsPerPage
    )
);
?>
</form>

<table class="bdr small" summary="Userlist">
    <tr class="thead">
        <th>&nbsp;</th>
        <th>#</th>
        <th><?php echo $this->lang->L_ID;?></th>
        <th><?php echo $this->lang->L_USERNAME;?></th>
        <th><?php echo $this->lang->L_NAME;?></th>
        <th><?php echo $this->lang->L_STATUS;?></th>
        <th><?php echo $this->lang->L_EDITED;?></th>
        <th><?php echo $this->lang->L_LATEST_ACTIVITY;?></th>
        <th><?php echo $this->lang->L_CAN_EDIT;?></th>
    </tr>
<?php

$i = 1;
if ($this->hits == 0) { ?>
    <tr class="row-odd">
        <td colspan="6" class="error"><?php echo $this->lang->L_NO_HITS;?>.</td>
    </tr>

<?php
}
foreach ($this->users as $userId => $user)
{
    $i += $this->offset;
    $cycleHelper = $this->cycle(array('row-even', 'row-odd'));
    $edit = '<a href="'.$this->baseUrl().'/admin_users/edit/id/'.$userId .'" title="' . $this->lang->L_EDIT_USER . '">';
    $userLog = '<a href="'.$this->baseUrl().'/log/index/filterUser/'.$userId .'" title="' . $this->lang->L_LOG . '">';
    ?>
    <tr class="<?php echo $cycleHelper->next();?>">
        <td class="vmiddle nowrap">
            <?php echo $edit . $this->getIcon('Edit', $this->lang->L_EDIT);?></a>
            <?php if ($this->user->hasRight('deleteUsers')) { ?>
                <a href="#" id="deleteUser-<?php echo $userId;?>" class="deleteUser" title="<?php echo $this->lang->L_DELETE_USER;?>">
                    <?php echo $this->getIcon('delete', '');?>
                </a>
            <?php } ?>
        </td>
        <td class="right vmiddle">
            <?php echo $edit . $this->numberFormat($i);?>.</a>
        </td>
        <td class="right vmiddle">
            <?php echo $edit . $user['id'];?></a>
        </td>
        <td class="vmiddle"><?php echo $edit . $user['username'];?></a></td>
        <td class="vmiddle"><?php echo $edit . $user['realName'];?></a></td>
        <td class="vmiddle">
            <div id="img-<?php echo $userId;?>" class="switchUserEditRight">
                <?php
                    if ($user['active'] == 1) {
                        echo $this->getIcon('Ok', $this->lang->L_CHANGE_STATUS, 16);
                    } else {
                        echo $this->getIcon('NotOk', $this->lang->L_CHANGE_STATUS, 16);
                    };
                ?>
            </div>
        </td>
        <td class="vmiddle right">
            <?php
                if (isset($this->userStatistics[$userId])) {
                    echo $userLog . $this->numberFormat($this->userStatistics[$userId]['editActions']) . '</a>';
                } else {
                    echo '-';
                } ?>
        </td>
        <td class="vmiddle">
            <?php
                if (isset($this->userStatistics[$userId])) {
                    echo $userLog . $this->userStatistics[$userId]['lastAction'] . '</a>';
                } else {
                    echo '-';
                } ?>
        </td>
        <td class="vmiddle">
            <?php $languageEditRights = $this->userModel->getUserLanguageRights($userId, false);?>
            <table summary="Flags of edit languages">
            <tr>
                <?php
                if (empty($languageEditRights)) { ?>
                    <td class="vmiddle"><?php echo $this->getIcon('NotOk', $this->lang->L_NOTHING, 16);?></td>
                    <?php
                } else {
                    foreach ($languageEditRights as $langId) {
                        if ($this->user->hasRight('editLanguage')) {
                            $editLang = '<a href="' . $this->baseUrl() . '/admin_languages/edit/id/'.$langId .'" title="' . $this->lang->L_EDIT_LANGUAGE .'">';
                            $editLangClose = '</a>';
                        } else {
                            $editLang = '';
                            $editLangClose = '';
                        }
                        if (isset($this->languages[$langId])) { ?>
                            <td class="vmiddle">
                                <?php echo $editLang . $this->printFlag($langId, 20) . $editLangClose?>
                            </td>
                            <td class="vmiddle">
                                <?php echo $editLang . $this->languages[$langId]['locale'] . $editLangClose;?>
                            </td>
                            <td class="vmiddle">
                                <?php echo $editLang . $this->languages[$langId]['name'] . $editLangClose;?>
                            </td>
                            <?php
                        }
                    }
                }?>
            </tr>
            </table>
        </td>
    </tr>
    <?php
    $i++;
}
?>
</table>
<div id="confirmDeleteUser" style="display:none">
    <?php echo $this->lang->L_REALLY_DELETE_USER;?><br />
    <?php echo $this->lang->L_THIS_WILL_ALSO_REMOVE_RIGHTS_SETTINGS_AND_LOG_ENTRIES;?>
</div>
<script type="text/javascript">
<?php $this->jQuery()->onLoadCaptureStart(); ?>
$('.deleteUser').click(function() {
    var a=this;
    $('#confirmDeleteUser').dialog({
        autoOpen: true,
        modal: true,
        title: '<?php echo $this->jsEscape($this->lang->L_CONFIRM_DELETE_TITLE);?>',
        width: 380,
        height: 160,
        buttons : {
                    '<?php echo $this->jsEscape($this->lang->L_CONFIRM_DELETE_USER);?>': function() {
                        var id = a.id.replace(/deleteUser-/, '');
                        $('#deleteUser').attr('value', id);
                        $('#myForm').submit();
                    },
                    '<?php echo $this->lang->L_CANCEL;?>': function() {
                        $(this).dialog("close");
                    }
                  }
    })
});
$('.switchUserEditRight').click(function() {
    var userId = this.id.replace(/img-/, '');
    $('#img-' + userId).html(imgAjax);
    $.ajax({
        type: 'POST',
        url: '<?php echo $this->serverUrl() . $this->baseUrl();?>/ajax/switch-user-status' ,
        dataType: 'json',
        async : true,
        cache: false,
        data:{
            'userId'    : userId
        },
        success:function(data) {
            $('#img-' + userId).html(data.icon);
        },
        error:function(error) {
            $('#img-' + userId).html(imgError);
        }
    });
});
<?php
$this->jQuery()->onLoadCaptureEnd(); ?>
</script>
<?php
if (isset($this->userDeleted)) {
    $this->showNotification(
        $this->userDeleted,
        $this->lang->L_USER_DELETED_SUCCESSFULLY . '<br />'. $this->lang->L_ALSO_REMOVED_LOG_ENTRIES_SETTINGS_AND_RIGHTS,
        $this->lang->L_ERROR_DELETING_USER . '<br />' . $this->lang->L_TRY_AGAIN,
        6000
    );
}
