<div id="headline">
    <h2><?php echo $this->lang->L_ADD_ENTRY;?></h2>
</div>
<form action="<?php echo $this->baseUrl();?>/entries/add-variable" method="post">
    <table class="bdr">
        <tr class="thead">
            <th colspan="2"><?php echo $this->lang->L_ADD_NEW_KEY;?></th>
        </tr>
        <tr class="row-odd">
            <td>
                <label for="var"><?php echo $this->lang->L_NAME;?>:</label>
            </td>
            <td>
                <input type="text" style="width:400px;" id="var" class="text" name="var" value="<?php echo $this->escape($this->newVar);?>" />
            </td>
        </tr>
        <tr class="row-even">
            <td>
                <label for="fileTemplate">
                    <?php echo $this->lang->L_SELECT_ASSIGNED_FILE_TEMPLATE;?>:
                </label>
            </td>
            <td>
                <?php echo $this->printFileTemplateHtml($this->fileTemplateSelected); ?>
            </td>
        </tr>
        <tr class="row-odd">
            <td>&nbsp;</td>
            <td><button type="submit" class="Formbutton ui-corner-all" value="Save" name="save"><?php echo $this->getIcon('save', '');?> <?php echo $this->lang->L_SAVE;?></button>
                <button type="submit" class="Formbutton ui-corner-all" value="Cancel" name="cancel"><?php echo $this->getIcon('delete', '');?> <?php echo $this->lang->L_CANCEL;?></button>
            </td>
        </tr>
    </table>
</form>
<?php
$this->jQuery()->addOnLoad("$('#var').focus();");
if (isset($this->error)) {
    $this->showNotification(false, '', $this->error);
}