<?php
$this->jQuery()->addJavascriptFile($this->baseUrl('/js/jquery/jeip.js'));
$viewData = array(
    'config'               => $this->config,
    'referenceLanguages'   => $this->referenceLanguages,
    'languages'            => $this->languages,
    'languagesEdit'        => $this->languagesEdit,
    'entry'                => $this->entry,
    'translatable'         => $this->translatable,
    'user'                 => $this->user,
    'lang'                 => $this->lang,
    'key'                  => $this->key,
    'langStatus'           => $this->langStatus,
    'skipKeysOffsets'      => $this->skipKeysOffsets,
    'assignedFileTemplate' => $this->assignedFileTemplate,
);
?>
<h2><?php echo $this->lang->L_EDIT_ENTRY;?></h2>
<h4><?php echo $this->lang->L_EDIT;?>: <?php echo $this->key['key'];?></h4>
<div>
    <a href="<?php echo $this->baseUrl();?>/entries/index" class="Formbutton">
        <?php echo $this->getIcon('Back', $this->lang->L_BACK, 16) . ' ' . $this->lang->L_BACK;?>
    </a>
</div>

<div style="float:left;margin-right:20px;">
    <?php echo $this->partial('entries/edit/edit-languages.phtml', $viewData); ?>
</div>
<div style="float:left">
    <?php echo $this->partial('entries/edit/reference-languages.phtml', $viewData);?>
</div>
<script type="text/javascript">
<?php $this->jQuery()->onLoadCaptureStart();?>
    $("textarea").autoGrow();
    $('.copy').click(function (e) {
        copyLang(e);
    });
    $('.translate').click(function (e) {
        translate(e);
    });
<?php if (isset($this->entrySaved)) { ?>
    $('#saveMessage').delay(200).fadeIn(800).delay(2000).fadeOut(800);
<?php
}
if ($this->user->hasRight('editKey')) { ?>
    $('.inlineEdit').eip('<?php echo $this->serverUrl() . $this->baseUrl();?>/ajax/save-key-name/', {
        saving_text: '<?php echo $this->lang->L_SAVING . '... ' . $this->getIcon('ajax-loader');?>',
        savebutton_text: '<?php echo $this->lang->L_SAVE;?>',
        savebutton_class: 'Formbutton',
        cancelbutton_text: '<?php echo $this->lang->L_CANCEL;?>',
        cancelbutton_class: 'Formbutton',
        mouseover_class: 'inlineEditMouseOver',
        editfield_class: 'inlineEditField',
        size: 'auto',
        form_buttons: '<span><button type="button" id="save-#{id}" class="#{savebutton_class}"><?php echo $this->getIcon('save');?> #{savebutton_text}</button> <button id="cancel-#{id}" class="#{cancelbutton_class}"><?php echo $this->getIcon('cancel');?>  #{cancelbutton_text}</button></span><br /><br />'
    });
    $('.inlineEditTrigger').click(function() {
        var id = $(this).attr('for');
        $('#' + id).trigger('click');
    });

<?php } ?>
function copyLang(event) {
    var lang = event.target.id;
    lang = lang.substr(5);
    lang = lang.split('-');
    $('#edit-'+lang[1]).val($('#textarea-'+lang[0]).val());
    $('#edit-'+lang[1]).focus();
}

function translate(event) {
    var lang = event.target.id;
    lang = lang.substr(10);
    lang = lang.split('-');
    var sourceLang = lang[0];
    var targetLang = lang[1];
    setPageInactive();
    $.ajax({
        url: '<?php echo $this->baseUrl();?>/ajax/translate/key/<?php echo $this->key['id'];?>/source/'+sourceLang+'/target/'+targetLang,
        dataType : 'HTML',
        success: function(response) {
            $('#edit-'+lang[1]).val(response.trim());
            $('#edit-'+lang[1]).focus();
            setPageActive();
        },
        error: function() {
            $('#edit-'+lang[1]).val('Error: ' + response);
            $('#edit-'+lang[1]).focus();
            setPageActive();
        }
    });
}
<?php $this->jQuery()->onLoadCaptureEnd();?>
</script>
<?php
// show notification bar after saving action
if (isset($this->entrySaved)) {
    $notificationClass='ok';
    if ($this->entrySaved == true) {
        $notificationContent = $this->getIcon('Ok','',16) . ' ' . $this->lang->L_SAVED_SUCCESSFULLY . '.';
    } else {
        $notificationClass='error';
        $notificationContent = $this->getIcon('Attention','',16) .' ' . $this->lang->L_SAVED_UNSUCCESSFULLY . '!';
    }
    ?>
    <div id="saveMessage" class="notification-bar <?php echo $notificationClass;?>">
            <?php echo $notificationContent;?>
    </div>
    <?php
}
?>
