<?php
$this->jQuery()->addJavascriptFile($this->baseUrl('/js/jquery/jeip.js'));
$i            = $this->offset+1;
$currentPage  = ceil(($this->offset + 1) / $this->recordsPerPage);
$nrOfPages    = ceil($this->rows / $this->recordsPerPage);
$entriesModel = new Application_Model_LanguageEntries();
$fileTemplateHelper = $this->printFileTemplateHtml(
    $this->fileTemplateFilter,
    array(
        'name'     => 'fileTemplateFilter',
        'id'       => 'fileTemplateFilter',
        'onchange' => "setPageInactive();resetOffset();$('#myForm').submit();",
    ),
    false,
    true
);
?>
<div id="headline">
    <h2><?php echo $this->lang->L_EDIT_ENTRIES;?></h2>
</div>

<form action="<?php echo $this->baseUrl();?>/entries/index" method="post" id="myForm">
    <table class="bdr morepadding" summary="Filter and find values">
        <tr>
            <td class="vmiddle">
                <input type="hidden" id="offset" name="offset" value="<?php echo $this->offset;?>" />
                <span id="searchInTranslations"><?php echo $this->lang->L_SEARCH_IN_TRANSLATIONS;?>:</span>
            </td>
            <td>
                <input
                    <?php if (false && $this->getUntranslated > 0) {
                        echo ' disabled="disabled"';
                    }?>
                type="text" class="text" id="filterValues" name="filterValues" value="<?php echo $this->escape($this->filterValues);?>" onchange="resetOffset()"/>
                <?php
                    // we have one file template - add value as hidden input
                    if (substr($fileTemplateHelper, 0, 7) == '<option') {
                        echo $fileTemplateHelper;
                    };
                ?>
            </td>
            <td>
                <button type="submit" class="Formbutton ui-corner-all" id="buttonFilterValuesSearch" value="Search" onclick="resetOffset();">
                    <?php echo $this->getIcon('Search', '', 16);?> <?php echo $this->lang->L_SEARCH;?>
                </button>
            </td>
            <td>
                <button type="submit" class="Formbutton ui-corner-all" id="buttonFilterValuesReset" onclick="$('#filterValues').val('');resetOffset();">
                    <?php echo $this->getIcon('delete', '');?> <?php echo $this->lang->L_RESET;?>
                </button>
            </td>
        </tr>
        <tr>
            <td class="vmiddle">
                <span id="searchInKeys"><?php echo $this->lang->L_SEARCH_IN_KEYS;?>:</span>
            </td>
            <td>
                <input
                    <?php if (false && $this->getUntranslated > 0) {
                        echo ' disabled="disabled"';
                    }?>
                type="text" class="text" id="filterKeys" name="filterKeys" value="<?php echo $this->escape($this->filterKeys);?>" onchange="resetOffset()"/>
            </td>
            <td>
                <button type="submit" class="Formbutton ui-corner-all" id="buttonFilterKeysSearch" value="Search" onclick="resetOffset();">
                    <?php echo $this->getIcon('Search', '', 16);?> <?php echo $this->lang->L_SEARCH;?>
                </button>
            </td>
            <td>
                <button type="submit" class="Formbutton ui-corner-all" id="buttonFilterKeysReset" onclick="$('#filterKeys').val('');resetOffset();">
                    <?php echo $this->getIcon('delete', '');?> <?php echo $this->lang->L_RESET;?>
                </button>
            </td>
        </tr>
        <?php
            // we have more than 1 file template - echo select list
            if (substr($fileTemplateHelper, 0, 7) == '<select') { ?>
                <tr>
                    <td class="vmiddle">
                        <label for="fileTemplateFilter"><?php echo $this->lang->L_FILTER_BY_FILE_TEMPLATE;?>:</label>
                    </td>
                    <td>
                        <?php echo $fileTemplateHelper; ?>
                    </td>
                    <td>&nbsp;</td>
                    <td>
                        <button type="submit" class="Formbutton ui-corner-all" id="buttonFileTemplateReset" onclick="resetOffset();$('#fileTemplateFilter option[value=\'0\']').attr('selected', true);">
                            <?php echo $this->getIcon('delete', '');?> <?php echo $this->lang->L_RESET;?>
                        </button>
                    </td>
                </tr>
            <?php } ?>
        <tr>
            <td class="vmiddle"><?php echo $this->lang->L_FIND_UNTRANSLATED;?>:</td>
            <td>
                <select class="select" id="getUntranslated" name="getUntranslated" onchange="setPageInactive();resetOffset();$('#myForm').submit();">
                    <option value="0">---</option>
                    <?php echo $this->selLanguage;?>
                </select>
            </td>
            <td>
                <button type="submit" class="Formbutton ui-corner-all" value="Search" onclick="resetOffset();">
                    <?php echo $this->getIcon('Search', '', 16);?> <?php echo $this->lang->L_SEARCH;?>
                </button>
            </td>
            <td>
                <button type="submit" class="Formbutton ui-corner-all" onclick="resetOffset();$('#getUntranslated option[value=\'0\']').attr('selected', true);">
                    <?php echo $this->getIcon('delete', '');?> <?php echo $this->lang->L_RESET;?>
                </button>
            </td>
        </tr>
    </table>
    <div class="top-margin">
        <?php
        if ($this->user->hasRight('addVar')) { ?>
             <button type="submit" class="Formbutton ui-corner-all" name="addVar" value="addVar">
                 <?php echo $this->getIcon('plus', '');?> <?php echo $this->lang->L_ADD_NEW_KEY;?>
             </button>
        <br/><br/>
            <?php
        }
        echo $this->partial('entries/index/browse-bar.phtml', array(
                'user'              => $this->user,
                'lang'              => $this->lang,
                'offset'            => $this->offset,
                'recordsPerPage'    => $this->recordsPerPage,
                'selRecordsPerPage' => $this->selRecordsPerPage,
                'rows'              => $this->rows,
            )
        );
        ?>
        <span style="padding:0;margin:0;">|
            <?php echo $this->lang->L_ENTRIES_PER_PAGE;?>:
            <select name="recordsPerPage" onchange="setPageInactive();resetOffset();$('#myForm').submit();">
                <?php echo $this->selRecordsPerPage;?>
            </select>
        </span>
        <?php if ((int) $this->fileTemplateFilter > 0) { ?>
            <br /><span><?php echo $this->lang->L_FILE_TEMPLATE . ': ' . $this->printFileTemplate($this->fileTemplateFilter);?></span>
            <br /><br /><?php
        }?>
    </div>
</form>

<table class="bdr small" summary="List of entries">
    <tr class="thead">
        <?php
            if ($this->user->hasRight('addVar')) { ?>
                <th>&nbsp;</th><?php
            } ?>
        <th>#</th>
        <?php
            if ($this->fileTemplateFilter == "0") { ?>
                <th><?php echo $this->lang->L_FILE_TEMPLATE;?></th><?php
            }
            if ($this->user->hasRight('editKey')) { ?>
                <th colspan="2"><?php echo $this->lang->L_KEY;?></th><?php
            } else { ?>
                <th><?php echo $this->lang->L_KEY;?></th><?php
            }
            foreach ($this->showLanguages as $lang) { ?>
                <th colspan="2" class="nowrap">
                    <?php
                        echo $this->printFlag($lang, 16).'&nbsp;';
                        echo $this->languages[$lang]['name'];
                    ?>
                </th><?php
            }
        ?>
    </tr>
    <?php
    foreach ($this->hits as $hit)
    {
        $keyId = $hit['id'];
        $cycleHelper = $this->cycle(array('row-even', 'row-odd'));
        $edit = '<a>';
        if (sizeof($this->languagesEdit) > 0) {
            $edit = '<a name="lang-' . $lang. '" href="'.$this->baseUrl().'/entries/edit/id/'.$keyId .'" title="' . $this->lang->L_EDIT . '">';
        }
        $editTemplate = $edit;
        if ($this->user->hasRight('addTemplate')) {
            $editTemplate = '<a href="'.$this->baseUrl().'/admin_files/edit/id/'. $hit['template_id'] .'" title="' . $this->lang->L_EDIT . '">';
        } ?>

        <tr class="<?php echo $cycleHelper->next();?>">

        <?php
        if ($this->user->hasRight('addVar')) {
            $delete = '<a href="#" title="' . $this->lang->L_DELETE_KEY . '" onclick="deleteVar(\''
                        . $keyId . '\',\''
                        . $hit['key'] . '\');">'; ?>
            <td class="top nowrap">
                <?php
                    echo $edit . $this->getIcon('Edit') . '</a>&nbsp;';
                    echo $delete;
                ?>
                <img src="<?php echo $this->getIconSrc('delete');?>" style="padding-top:2px;" alt="" height="10" width="10"/>
                </a>
            </td>
                 <?php
                }
            ?>
            <td class="right top">
                <?php echo $this->numberFormat($i);?>.
            </td>
            <?php if ($this->fileTemplateFilter == "0") { ?>
                <td class="ssmall nowrap top">
                    <?php echo $editTemplate . $this->printFileTemplate($hit['template_id']);?></a>
                </td><?php
            }
            if ($this->user->hasRight('editKey')) { ?>
                <td class="ssmall nowrap top">&nbsp;
                    <?php if ($this->user->hasRight('editKey')) { ?>
                        <label for="key-<?php echo $hit['id'];?>" class="inlineEditKeyTrigger">
                            <?php echo $this->getIcon('Edit', $this->lang->L_CLICK_TO_INLINE_EDIT);?>
                        </label>
                    <?php } ?>
                </td>
            <?php } ?>

            <td class="ssmall nowrap top">
                <?php if ($this->user->hasRight('editKey')) { ?>
                <div class="inlineEditKey" id="key-<?php echo $hit['id'];?>" title="<?php echo $this->lang->L_CLICK_TO_INLINE_EDIT;?>"><?php echo $hit['key'];?></div>
                <?php } else { ?>
                    <?php echo $edit . $hit['key'];?></a>
                <?php } ?>
            </td>
            <?php
            foreach ($this->showLanguages as $lang) {
                $text = isset($hit['languages'][$lang]) ? $hit['languages'][$lang] : '';
                $text = htmlspecialchars($text, ENT_COMPAT,'utf-8');
                if (!isset($text) || $text == '') {
                    $text = '<i>' . $this->lang->L_UNTRANSLATED . '</i>';
                }
                if (in_array($lang, $this->languagesEdit)) { ?>
                    <td class="top">
                        <label for="key-<?php echo $hit['id'] . '-' . $lang;?>" id="lkey-<?php echo $hit['id'] . '-' . $lang;?>" class="inlineEditValueTrigger">
                            <?php echo $this->getIcon('Edit', $this->lang->L_CLICK_TO_INLINE_EDIT);?>
                        </label>
                    </td>
                    <td class="top">
                            <span id="key-<?php echo $hit['id'] . '-' . $lang;?>" class="inlineEditValue">
                                <?php echo $edit.$text;?></a>
                            </span>
                    </td>
                    <?php
                } else {
                    echo '<td colspan="2" class="top">'. $text .'</td>';
                }
            }
            ?>
        </tr>
    <?php
    $i++;
    }
    // no hits found
    if ($this->rows == 0) {
        $rowCount = 5 + count($this->languagesEdit) + count($this->showLanguages);
        if ($this->user->hasRight('addVar')) {
            $rowCount++;
        } ?>
        <tr class="row-odd">
            <td colspan="<?php echo $rowCount;?>">
                <br /><?php echo $this->lang->L_NO_HITS;?><br />
                <?php echo $this->lang->L_SELECT_OTHER_FILTER_CRITERIA;?>.
                <br /><br />
            </td>
        </tr><?php
    }
?>
</table>

<div class="top-margin">
<?php
    echo $this->partial('entries/index/browse-bar.phtml', array(
            'user'              => $this->user,
            'lang'              => $this->lang,
            'offset'            => $this->offset,
            'recordsPerPage'    => $this->recordsPerPage,
            'selRecordsPerPage' => $this->selRecordsPerPage,
            'rows'              => $this->rows,
        )
    );
?>
</div>
<div id="confirmDeleteVar" style="display:none"></div>
<script type="text/javascript">
/* <![CDATA[ */
function deleteVar(id, name)
{
    var message = '<?php echo $this->jsEscape($this->lang->L_CONFIRM_DELETE_KEY_X)?>';
    var text = message.replace(/{KEY}/g, name);
    $('#confirmDeleteVar').html(text);
    $('#confirmDeleteVar').dialog({
        autoOpen: true,
        modal: true,
        title: '<?php echo $this->jsEscape($this->lang->L_CONFIRM_DELETE_TITLE);?>',
        buttons : {
                    '<?php echo $this->lang->L_OK;?>': function() {
                        setPageInactive();
                        self.location.href = '<?php echo $this->baseUrl();?>/entries/delete/id/'+id;
                    },
                    '<?php echo $this->lang->L_CANCEL;?>': function() {
                        $(this).dialog("close");
                    }
                  }
    })
}

function showErrorMsg(msg) {
    $('#notify').remove();
    var notify = '<div id="notify" class="notification-bar error"><?php echo $this->getIcon('Attention', '', 16);?> ' + msg + '</div>';
    $('body').append(notify);
    $('#notify').delay(200).fadeIn(600).delay(2500).fadeOut(600);
}

function showOkMsg() {
    $('#notify').remove();
    var notify = '<div id="notify" class="notification-bar ok"><?php echo $this->getIcon('Ok', '', 16) . ' ' . $this->lang->L_CHANGES_SAVED_SUCCESSFULLY;?>' + '</div>';
    $('body').append(notify);
    $('#notify').delay(200).fadeIn(600).delay(1500).fadeOut(600);
}
<?php $this->jQuery()->onLoadCaptureStart();?>

/* register click event for key edit icons */
$('.inlineEditKeyTrigger').click(function(e) {
    $('#' + $(this).attr('for')).trigger('click');
});

/* register click event for value edit icons */
$('.inlineEditValueTrigger').click(function(e) {
    var id = $(this).attr('for');
    // remove link
    var oldHtml = $('#' + id).html();
    var editText = $('#' + id + ' a').html();
    if (editText == '<i><?php echo $this->jsEscape($this->lang->L_UNTRANSLATED);?></i>') {
        editText = '';
    }
    $('#' + id).html(editText);

    /* register inline edit */
    $('#' + id).eip('<?php echo $this->serverUrl() . $this->baseUrl();?>/ajax/save-translation/', {
        saving_text: '<?php echo $this->lang->L_SAVING . '... ' . $this->getIcon('ajax-loader');?>',
        savebutton_text: '<?php echo $this->lang->L_SAVE;?>',
        savebutton_class: 'Formbutton',
        cancelbutton_text: '<?php echo $this->lang->L_CANCEL;?>',
        cancelbutton_class: 'Formbutton',
        mouseover_class: 'inlineEditMouseOver',
        editfield_class: 'textarea-inlineedit',
        data: { oldHtml: oldHtml, id: id},
        size: 'auto',
        form_type: 'textarea',
        form_buttons: '<span><button type="button" id="save-#{id}" class="#{savebutton_class}"><?php echo $this->getIcon('save');?> #{savebutton_text}</button> <button id="cancel-#{id}" class="#{cancelbutton_class}"><?php echo $this->getIcon('cancel');?>  #{cancelbutton_text}</button></span><br /><br />',
        on_error: function(msg) {
            removeTrigger(this);
            showErrorMsg(msg);
        },
        after_save: function(data) {
            showOkMsg();
            removeTrigger(this);
        },
        on_cancel: function() {
            removeTrigger(this);
        }
    });

    $('#' + id).trigger('click');
    $(window).scrollTop($('#l' + id).position().top);
});

/* Unbind click event, restore old edit link and replace link text with the new one */
function removeTrigger(obj) {
    $('#' + obj.data.id).unbind('click');
    var newText = $('#' + obj.data.id).html();
    if (newText == '') {
        newText = '<i><?php echo $this->jsEscape($this->lang->L_UNTRANSLATED);?></i>';
    }
    // replace text in old link
    $('#' + obj.data.id).html(obj.data.oldHtml);
    $('#' + obj.data.id + ' a').html(newText);

}

/* Add/remove optical inline edit class when hovering edit icons */
$('.inlineEditValueTrigger, .inlineEditKeyTrigger').hover(function(e) {
        $('#' + $(this).attr('for')).addClass('inlineEditMouseOver');
    },
    function() {
        $('#' + $(this).attr('for')).removeClass('inlineEditMouseOver');
    }
);

$('.inlineEditKey').eip('<?php echo $this->serverUrl() . $this->baseUrl();?>/ajax/save-key-name/', {
    saving_text: '<?php echo $this->lang->L_SAVING . '... ' . $this->getIcon('ajax-loader');?>',
    savebutton_text: '<?php echo $this->lang->L_SAVE;?>',
    savebutton_class: 'Formbutton',
    cancelbutton_text: '<?php echo $this->lang->L_CANCEL;?>',
    cancelbutton_class: 'Formbutton',
    mouseover_class: 'inlineEditMouseOver',
    editfield_class: 'inlineEditField',
    size: 'auto',
    form_buttons: '<span><button type="button" id="save-#{id}" class="#{savebutton_class}"><?php echo $this->getIcon('save');?> #{savebutton_text}</button> <button id="cancel-#{id}" class="#{cancelbutton_class}"><?php echo $this->getIcon('cancel');?>  #{cancelbutton_text}</button></span><br /><br />',
    on_error: function(msg) {
        showErrorMsg(msg);
    },
    after_save: function() {
        showOkMsg();
    }
});

var disabledElements = [
    'searchInTranslations', 'searchInKeys',
    'filterValues', 'buttonFilterValuesSearch', 'buttonFilterValuesReset',
    'filterKeys', 'buttonFilterKeysSearch', 'buttonFilterKeysReset'
];
/* if "get untranslated filter" is used -> disable other inputs */
if ($('#getUntranslated option:selected').val() > 0) {
    $.each(disabledElements, function(){
        var domElement = $('#' + this);
        domElement.css('opacity', 0.4);
        domElement.attr('disabled', true);
    });
}

// re-enable form inputs on submit for not losing provided inputs */
$('#myForm').on('submit', function() {
    $.each(disabledElements, function(){
        $('#' + this).attr('disabled', false);
    });
});
<?php $this->jQuery()->onLoadCaptureEnd();?>
/* ]]> */
</script>
<?php
if (isset($this->keyDeleted)) {
    $this->showNotification(
        $this->keyDeleted,
        $this->lang->L_KEY_DELETED_SUCCESSFULLY . '.',
        $this->lang->L_ERROR_DELETING_KEY . '!'
    );
}
