<?php
$this->jQuery()->addJavascriptFile($this->baseUrl('/js/jquery/jeip.js'));
$i = $this->offset+1;
$currentPage = ceil(($this->offset + 1) / $this->recordsPerPage);
$nrOfPages = ceil($this->rows / $this->recordsPerPage);
$entriesModel = new Application_Model_LanguageEntries();
?>
<h2>Edit entries</h2>

<form action="<?php echo $this->baseUrl();?>/entries/index" method="post" id="myForm">
        <table class="bdr morepadding" summary="Filter and find values">
            <tr>
                <td>
                    <input type="hidden" id="offset" name="offset" value="<?php echo $this->offset;?>" />
                    Search in phrases:
                </td>
                <td>
                    <input
                        <?php if (false && $this->getUntranslated > 0) {
                            echo ' disabled="disabled"';
                        }?>
                    type="text" class="text" id="filterValues" name="filterValues" value="<?php echo $this->escape($this->filterValues);?>" onchange="resetOffset()"/>
                </td>
                <td>
                    <button type="submit" class="Formbutton" value="Search" onclick="resetOffset();">
                        <?php echo $this->getIcon('search', '', 16);?> Search
                    </button>
                </td>
                <td>
                    <button type="submit" class="Formbutton" onclick="$('#filterValues').val('');resetOffset();">
                        <?php echo $this->getIcon('delete', '');?> Reset
                    </button>
                </td>
            </tr>
            <tr>
                <td>Search in keys:</td>
                <td>
                    <input
                        <?php if (false && $this->getUntranslated > 0) {
                            echo ' disabled="disabled"';
                        }?>
                    type="text" class="text" id="filterKeys" name="filterKeys" value="<?php echo $this->escape($this->filterKeys);?>" onchange="resetOffset()"/>
                </td>
                <td>
                    <button type="submit" class="Formbutton" value="Search" onclick="resetOffset();">
                        <?php echo $this->getIcon('search', '', 16);?> Search
                    </button>
                </td>
                <td>
                    <button type="submit" class="Formbutton" onclick="$('#filterKeys').val('');resetOffset();">
                        <?php echo $this->getIcon('delete', '');?> Reset
                    </button>
                </td>
            </tr>
            <tr>
                <td>
                    <label for="fileTemplateFilter">Filter by file template:</label>
                </td>
                <td>
                    <select class="select" name="fileTemplateFilter" id="fileTemplateFilter" onchange="setPageInactive();resetOffset();$('#myForm').submit();">
                        <?php echo $this->selFileTemplate;?>
                    </select>
                </td>
                <td>&nbsp;</td>
                <td>
                    <button type="submit" class="Formbutton" onclick="resetOffset();$('#fileTemplateFilter option[value=\'0\']').attr('selected', true);">
                        <?php echo $this->getIcon('delete', '');?> Reset
                    </button>
                </td>
            </tr>
            <tr>
                <td>Find untranslated for:</td>
                <td>
                    <select class="select" id="getUntranslated" name="getUntranslated" onchange="setPageInactive();resetOffset();$('#myForm').submit();">
                        <option value="0">---</option>
                        <?php echo $this->selLanguage;?>
                    </select>
                </td>
                <td>
                    <button type="submit" class="Formbutton" value="Search" onclick="resetOffset();">
                        <?php echo $this->getIcon('search', '', 16);?> Search
                    </button>
                </td>
                <td>
                    <button type="submit" class="Formbutton" onclick="resetOffset();$('#getUntranslated option[value=\'0\']').attr('selected', true);">
                        <?php echo $this->getIcon('delete', '');?> Reset
                    </button>
                </td>
            </tr>
        </table>

    <p style="margin:12px 0 0 0">
        <?php
        if ($this->user->hasRight('addVar')) { ?>
             <button type="submit" class="Formbutton" name="addVar" value="addVar">
                 <?php echo $this->getIcon('plus', '');?> Add new key
             </button>
        <br/><br/>
            <?php
        }
            ?>
        <a href="#" <?php if($this->offset > 0): ?> title="Shortcut ALT+C"
            onclick="mySubmit('offset', '<?php echo $this->offset-$this->recordsPerPage;?>');"
            accesskey="c" class="Formbutton"><?php echo $this->getIcon('Back', '', 16);?>
            <?php else: ?>
            class="Formbutton"><?php echo $this->getIcon('BackDisabled', '', 16);?>
            <?php endif; ?>
        </a>

        <a href="#" <?php if($this->offset + $this->recordsPerPage < $this->rows): ?> title="Shortcut ALT+V"
            onclick="mySubmit('offset', '<?php echo $this->offset+$this->recordsPerPage;?>');"
            accesskey="v" class="Formbutton"><?php echo $this->getIcon('Forward', '', 16);?>
            <?php else: ?>
            class="Formbutton"><?php echo $this->getIcon('ForwardDisabled', '', 16);?>
            <?php endif; ?>
        </a>
        Page <?php echo $currentPage; ?> of <?php echo $nrOfPages; ?> | Hits: <?php echo $this->numberFormat($this->rows);?>
        <span style="padding:0;margin:0;">|
            Entries per page:
            <select name="recordsPerPage" onchange="setPageInactive();resetOffset();$('#myForm').submit();">
                <?php echo $this->selRecordsPerPage;?>
            </select>
        </span>
    </p>
</form>
<?php
if (empty($this->showLanguages)) {
    echo "<div class=\"error\">You are not allowed to edit any language. Please contact the administrator.</div></div>";
    return;
}
?>
<table class="bdr small" summary="List of entries">
    <tr class="thead">
        <?php
            if ($this->addVar) {
                echo '<th>&nbsp;</th>';
            }
            ?>
        <th>#</th>
        <th><?php echo $this->lang->L_FILE_TEMPLATE;?></th>
        <?php if ($this->user->hasRight('editKey')) { ?>
            <th colspan="2"><?php echo $this->lang->L_KEY;?></th>
        <?php } else { ?>
            <th><?php echo $this->lang->L_KEY;?></th>
        <?php } ?>
        <?php
            foreach ($this->showLanguages as $lang) {
        ?>
                <th colspan="2" class="nowrap">
                    <?php
                        echo $this->printFlag($lang, 16).'&nbsp;';
                        echo $this->languages[$lang]['name'];
                    ?>
                </th>
        <?php
            }
        ?>
    </tr>
<?php
foreach ($this->hits as $hit)
{
    $keyId = $hit['id'];
    $cycleHelper = $this->cycle(array('row-even', 'row-odd'));
    $edit = '<a href="'.$this->baseUrl().'/entries/edit/id/'.$keyId .'" title="Edit language variable" class="tooltip">';
    ?>
    <tr class="<?php echo $cycleHelper->next();?>">
        <?php
            if ($this->user->hasRight('addVar')) {
                $delete = '<a href="#" title="Delete language variable" class="tooltip" onclick="deleteVar(\''
                            . $keyId . '\',\''
                            . $hit['key'] . '\');">';
            ?>
            <td>
                <?php echo $delete;?>
                <img src="<?php echo $this->getIconSrc('delete');?>" style="padding-top:2px;" alt="" height="10" width="10"/>
                </a>
            </td>
             <?php
            }
        ?>
        <td class="right top">
            <?php echo $this->numberFormat($i);?>.
        </td>
        <td class="ssmall nowrap top">
            <?php echo $edit . $this->printFileTemplate($hit['template_id']);?></a>
        </td>
        <?php if ($this->user->hasRight('editKey')) { ?>
            <td class="ssmall nowrap top">&nbsp;
                <?php if ($this->user->hasRight('editKey')) { ?>
                    <label for="key-<?php echo $hit['id'];?>" class="inlineEditTrigger">
                        <?php echo $this->getIcon('Edit', $this->lang->L_CLICK_TO_INLINE_EDIT);?>
                    </label>
                <?php } ?>
            </td>
        <?php } ?>
        <td class="ssmall nowrap top">
            <?php if ($this->user->hasRight('editKey')) { ?>
                <div class="inlineEdit" id="key-<?php echo $hit['id'];?>" title="<?php echo $this->lang->L_CLICK_TO_INLINE_EDIT;?>"><?php echo $hit['key'];?></div>
            <?php } else { ?>
                <?php echo $edit . $hit['key'];?></a>
            <?php } ?>
        </td>
        <?php
        foreach ($this->showLanguages as $lang) {
            $text = isset($hit['languages'][$lang]) ? $hit['languages'][$lang] : '';
            $text = htmlspecialchars($text, ENT_COMPAT,'utf-8');
            if (!isset($text) || $text == '') {
                $text = '<i>untranslated</i>';
            }
            if (in_array($lang, $this->languagesEdit)) {
                echo '<td class="top">'. $edit . $this->getIcon('Edit', '').'</a></td>'
                    .'<td class="top">'. $edit. $text . '</a></td>';
            } else {
                echo '<td colspan="2" class="top">'. $text .'</td>';
            }
        }
        ?>
    </tr>
<?php
    $i++;
}
if ($this->rows == 0) {
    $rowCount = 5+count($this->languagesEdit)+count($this->showLanguages);
    if ($this->addVar) {
        $rowCount++;
    }
?>
    <tr class="row-even">
        <td colspan="<?php echo $rowCount;?>">
            <br />
            Nothing found.<br />
            Select another filter / search value.
            <br /><br />
        </td>
    </tr>
<?php
}
    ?>
</table>
<script type="text/javascript">
<?php $this->jQuery()->onLoadCaptureStart();?>
function deleteVar(id, name)
{
    if (confirm('Are you really sure you want to delete the variable \''+name+'\'?\nAll language entries will be lost!')) {
        setPageInactive();
        self.location.href = '<?php echo $this->baseUrl();?>/entries/delete/id/'+id;
    }
}

$('.inlineEditTrigger').click(function() {
    var id = $(this).attr('for');
    $('#' + id).trigger('click');
});

$('.inlineEdit').eip('<?php echo $this->serverUrl() . $this->baseUrl();?>/ajax/save-key-name/', {
    saving_text: '<?php echo $this->lang->L_SAVING . '... ' . $this->getIcon('ajax-loader');?>',
    savebutton_text: '<?php echo $this->lang->L_SAVE;?>',
    savebutton_class: 'Formbutton',
    cancelbutton_text: '<?php echo $this->lang->L_CANCEL;?>',
    cancelbutton_class: 'Formbutton',
    mouseover_class: 'inlineEditMouseOver',
    editfield_class: 'inlineEditField',
    size: 'auto',
    form_buttons: '<span><button type="button" id="save-#{id}" class="#{savebutton_class}"><?php echo $this->getIcon('save');?> #{savebutton_text}</button> <button id="cancel-#{id}" class="#{cancelbutton_class}"><?php echo $this->getIcon('cancel');?>  #{cancelbutton_text}</button></span><br /><br />'

});
<?php $this->jQuery()->onLoadCaptureEnd();?>
</script>
