<?php
$this->jQuery()->onLoadCaptureStart();
?>
$.ajax({
    url: '<?php echo $this->serverUrl(). $this->baseUrl() . '/ajax/optimize-tables';?>',
    dataType: 'json',
    type: "GET",
    async : true,
    cache: false,
    success: function (data) {
            var errorMsg = '';
            $.each(data, function(table, msg) {
                if (msg != 'ok') {
                    errorMsg += table + ': ' + msg + '<br />';
                }
            });
            if (errorMsg > '') {
                $('#optimizeErrors').html(errorMsg);
                $('#optimizationError').dialog({
                    title: '<?php echo $this->lang->L_ERROR;?>',
                    modal: true,
                    width: 400,
                    buttons: { '<?php echo $this->lang->L_OK;?>': function() { $(this).dialog("close"); } }
                });
            }
        }
});
<?php
$this->jQuery()->onLoadCaptureEnd();
