<?php
$addUserUrl = $this->baseUrl() . '/admin_users/edit/id/0';
?>
<p style="margin:0;padding:0;">
    <input type="hidden" id="offset" name="offset" value="<?php echo $this->offset;?>" />
    <?php echo $this->lang->L_FILTER_SEARCH;?>:
    <input type="text" class="text" id="filterUser" name="filterUser" value="<?php echo $this->escape($this->filterUser);?>" />
    <button type="submit" class="Formbutton" value="Search" onclick="resetOffset();">
        <?php echo $this->getIcon('search', '', 16);?> <?php echo $this->lang->L_SEARCH;?>
    </button>
    <button type="submit" class="Formbutton" onclick="$('#filterUser').val('');resetOffset();">
        <?php echo $this->getIcon('delete', '');?> <?php echo $this->lang->L_RESET;?>
    </button>
    <?php if ($this->user->hasRight('addUser')) { ?>
        <button type="button" class="Formbutton" onclick="window.location.href='<?php echo $addUserUrl;?>'">
            <?php echo $this->getIcon('plus', '');?> <?php echo $this->lang->L_CREATE_NEW_USER_ACCOUNT;?>
        </button>
    <?php } ?>
    <br /><br />

    <a href="#" <?php if($this->offset > 0): ?> title="<?php echo $this->lang->L_PREVIOUS_PAGE;?> (<?php echo $this->lang->L_SHORTCUT;?> ALT+C)"
        onclick="mySubmit('offset', '<?php echo $this->offset-$this->recordsPerPage;?>');"
        accesskey="c" class="Formbutton"><?php echo $this->getIcon('Back', '', 16);?>
        <?php else: ?>
        class="Formbutton"><?php echo $this->getIcon('BackDisabled', '', 16);?>
        <?php endif; ?>
    </a>

    <a href="#" <?php if($this->offset + (int) $this->recordsPerPage < $this->hits): ?> title="<?php echo $this->lang->L_NEXT_PAGE;?> (<?php echo $this->lang->L_SHORTCUT;?> ALT+V)"
        onclick="mySubmit('offset', '<?php echo $this->offset+$this->recordsPerPage;?>');"
        accesskey="v" class="Formbutton"><?php echo $this->getIcon('Forward', '', 16);?>
        <?php else: ?>
        class="Formbutton"><?php echo $this->getIcon('ForwardDisabled', '', 16);?>
        <?php endif; ?>
    </a>
    <?php echo $this->lang->L_ENTRIES_PER_PAGE;?>:
    <select name="recordsPerPage" onchange="setPageInactive();;resetOffset();$('#myForm').submit();">
        <?php echo $this->selRecordsPerPage;?>
    </select>
    <?php echo $this->lang->L_HITS;?>: <?php echo $this->numberFormat($this->hits);?>
    <input type="hidden" name="deleteUser" id="deleteUser" value="0"/>
</p>
