<div id="headline">
    <h2><?php echo $this->lang->L_CONFIGURATION . ' - ' . $this->lang->L_LANGUAGES;?></h2>
</div>
<?php
$i = 1;
echo $this->partial('settings/head-navi.phtml', array('lang' => $this->lang, 'vcsActivated' => $this->vcsActivated));
?>
<form action="<?php echo $this->baseUrl();?>/settings_languages/index" method="post">
    <h4><?php echo $this->lang->L_YOU_ARE_ALLOWED_TO_EDIT_FOLLOWING_LANGUAGES;?>:</h4>
    <table class="bdr small" summary="List of languages you are allowed to edit">
        <tr class="thead">
            <th>#</th>
            <th colspan="3"><?php echo $this->lang->L_LANGUAGES;?></th>
            <th><?php echo $this->lang->L_FALLBACK_LANGUAGE;?></th>
        </tr>
        <?php
        foreach ($this->editLanguages as $lang) {
            $langId   = $lang;
            $langName = $this->languages[$langId]['name'];
            ?>
            <tr class="<?php echo $this->cycle(array('row-even', 'row-odd'))->next();?>">
                <td class="right vmiddle"><?php echo $i;?>.</td>
                <td>
                    <?php echo $this->printFlag($langId);?>
                </td>
                <td class="vmiddle"><?php echo $this->languages[$langId]['locale'];?></td>
                <td class="vmiddle"><?php echo $langName;?></td>
                <td class="vmiddle">
                    <?php
                    if ($langId == $this->fallbackLanguageId) {
                        echo $this->getIcon('Ok', '', 16);
                    }
                    ?>
                    &nbsp;
                </td>
            </tr>
            <?php
            $i++;
        }
        ?>
    </table>

    <div class="spacer"></div>
    <h4><?php echo $this->lang->L_SELECT_YOUR_REFERENCE_LANGUAGES;?>:</h4>

    <p><?php echo $this->lang->L_REFERENCE_LANGUAGES_EXPLAIN;?></p>
    <table class="bdr" summary="List of all languages you can select as a reference">
        <tr class="thead">
            <th>#</th>
            <th colspan="3"><?php echo $this->lang->L_REFERENCE_LANGUAGES;?></th>
            <th><?php echo $this->lang->L_STATUS;?></th>
            <th>&nbsp;</th>
        </tr>
        <?php
        $i                 = 1;
        $cycle             = $this->cycle(array('row-even', 'row-odd'));
        $switchStatusTitle = 'title="' . $this->lang->L_CHANGE_STATUS . '"';
        foreach ($this->languages as $key => $language) {
            $id       = 'lang_' . $language['id'];
            $langId   = $language['id'];
            $langName = $this->languages[$langId]['name'];
            $canEditLanguage = false;
            if (in_array($key, $this->editLanguages)) {
                $canEditLanguage = true;
            } ?>
            <tr class="<?php echo $cycle->next();?>">
                <td class="right vmiddle"><?php echo $i;?>.</td>
                <td>
                    <label for="img-<?php echo $language['id'];?>" class="switchUserReferenceLanguageLabel">
                        <?php echo $this->printFlag($key);?>
                    </label>
                </td>
                <td class="vmiddle">
                    <label <?php echo $switchStatusTitle;?> for="img-<?php echo $language['id'];?>"
                                                            class="switchUserReferenceLanguageLabel">
                        <?php echo $this->languages[$langId]['locale'];?>
                    </label>
                </td>
                <td class="vmiddle">
                    <label <?php echo $switchStatusTitle;?> for="img-<?php echo $language['id'];?>"
                                                            class="switchUserReferenceLanguageLabel">
                        <?php echo $langName;?>
                    </label>
                </td>
                <td class="vmiddle center">
                    <div id="img-<?php echo $language['id'];?>" class="switchUserReferenceLanguage">
                        <?php
                        if (in_array($key, $this->refLanguagesSelected)) {
                            echo $this->getIcon('Ok', $this->lang->L_CHANGE_STATUS, 16);
                        } else {
                            echo $this->getIcon('NotOk', $this->lang->L_CHANGE_STATUS, 16);
                        }
                        ;?>
                    </div>
                </td>
                <td class="vmiddle"><?php
                    if ($canEditLanguage !== true) { ?>
                        <a class="Formbutton requestEditRights" id="lang-<?php echo $language['locale'];?>"><?php
                            echo $this->getIcon('Edit', '', 16). ' ' . $this->lang->L_REQUEST_EDIT_RIGHT;?>
                        </a><?php
                    } else { ?>
                        &nbsp;<?php
                    } ?>
                </td>
            </tr>
            <?php
            $i++;
        }
        ?>
    </table>
</form>
<script type="text/javascript">
    <?php $this->jQuery()->onLoadCaptureStart(); ?>
    $('.switchUserReferenceLanguage').click(function () {
        var languageId = this.id.replace(/img-/, '');
        $('#img-' + languageId).html(imgAjax);
        $.ajax({
            type:'POST',
            url:'<?php echo $this->serverUrl() . $this->baseUrl(); ?>/ajax/switch-reference-language-status',
            dataType:'json',
            async:true,
            cache:false,
            data:{
                'languageId':languageId
            },
            success:function (data) {
                $('#img-' + languageId).html(data.icon);
            },
            error:function (error) {
                $('#img-' + languageId).html(imgError);
            }
        });
    });
    $('.switchUserReferenceLanguageLabel').click(function () {
        var id = $(this).attr('for');
        $('#' + id).trigger('click');
    });
    $('.requestEditRights').click(function () {
        var languageLocale = this.id.replace(/lang-/, '');
        var message = '<?php echo $this->jsEscape($this->lang->L_REQUEST_EDIT_RIGHT_CONFIRM);?>';
        message = message.replace('{LOCALE}', languageLocale);
        $('#confirmRequestEditRight').html(message);
        $('#confirmRequestEditRight').dialog('option', 'locale', languageLocale);
        $('#confirmRequestEditRight').dialog('open');
    });

    <?php
    $this->popUpMessage()->addMessage(
        'confirmRequestEditRight',
        $this->lang->L_REQUEST_EDIT_RIGHT,
        $this->lang->L_REQUEST_EDIT_RIGHT_CONFIRM,
        array(
            'modal' => true,
            'height' => 140,
            'width' => 440,
            'dialogClass' => 'info',
            'autoOpen' => false,
            'buttons' => array(
                'L_CANCEL' => 'function() {
                                    $(this).dialog("close");
                                }',
                'L_REQUEST_EDIT_RIGHT' => 'function() {
                    $(this).html(\'' . $this->jsEscape($this->getIcon('ajax-loader', '')) . '\');
                    var locale = $(\'#confirmRequestEditRight\').dialog(\'option\', \'locale\');
                    $.ajax({
                        type:\'POST\',
                        url:\'' . $this->serverUrl() . $this->baseUrl() . '/ajax/request-language-edit-right\',
                        dataType:\'json\',
                            async:false,
                            cache:false,
                            data:{
                            \'locale\':locale
                        },
                        success:function (data) {
                            if (data.success == true) {
                                $(\'#confirmRequestEditRight\').html(\'' . $this->jsEscape($this->lang->L_REQUEST_EDIT_RIGHT_CONFIRM_MESSAGE) . '\');
                            } else {
                                $(\'#confirmRequestEditRight\').html(\'' . $this->jsEscape(($this->lang->L_ERROR . '!<br /> ' . $this->lang->L_TRY_AGAIN)) . '\');
                            }
                            buttons = $(\'#confirmRequestEditRight\').dialog(\'option\', \'buttons\');
                            $(\'#confirmRequestEditRight\').dialog(\'option\', \'buttons\', {
                                \'' . $this->jsEscape($this->lang->L_OK) . '\': function() {
                                    $(this).dialog("close");
                                    $(\'#confirmRequestEditRight\').dialog(\'option\', \'buttons\', buttons);
                                }
                            });
                        },
                        error:function (error) {
                            $(\'#confirmRequestEditRight\').html(imgError + \'' . $this->jsEscape($this->lang->L_ERROR_AJAX) . '\');
                        }
                    });

                }'
            )
        )
    );

    $this->jQuery()->onLoadCaptureEnd();
    ?>
</script>

