<h2>Admin - Files</h2>
<?php
echo $this->partial('admin/head-navi.phtml');
if ($this->fileTemplate['id'] == 0) {
    $subTitle = "Create new file template";
} else {
    $subTitle = "Edit file template \"{$this->fileTemplate['name']}\"";
} ?>
<h4><?php echo $this->out($subTitle); ?></h4>
<form action="<?php echo $this->baseUrl(); ?>/admin_files/edit/id/<?php echo $this->fileTemplate['id']; ?>/" method="post" enctype="multipart/form-data">
    <table class="bdr more-padding" summary="List of file template settings">
        <tr class="thead">
            <th colspan="2">File template settings</th>
            <th>Possible placeholder</th>
        </tr>
        <tr class="row-odd">
            <td><label for="tplName">Name</label></td>
            <td><input type="text" name="tplName" id="tplName" class="text" size="80" value="<?php echo $this->out($this->fileTemplate['name']); ?>"/></td>
            <td>-</td>
        </tr>
        <tr class="row-even">
            <td>
                <label for="tplHeader">Header</label>
            </td>
            <td><textarea name="tplHeader" id="tplHeader" rows="2" cols="80" class="textarea-edit"><?php echo $this->out($this->fileTemplate['header']); ?></textarea></td>
            <td>{LANG_NAME}, {LOCALE}</td>
        </tr>
        <tr class="row-odd">
            <td><label for="tplContent">Content</label></td>
            <td><textarea name="tplContent" id="tplContent" rows="2" cols="80" class="textarea-edit"><?php echo $this->out($this->fileTemplate['content']); ?></textarea></td>
            <td>{KEY}, {VALUE}</td>
        </tr>
        <tr class="row-even">
            <td><label for="tplFooter">Footer</label></td>
            <td><textarea name="tplFooter" id="tplFooter" rows="2" cols="80" class="textarea-edit"><?php echo $this->out($this->fileTemplate['footer']); ?></textarea></td>
            <td>{LANG_NAME}, {LOCALE}</td>
        </tr>
        <tr class="row-odd">
            <td><label for="tplFile">Filename</label></td>
            <td><input type="text" name="tplFile" id="tplFile" class="text" size="80" value="<?php echo $this->out($this->fileTemplate['filename']); ?>"/></td>
            <td>{LOCALE}</td>
        </tr>
        <tr class="row-even">
            <td>&nbsp;</td>
            <td colspan="2"><button type="submit" class="Formbutton"><?php echo $this->getIcon('save'); ?> Save</button></td>
        </tr>
    </table>
</form>
<?php
$this->jQuery()->addOnLoad('$("textarea").autoGrow();');
if (isset($this->creationResult)) {
    if ($this->creationResult === true) {
        $this->popUpMessage()->addMessage(
            'settingsSaved',
            'Ok',
            'Your changes have been saved successfully.',
            array(
                 'modal' => true,
                 'height' => 130,
                 'width' => 400,
                 'dialogClass' => 'info',
            )
        );
    } else {
        $this->popUpMessage()->addMessage(
            'settingsSaved',
            'Error',
            'The following error occurred while saving your changes.<br /><br/><span class="error">'
                . $this->creationResult . '</span><br /><br/>Please try again.<br/><br/>',
            array(
                'modal' => true,
                'width' => 400,
                'dialogClass' => 'info',
            )
        );
    }
}
?>
