<h2>Admin - Files</h2>
<?php echo $this->partial('admin/head-navi.phtml'); ?>
What?! Why are you here?<br />
All these interruptions are enough to make one insane. *mad laughter*<br />
Here, take this and leave me to my work.<br/>
Trouble me no more!<br /><br /><br />
<a class="Formbutton" href="<?php echo $this->baseUrl(); ?>/admin_files/"><?php echo $this->getIcon('Back', '', 16); ?> Go back</a>