<h2>Admin - Files</h2>
<?php echo $this->partial('admin/head-navi.phtml'); ?>
<form action="<?php echo $this->baseUrl();?>/admin_files/" method="post" id="myForm">
    <p style="margin:0;padding:0;">
        <input type="hidden" id="offset" name="offset" value="<?php echo $this->offset;?>" />
        Filter / Search:
        <input type="text" class="text" id="filterUser" name="filterUser" value="<?php echo $this->escape($this->filterUser);?>" />
        <button type="submit" class="Formbutton" value="Search" onclick="resetOffset();">
            <?php echo $this->getIcon('search', '', 16);?> Search
        </button>
        <button type="submit" class="Formbutton" onclick="$('#filterUser').val('');resetOffset();">
            <?php echo $this->getIcon('delete', '');?> Reset
        </button>
        <button type="button" class="Formbutton" onclick="window.location.href='<?php echo $this->baseUrl();?>/admin_languages/edit/id/0'">
            <?php echo $this->getIcon('plus', '');?> Add language
        </button>
        <br /><br />

        <a href="#" <?php if($this->offset > 0): ?> title="Shortcut ALT+C"
            onclick="mySubmit('offset', '<?php echo $this->offset-$this->recordsPerPage;?>');"
            accesskey="c" class="Formbutton"><?php echo $this->getIcon('Back', '', 16);?>
            <?php else: ?>
            class="Formbutton"><?php echo $this->getIcon('BackDisabled', '', 16);?>
            <?php endif; ?>
        </a>

        <a href="#" <?php if($this->offset + $this->recordsPerPage < $this->rows): ?> title="Shortcut ALT+V"
            onclick="mySubmit('offset', '<?php echo $this->offset+$this->recordsPerPage;?>');"
            accesskey="v" class="Formbutton"><?php echo $this->getIcon('Forward', '', 16);?>
            <?php else: ?>
            class="Formbutton"><?php echo $this->getIcon('ForwardDisabled', '', 16);?>
            <?php endif; ?>
        </a>
        Entries per page:
        <select name="recordsPerPage" onchange="setPageInactive();resetOffset();$('#myForm').submit();">
            <?php echo $this->selRecordsPerPage;?>
        </select>
        Hits: <?php echo $this->numberFormat($this->hits);?>

    </p>
</form>
