<div id="headline">
    <h2><?php echo $this->lang->L_ADMIN;?> - <?php echo $this->lang->L_FILE_TEMPLATES;?></h2>
</div>
<?php echo $this->partial('admin/head-navi.phtml', array('lang' => $this->lang)); ?>
<form action="<?php echo $this->baseUrl();?>/admin_files/" method="post" id="myForm">
    <p style="margin:0;padding:0;">
        <input type="hidden" id="offset" name="offset" value="<?php echo $this->offset;?>" />
        <?php echo $this->lang->L_FILTER_SEARCH;?>:
        <input type="text" class="text" id="filterUser" name="filterUser" value="<?php echo $this->escape($this->filterUser);?>" />
        <button type="submit" class="Formbutton ui-corner-all" value="Search" onclick="resetOffset();">
            <?php echo $this->getIcon('Search', '', 16);?> <?php echo $this->lang->L_SEARCH;?>
        </button>
        <button type="submit" class="Formbutton ui-corner-all" onclick="$('#filterUser').val('');resetOffset();">
            <?php echo $this->getIcon('delete', '');?> <?php echo $this->lang->L_RESET;?>
        </button>
        <?php if ($this->user->hasRight('addTemplate')) { ?>
            <button type="button" class="Formbutton ui-corner-all" onclick="window.location.href='<?php echo $this->baseUrl();?>/admin_files/edit/id/0'">
                <?php echo $this->getIcon('plus', '');?> <?php echo $this->lang->L_ADD_FILE_TEMPLATE;?>
            </button>
        <?php } ?>
        <br /><br />

        <a href="#" <?php if($this->offset > 0): ?> title="<?php echo $this->lang->L_PREVIOUS_PAGE;?> (<?php echo $this->lang->L_SHORTCUT;?> ALT+C)"
            onclick="mySubmit('offset', '<?php echo $this->offset-$this->recordsPerPage;?>');"
            accesskey="c" class="Formbutton ui-corner-all"><?php echo $this->getIcon('Back', '', 16);?>
            <?php else: ?>
            class="Formbutton ui-corner-all"><?php echo $this->getIcon('BackDisabled', '', 16);?>
            <?php endif; ?>
        </a>

        <a href="#" <?php if($this->offset + $this->recordsPerPage < $this->rows): ?> title="<?php echo $this->lang->L_NEXT_PAGE;?> (<?php echo $this->lang->L_SHORTCUT;?> ALT+V)"
            onclick="mySubmit('offset', '<?php echo $this->offset+$this->recordsPerPage;?>');"
            accesskey="v" class="Formbutton ui-corner-all"><?php echo $this->getIcon('Forward', '', 16);?>
            <?php else: ?>
            class="Formbutton ui-corner-all"><?php echo $this->getIcon('ForwardDisabled', '', 16);?>
            <?php endif; ?>
        </a>
        <?php echo $this->lang->L_ENTRIES_PER_PAGE;?>:
        <select name="recordsPerPage" onchange="setPageInactive();resetOffset();$('#myForm').submit();">
            <?php echo $this->selRecordsPerPage;?>
        </select>
        <?php echo $this->lang->L_HITS;?>: <?php echo $this->numberFormat($this->hits);?>
        &nbsp;|&nbsp;
        <?php echo $this->lang->L_ORDER_LIST_BY;?>: <select name="templateOrderBy" onchange="$(this).parents('form')[0].submit();"><?php echo Msd_Html::getHtmlOptions($this->templateOrderFields, $this->selOrderField, false); ?></select>

    </p>
</form>

    <table class="bdr more-padding ssmall" summary="List of file templates">
        <tr class="thead">
            <th></th>
            <th>#</th>
            <th><?php echo $this->lang->L_NAME;?></th>
            <th><?php echo $this->lang->L_HEADER;?></th>
            <th><?php echo $this->lang->L_GENERATED_CONTENT;?></th>
            <th><?php echo $this->lang->L_FOOTER;?></th>
            <th><?php echo $this->lang->L_FILE_PATH;?></th>
        </tr>
<?php
if ($this->hits == 0) { ?>
    <tr class="row-odd">
        <td colspan="6" class="error"><?php echo $this->lang->L_NO_HITS;?>.</td>
    </tr>

<?php
}
$cycleHelper = $this->cycle(array('row-even', 'row-odd'));
$counter = 0;
if ($this->user->hasRight('editTemplate')) {
    $editUrlPattern = $this->baseUrl() . '/admin_files/edit/id/';
} else {
    $editUrlPattern = $this->baseUrl() . '/admin_files/view/id/';
}
foreach ($this->fileTemplates as $fileTemplate) {
    $cutOptions = array(
        'escapeResult' => true,
    );
    $headerShort = $this->cutString($fileTemplate['header'], 40, $cutOptions);
    $footerShort = $this->cutString($fileTemplate['footer'], 40, $cutOptions);
    $editUrl     = $editUrlPattern . $fileTemplate['id'] . '/';
    $counter++;
?>
    <tr class="<?php echo $cycleHelper->next(); ?>">
        <td class="nowrap">
            <a href="<?php echo $editUrl; ?>" title="<?php echo $this->lang->L_EDIT_FILE_TEMPLATE;?>"><?php echo $this->getIcon('Edit', ''); ?></a>
            <?php if ($this->user->hasRight('addTemplate')) { ?>
                <a href="#" title="<?php echo $this->lang->L_DELETE_FILE_TEMPLATE;?>" onclick="showDelConfirm(<?php echo $fileTemplate['id']; ?>);"><?php echo $this->getIcon('delete', ''); ?></a>
            <?php } ?>
        </td>
        <td><?php echo $counter; ?></td>
        <td>
            <a href="<?php echo $editUrl; ?>" title="<?php echo $this->lang->L_EDIT_FILE_TEMPLATE;?>"><?php echo $this->out($fileTemplate['name']); ?></a>
        </td>
        <td>
            <pre><?php echo $headerShort; ?></pre>
            <?php if (strlen($headerShort) < strlen($fileTemplate['header'])) { ?><a href="#" class="Formbutton expandButton" id="tmpl-header-<?php echo $fileTemplate['id']; ?>"><?php echo $this->getIcon('Info', '', 16); ?> <?php echo $this->lang->L_HEADER;?></a>
            <div class="hidden" id="complete-header-<?php echo $fileTemplate['id']; ?>"><?php echo $this->lang->L_HEADER;?>:<pre style="border:1px dashed #256777; padding:5px; margin:5px;"><?php echo $this->out($fileTemplate['header']); ?></pre></div><?php } ?>
        </td>
        <td>
            <pre><?php echo $this->out($fileTemplate['content']); ?></pre>
        </td>
        <td>
            <pre><?php echo $footerShort; ?></pre>
            <?php if (strlen($headerShort) < strlen($fileTemplate['footer'])) { ?><a href="#" class="Formbutton expandButton" id="tmpl-footer-<?php echo $fileTemplate['id']; ?>"><?php echo $this->getIcon('Info', '', 16); ?> <?php echo $this->lang->L_FOOTER;?></a>
            <div class="hidden" id="complete-footer-<?php echo $fileTemplate['id']; ?>"><?php echo $this->lang->L_FOOTER;?>:<pre style="border:1px dashed #256777; padding:5px; margin:5px;"><?php echo $this->out($fileTemplate['footer']); ?></pre></div><?php } ?>
        </td>
        <td><?php echo $this->out($fileTemplate['filename']); ?></td>
    </tr>
<?php
}
?>
    </table>
<script type="text/javascript">
<?php $this->jQuery()->javascriptCaptureStart(); ?>
var templateList = <?php echo Zend_Json_Encoder::encode($this->fileTemplates); ?>;
function showDelConfirm(tmplId)
{
    var tempTemplateList = [];
    tempTemplateList.push({'id':0, 'name':'<?php echo $this->jsEscape($this->lang->L_DELETE_FILE_TEMPLATE);?>'});
    var tmplToDelete;
    for (var i in templateList) {
        if (templateList[i].id == tmplId) {
            tmplToDelete = templateList[i];
            continue;
        }
        tempTemplateList.push(templateList[i]);
    }
    var dialogDiv = $(
        '<div><?php echo $this->jsEscape($this->lang->L_CONFIRM_DELETE_FILE_TEMPLATE);?>:"'
            + tmplToDelete.name
            + '"?<br\/><br\/><br\/><?php echo $this->jsEscape($this->lang->L_SELECT_REPLACEMENT_TEMPLATE);?>:<br\/>'
            + '<form action="<?php echo $this->baseUrl(); ?>/admin_files/delete/" method="post" id="delTemplateForm">'
            + '<span id="delTmplFormContent"\/><input type="hidden" name="delTemplateId" value="'
            + tmplId + '" \/><\/form><\/div>'
    );
    var select = $('<select name="replacementId"><\/select>');
    var template = $.template(null, '<option value="${id}">${name}<\/option>');
    $.tmpl(template, tempTemplateList).appendTo(select);
    dialogDiv.find('#delTmplFormContent').append(select);
    dialogDiv.dialog({
        'autoOpen':true,
        'modal':true,
        'dialogClass':'info',
        'title':'<?php echo $this->jsEscape($this->lang->L_DELETE_FILE_TEMPLATE);?>',
        'minWidth':560,
        'buttons':[{
            'text':'<?php echo $this->lang->L_YES;?>',
            'click':function() { $(this).dialog('close'); $('#delTemplateForm')[0].submit(); }
        }, {
            'text':"<?php echo $this->lang->L_CANCEL;?>",
            'click':function() { $(this).dialog('close'); }
        }]
    });
}
<?php $this->jQuery()->javascriptCaptureEnd(); ?>
<?php $this->jQuery()->onLoadCaptureStart(); ?>
$('.expandButton').click(function(){
    var tmplInfo = $(this).attr('id').split('-');
    var tmplId = tmplInfo[2];
    var tmplType = tmplInfo[1];
    $('#complete-' + tmplType + '-' + tmplId).dialog({
        "dialogClass":"info",
        "buttons":{ "OK": function() { $(this).dialog('close'); } },
        "title": '<?php echo $this->jsEscape($this->lang->L_COMPLETE_VIEW);?>',
        "minWidth":560,
        "modal":true
    });
});
<?php $this->jQuery()->onLoadCaptureEnd(); ?>
</script>
<?php
if ($this->deletionResult !== null) {
    if ($this->deletionResult['delete'] && $this->deletionResult['update']) {
        $this->showNotification(
            true,
            $this->lang->L_FILE_TEMPLATE_DELETED_SUCCESSFULLY . '.<br/>'
                . $this->lang->L_TEMPLATE_ASSIGNMENTS_UPDATED . '.',
            '',
            6000
        );
    } else {
        $message = $this->deletionResult['delete'] ?
            $this->lang->L_FILE_TEMPLATE_DELETED_SUCCESSFULLY . '.' :
            $this->lang->L_ERROR_DELETING_FILE_TEMPLATE . '!';
        $message .= '<br />';
        $message .= $this->deletionResult['update'] ?
            $this->lang->L_TEMPLATE_ASSIGNMENTS_UPDATED . '.' :
            $this->lang->L_ERROR_UPDATING_FILE_TEMPLATE . '!';

        $this->showNotification(false, '', $message, 6000);
    }
}
