<h2>Admin - Files</h2>
<?php echo $this->partial('admin/head-navi.phtml'); ?>
<form action="<?php echo $this->baseUrl();?>/admin_files/" method="post" id="myForm">
    <p style="margin:0;padding:0;">
        <input type="hidden" id="offset" name="offset" value="<?php echo $this->offset;?>" />
        Filter / Search:
        <input type="text" class="text" id="filterUser" name="filterUser" value="<?php echo $this->escape($this->filterUser);?>" />
        <button type="submit" class="Formbutton" value="Search" onclick="resetOffset();">
            <?php echo $this->getIcon('search', '', 16);?> Search
        </button>
        <button type="submit" class="Formbutton" onclick="$('#filterUser').val('');resetOffset();">
            <?php echo $this->getIcon('delete', '');?> Reset
        </button>
        <button type="button" class="Formbutton" onclick="window.location.href='<?php echo $this->baseUrl();?>/admin_files/edit/id/0'">
            <?php echo $this->getIcon('plus', '');?> Add file template
        </button>
        Order list by: <select name="templateOrderBy" onchange="$(this).parents('form')[0].submit();"><?php echo Msd_Html::getHtmlOptions($this->templateOrderFields, $this->selOrderField, false); ?></select>
        <br /><br />

        <a href="#" <?php if($this->offset > 0): ?> title="Shortcut ALT+C"
            onclick="mySubmit('offset', '<?php echo $this->offset-$this->recordsPerPage;?>');"
            accesskey="c" class="Formbutton"><?php echo $this->getIcon('Back', '', 16);?>
            <?php else: ?>
            class="Formbutton"><?php echo $this->getIcon('BackDisabled', '', 16);?>
            <?php endif; ?>
        </a>

        <a href="#" <?php if($this->offset + $this->recordsPerPage < $this->rows): ?> title="Shortcut ALT+V"
            onclick="mySubmit('offset', '<?php echo $this->offset+$this->recordsPerPage;?>');"
            accesskey="v" class="Formbutton"><?php echo $this->getIcon('Forward', '', 16);?>
            <?php else: ?>
            class="Formbutton"><?php echo $this->getIcon('ForwardDisabled', '', 16);?>
            <?php endif; ?>
        </a>
        Entries per page:
        <select name="recordsPerPage" onchange="setPageInactive();resetOffset();$('#myForm').submit();">
            <?php echo $this->selRecordsPerPage;?>
        </select>
        Hits: <?php echo $this->numberFormat($this->hits);?>
    </p>
</form>

    <table class="bdr more-padding ssmall" summary="List of file templates">
        <tr class="thead">
            <th></th>
            <th>#</th>
            <th>Name</th>
            <th>Header</th>
            <th>Language variable</th>
            <th>Footer</th>
            <th>File path</th>
        </tr>
<?php
if ($this->hits == 0) { ?>
    <tr class="row-odd">
        <td colspan="6" class="error">Sorry, no hits.</td>
    </tr>

<?php
}
$cycleHelper = $this->cycle(array('row-even', 'row-odd'));
$counter = 0;
foreach ($this->fileTemplates as $fileTemplate) {
    $cutOptions = array(
        'escapeResult' => true,
    );
    $headerShort = $this->cutString($fileTemplate['header'], 40, $cutOptions);
    $footerShort = $this->cutString($fileTemplate['footer'], 40, $cutOptions);

    $counter++;
    $editUrl = $this->baseUrl() . '/admin_files/edit/id/' . $fileTemplate['id'] . '/';
?>
        <tr class="<?php echo $cycleHelper->next(); ?>">
            <td>
                <a href="<?php echo $editUrl; ?>" title="Edit file template"><?php echo $this->getIcon('Edit', ''); ?></a>
                <a href="#" title="Delete file template" onclick="showDelConfirm(<?php echo $fileTemplate['id']; ?>);"><?php echo $this->getIcon('delete', ''); ?></a>
            </td>
            <td><?php echo $counter; ?></td>
            <td>
                <a href="<?php echo $editUrl; ?>" title="Edit file template"><?php echo $this->out($fileTemplate['name']); ?></a>
            </td>
            <td>
                <pre><?php echo $headerShort; ?></pre>
                <?php if (strlen($headerShort) < strlen($fileTemplate['header'])) { ?><a href="#" class="Formbutton expandButton" id="tmpl-header-<?php echo $fileTemplate['id']; ?>"><?php echo $this->getIcon('Info', '', 16); ?> Complete header</a>
                <div class="hidden" id="complete-header-<?php echo $fileTemplate['id']; ?>">Complete file header:<pre style="border:1px dashed #256777; padding:5px; margin:5px;"><?php echo $this->out($fileTemplate['header']); ?></pre></div><?php } ?>
            </td>
            <td>
                <pre><?php echo $this->out($fileTemplate['content']); ?></pre>
            </td>
            <td>
                <pre><?php echo $footerShort; ?></pre>
                <?php if (strlen($headerShort) < strlen($fileTemplate['footer'])) { ?><a href="#" class="Formbutton expandButton" id="tmpl-footer-<?php echo $fileTemplate['id']; ?>"><?php echo $this->getIcon('Info', '', 16); ?> Complete footer</a>
                <div class="hidden" id="complete-footer-<?php echo $fileTemplate['id']; ?>">Complete file footer:<pre style="border:1px dashed #256777; padding:5px; margin:5px;"><?php echo $this->out($fileTemplate['footer']); ?></pre></div><?php } ?>
            </td>
            <td><?php echo $this->out($fileTemplate['filename']); ?></td>
        </tr>
<?php
}
?>
    </table>
<script type="text/javascript">
<?php $this->jQuery()->javascriptCaptureStart(); ?>
var templateList = <?php echo Zend_Json_Encoder::encode($this->fileTemplates); ?>;
function showDelConfirm(tmplId)
{
    var tempTemplateList = [];
    tempTemplateList.push({'id':0, 'name':'Unassigned'});
    var tmplToDelete;
    for (var i in templateList) {
        if (templateList[i].id == tmplId) {
            tmplToDelete = templateList[i];
            continue;
        }
        tempTemplateList.push(templateList[i]);
    }
    var dialogDiv = $(
        '<div>Are you sure, that you want delete the file template "'
            + tmplToDelete.name
            + '"?<br\/><br\/><br\/>Please select a replacement for the deleted file template:<br\/>'
            + '<form action="<?php echo $this->baseUrl(); ?>/admin_files/delete/" method="post" id="delTemplateForm">'
            + '<span id="delTmplFormContent"\/><input type="hidden" name="delTemplateId" value="'
            + tmplId + '" \/><\/form><\/div>'
    );
    var select = $('<select name="replacementId"><\/select>');
    var template = $.template(null, '<option value="${id}">${name}<\/option>');
    $.tmpl(template, tempTemplateList).appendTo(select);
    dialogDiv.find('#delTmplFormContent').append(select);
    console.debug(dialogDiv.find('#delTmplFormContent').size(), dialogDiv);
    dialogDiv.dialog({
        'autoOpen':true,
        'modal':true,
        'dialogClass':'info',
        'title':'Delete file template',
        'minWidth':560,
        'buttons':[{
            'text':'Yes',
            'click':function() { $(this).dialog('close'); $('#delTemplateForm')[0].submit(); }
        }, {
            'text':"No",
            'click':function() { $(this).dialog('close'); }
        }]
    });
}
<?php $this->jQuery()->javascriptCaptureEnd(); ?>
<?php $this->jQuery()->onLoadCaptureStart(); ?>
$('.expandButton').click(function(){
    var tmplInfo = $(this).attr('id').split('-');
    var tmplId = tmplInfo[2];
    var tmplType = tmplInfo[1];
    $('#complete-' + tmplType + '-' + tmplId).dialog({
        "dialogClass":"info",
        "buttons":{ "OK": function() { $(this).dialog('close'); } },
        "title":'Complete ' + tmplType,
        "minWidth":560,
        "modal":true
    });
});
<?php $this->jQuery()->onLoadCaptureEnd(); ?>
</script>
<?php if ($this->deletionResult !== null) {
    if ($this->deletionResult['delete'] && $this->deletionResult['update']) {
        $this->popUpMessage()->addMessage(
            'deletionSuccess',
            'Deletion successful',
            '<span class="success">The file template was successfully deleted.<br/><br/>Template assignments has been updated.</span>',
            array(
                'modal' => true,
                'dialogClass' => 'success',
                'width' => '350px',
            )
        );
    } else {
        $deletion = $this->deletionResult['delete'] ?
            '<span class="success">The file template was successfully deleted.</span>' :
            '<span class="error">Can\'t delete the file template.</span>';
        $update = $this->deletionResult['update'] ?
            '<span class="success">Template assignments has been updated.</span>' :
            '<span class="error">Can\'t update template assignments.</span>';
        $this->popUpMessage()->addMessage(
            'deletionErroneous',
            'Deletion successful',
            $deletion . '<br/><br/>' . $update,
            array(
                'modal' => true,
                'dialogClass' => 'error',
                'width' => '350px',
            )
        );
    }
}
var_dump($this->fileTemplates);