<div id="headline">
    <h2><?php echo $this->lang->L_EDIT_ENTRIES;?></h2>
</div>

<table class="bdr small" summary="List of entries">
    <tr class="thead">
        <th>#</th>
        <th><?php echo $this->lang->L_FILE_TEMPLATE;?></th>
        <th><?php echo $this->lang->L_KEY;?></th>
        <th><?php echo $this->lang->L_VALUE_IN_APPLICATION;?></th><?php
        foreach ($this->showLanguages as $lang) { ?>
            <th colspan="2" class="nowrap">
            <?php
            echo $this->printFlag($lang, 16).'&nbsp;';
            echo $this->languages[$lang]['name'];
            ?>
            </th><?php
        }
        ?>
    </tr>
    <?php
    $i=1;
    foreach ($this->hits as $hit)
    {
        $keyId = $hit['id'];
        $cycleHelper = $this->cycle(array('row-even', 'row-odd'));
        $edit = '<a>';
        if (sizeof($this->languagesEdit) > 0) {
            $edit = '<a name="lang-' . $lang. '" href="'.$this->baseUrl().'/entries/edit/id/'.$keyId .'/ref/connector" title="' . $this->lang->L_EDIT . '">';
        }
        ?>

        <tr class="<?php echo $cycleHelper->next();?>">
            <td class="right top">
                <?php echo $this->numberFormat($i);?>.
            </td>
            <td class="ssmall nowrap top">
                <?php echo $this->printFileTemplate($hit['template_id']);?>
            </td>
            <td class="ssmall nowrap top"><?php echo $hit['key'];?></td>
            <td>
                <?php echo $this->out($this->applicationValues[$hit['key']]); ?>
            </td>
            <?php
            foreach ($this->showLanguages as $lang) {
                $text = isset($hit['languages'][$lang]) ? $hit['languages'][$lang] : '';
                $text = htmlspecialchars($text, ENT_COMPAT,'utf-8');
                if (!isset($text) || $text == '') {
                    $text = '<i>' . $this->lang->L_UNTRANSLATED . '</i>';
                }
                if (in_array($lang, $this->languagesEdit)) { ?>
                    <td class="top">
                        <label for="key-<?php echo $hit['id'] . '-' . $lang;?>" id="lkey-<?php echo $hit['id'] . '-' . $lang;?>" class="inlineEditValueTrigger">
                            <?php echo $this->getIcon('Edit', $this->lang->L_CLICK_TO_INLINE_EDIT);?>
                        </label>
                    </td>
                    <td class="top">
                            <span id="key-<?php echo $hit['id'] . '-' . $lang;?>" class="inlineEditValue">
                                <?php echo $edit.$text;?></a>
                            </span>
                    </td><?php
                } else {
                    echo '<td colspan="2" class="top">'. $text .'</td>';
                }
            }
            ?>
        </tr>
        <?php
        $i++;
    }
    // no hits found
    if (count($this->hits) == 0) {
        $rowCount = 7 + count($this->languagesEdit) + count($this->showLanguages);
        if ($this->user->hasRight('addVar')) {
            $rowCount++;
        } ?>
        <tr class="row-odd">
        <td colspan="<?php echo $rowCount;?>">
            <br /><?php echo $this->lang->L_NO_HITS;?><br />
            <br /><br />
        </td>
        </tr><?php
    }
    ?>
</table>
<?php
echo $this->partial('/helper/js-edit-functions.phtml', array('lang' => $this->lang));

