<div id="logout">
    <?php
    echo $this->partial(
        'helper/switch-language-box.phtml',
        array(
            'lang'                  => $this->lang,
            'controller'            => 'register',
            'request'               => $this->request,
            'availableGuiLanguages' => $this->availableGuiLanguages,
        )
    );
    ?>
</div>

<div id="login">
    <h1><br><br><?php echo $this->lang->L_FORGOT_PASSWORD_TITLE; ?></h1>

    <div style="width:600px;margin: auto auto; vertical-align:middle; background: url('/css/otc/pics/User.png') no-repeat 2% 6%;">
        <form action="<?php echo $this->serverUrl() . $this->baseUrl(); ?>/index_password/requestpassword/" method="post" enctype="multipart/formdata">
            <fieldset>
                <table>
                    <tbody>
                        <tr>
                            <td>
                                <?php echo $this->lang->L_EMAIL; ?>
                            </td>
                            <td>
                                <input type="text" class="text" name="user_email" />
                            </td>
                        </tr>
                        <tr>
                            <td></td>
                            <td>
                                <button type="submit" class="Formbutton ui-corner-all"><?php echo $this->getIcon('save'); ?> <?php echo $this->lang->L_REQUEST_PASSWORD; ?></button>
                                <a href="<?php echo $this->serverUrl() . $this->baseUrl();?>" class="Formbutton ui-corner-all"><?php echo $this->getIcon('delete'); ?> <?php echo $this->lang->L_CANCEL; ?></a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </fieldset>
        </form>
    </div>
</div>

<?php
if($this->infos){
    $this->showNotification(
        $this->isError ? false : true,
        $this->infos['SUCCESS_MESSAGE'],
        $this->infos['ERROR_MESSAGE']
    );
}
?>