<div id="logout">
    <?php
    echo $this->partial(
        'helper/switch-language-box.phtml',
        array(
            'lang'                  => $this->lang,
            'controller'            => 'register',
            'request'               => $this->request,
            'availableGuiLanguages' => $this->availableGuiLanguages,
        )
    );
    ?>
</div>
    <div id="login">

    <h1><br><br><?php echo $this->lang->L_RESET_PASSWORD_TITLE; ?></h1>
    <div style="width:600px;margin: auto auto; vertical-align:middle; background: url('/css/otc/pics/User.png') no-repeat 2% 6%;">
        <form action="<?php echo $this->serverUrl() . $this->baseUrl(); ?>/index_password/setpassword/" method="post" enctype="multipart/formdata">
            <fieldset>

                <table>
                    <tbody>
                    <tr>
                        <td>
                            <?php echo $this->lang->L_NEW_PASSWORD ?>
                        </td>
                        <td>
                            <input type="password" class="text" name="user_password" />
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <?php echo $this->lang->L_CONFIRM_PASSWORD ?>
                        </td>
                        <td>
                            <input type="password" class="text" name="user_password2" />
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>
                            <input type="hidden" value="<?php echo $this->userid; ?>" name="userid"/>
                            <input type="hidden" value="<?php echo $this->userhash; ?>" name="userhash"/>
                            <button type="submit" class="Formbutton ui-corner-all"><?php echo $this->getIcon('save'); ?> <?php echo $this->lang->L_RESET; ?></button>
                            <a href="<?php echo $this->serverUrl() . $this->baseUrl();?>" class="Formbutton ui-corner-all"><?php echo $this->getIcon('delete'); ?> <?php echo $this->lang->L_CANCEL; ?></a>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </fieldset>
        </form>
    </div>
</div>
<?php

if($this->infos){
    $this->showNotification(
        $this->isError ? false : true,
        $this->infos['SUCCESS_MESSAGE'],
        $this->infos['ERROR_MESSAGE']
    );
}
?>