<?php
$user = new Application_Model_User();
$projectUrl   = $this->url(array('controller'=>'admin_project','action'=>'index'));
$usersUrl     = $this->url(array('controller'=>'admin_users','action'=>'index'));
$languagesUrl = $this->url(array('controller'=>'admin_languages','action'=>'index'));
$filesUrl     = $this->url(array('controller'=>'admin_files','action'=>'index'));
$vcsUrl       = $this->url(array('controller'=>'admin_vcs','action'=>'index'));
// get action name to set the active item in TabBar
$controllerName = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
// format action name and escape possible dot in action name
$controllerName = str_replace('.', '\\\.', $controllerName);
$this->jQuery()->onLoadCaptureStart(); ?>
// highlight active tab
$('#<?php echo $controllerName; ?>').addClass("ui-state-highlight");
<?php $this->jQuery()->onLoadCaptureEnd(); ?>

<div id="headnavi" class="ui-tabs ui-widget ui-widget-content ui-corner-all">
    <ul class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
        <?php
        if ($user->hasRight('editProject')) { ?>
            <li id="admin_project" class="ui-state-default ui-corner-top" onmouseover="tabOver(this)" onmouseout="tabOut(this)">
                <a href="<?php echo $projectUrl;?>">
                    <?php echo$this->getIcon('Project', '', 16);?>
                    Project
                </a>
            </li>
        <?php
        }
        if ($user->hasRight('editUsers')) { ?>
            <li id="admin_users" class="ui-state-default ui-corner-top" onmouseover="tabOver(this)" onmouseout="tabOut(this)">
                <a href="<?php echo $usersUrl;?>">
                    <?php echo$this->getIcon('Users', '', 16);?>
                    Users
                </a>
            </li>
        <?php
        }
        if ($user->hasRight('editLanguage')) { ?>
            <li id="admin_languages" class="ui-state-default ui-corner-top" onmouseover="tabOver(this)" onmouseout="tabOut(this)">
                <a href="<?php echo $languagesUrl;?>">
                    <?php echo$this->getIcon('Document', '', 16);?>
                    Languages
                </a>
            </li>
            <?php
        }
        if ($user->hasRight('editTemplate')) { ?>
            <li id="admin_files" class="ui-state-default ui-corner-top" onmouseover="tabOver(this)" onmouseout="tabOut(this)">
                <a href="<?php echo $filesUrl;?>">
                    <?php echo$this->getIcon('OpenFile', '', 16);?>
                    File Templates
                </a>
            </li>
            <?php
        }
        if ($user->hasRight('editVcs')) { ?>
            <li id="admin_export" class="ui-state-default ui-corner-top" onmouseover="tabOver(this)" onmouseout="tabOut(this)">
                <a href="<?php echo $vcsUrl;?>">
                    <?php echo$this->getIcon('BackupDatabase', '', 16);?>
                    VCS
                </a>
            </li>
        <?php } ?>
    </ul>
</div>
