<?php
$usersUrl           = $this->url(array('controller'=>'admin_users','action'=>'index'));
$languagesUrl       = $this->url(array('controller'=>'admin_languages','action'=>'index'));
$filesUrl           = $this->url(array('controller'=>'admin_files','action'=>'index'));
$exportUrl          = $this->url(array('controller'=>'admin_export','action'=>'index'));

// get action name to set the active item in TabBar
$actionName = Zend_Controller_Front::getInstance()->getRequest()->getActionName();

// format action name and escape possible dot in action name
$actionName = str_replace('.', '\\\.', $actionName);
$this->jQuery()->onLoadCaptureStart(); ?>
    // set selected tab
    $('#<?php echo $actionName; ?>').addClass("ui-state-active");
    $('#<?php echo $actionName; ?>').addClass("ui-tabs-selected");
<?php $this->jQuery()->onLoadCaptureEnd(); ?>

<div id="headnavi" class="ui-tabs ui-widget ui-widget-content ui-corner-all">
    <ul class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
        <li id="users" class="ui-state-default ui-corner-top" onmouseover="tabOver(this)" onmouseout="tabOut(this)">
            <a href="<?php echo $usersUrl;?>">
                <?php echo$this->getIcon('Users', '', 16);?>
                Users
            </a>
        </li>
        <li id="languages" class="ui-state-default ui-corner-top" onmouseover="tabOver(this)" onmouseout="tabOut(this)">
            <a href="<?php echo $languagesUrl;?>">
                <?php echo$this->getIcon('Document', '', 16);?>
                Languages
            </a>
        </li>
        <li id="files" class="ui-state-default ui-corner-top" onmouseover="tabOver(this)" onmouseout="tabOut(this)">
            <a href="<?php echo $filesUrl;?>">
                <?php echo$this->getIcon('OpenFile', '', 16);?>
                File templates
            </a>
        </li>
        <li id="export" class="ui-state-default ui-corner-top" onmouseover="tabOver(this)" onmouseout="tabOut(this)">
            <a href="<?php echo $exportUrl;?>">
                <?php echo$this->getIcon('BackupDatabase', '', 16);?>
                Export
            </a>
        </li>
    </ul>
</div>
