<?php
echo sprintf($this->lang->L_EDIT_RIGHT_ADDED_TO, $this->languageData['name']);
?>
<br /><br />
<?php echo sprintf($this->lang->L_EDIT_RIGHT_ADDED_EXPLAIN, $this->languageData['name'], $this->languageData['locale']);?>
<?php echo $this->lang->L_EDIT_RIGHT_ADDED_EXPLAIN;?><br />
<br /><br/>
<a href="<?php echo $this->serverUrl() . $this->baseUrl();?>">
    <?php echo $this->lang->L_CLICK_TO_LOGIN;?>
</a>
