<div id="headline">
    <h2><?php echo $this->lang->L_ADMIN;?> - <?php echo $this->lang->L_TRANSLATION_SERVICE;?></h2>
</div>
<?php
echo $this->partial('admin/head-navi.phtml', array('lang' => $this->lang));
$cycleHelper = $this->cycle(array('row-even', 'row-odd'));
?>
<h4><?php echo $this->lang->L_TRANSLATION_SERVICE;?>:</h4>
<form action="" method="post">
    <table class="bdr more-padding" summary="Set translation service">
        <tr class="thead">
            <th colspan="2"><?php echo $this->lang->L_TRANSLATION_SERVICE;?></th>
        </tr>
        <tr class="<?php echo $cycleHelper->next();?>">
            <td><?php echo $this->lang->L_TRANSLATION_SERVICE_ALLOWED;?>:</td>
            <td>
                <input type="radio" name="tsActivated" id="ts_active_yes" value="1"
                    <?php if ($projectConfig['tsActivated'] == 1) { ?>
                        checked="checked"
                    <?php } ?>
                    />
                <label for="ts_active_yes"> <?php echo $this->lang->L_YES;?></label>
                &nbsp;&nbsp;
                <input type="radio" name="tsActivated" id="ts_active_no" value="0"
                    <?php if ($projectConfig['tsActivated'] == 0) { ?>
                        checked="checked"
                    <?php } ?>
                    />
                <label for="ts_active_no"> <?php echo $this->lang->L_NO;?></label>
            </td>
        </tr>

        <tr class="<?php echo $cycleHelper->next();?>">
            <td><label for="vcsAdapter"><?php echo $this->lang->L_CURRENT_TRANSLATIONSERVICE_ADAPTER;?>:</label></td>
            <td>
                <select name="vcsAdapter" id="vcsAdapter" onchange="$('#exportConfigForm').submit();">
                    <?php foreach ($this->tsAvailAdapter as $tsAdapter) {
                        $isSeleted = (bool) (strtolower($tsAdapter) == strtolower($this->tsConfig['tsAdapter']));
                        ?>
                        <option value="<?php echo $vcsAdapter; ?>"<?php echo $isSeleted ? ' selected="selected"' : ''; ?>><?php echo str_replace('_', ' ', $tsAdapter); ?></option>
                    <?php } ?>
                </select>
            </td>
        </tr>
        <tr class="<?php echo $cycleHelper->next(); ?>">
            <td>&nbsp;</td>
            <td><button type="submit" class="Formbutton ui-corner-all" name="saveButton"><?php echo $this->getIcon('save'); ?> <?php echo $this->lang->L_SAVE;?></button></td>
        </tr>
    </table>
</form>

